### ISSUE TITLE
Investigate the development of a 4th gen BOINC credit mechanism

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#108]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grctest](https://github.com/grctest)**
_Sunday Apr 09, 2017 at 22:57 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/103_

----

We created a large thread, a lot of users expressed grievences with the current credit mechanism, David Anderson IIRC brushed off concerns, then the thread died.

https://boinc.berkeley.edu/dev/forum_thread.php?id=10953

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Friday Apr 21, 2017 at 19:16 GMT_

----

Perhaps it would be worth extracting valuable posts (excluding troll posts), highlighting well-known community members? It could help focus the discussion for new users to read..

**Comment by grctest** [comment]
At the BOINC workshop in early September 2017, the attendees all expressed an interest in improving the BOINC credit mechanism.
