### ISSUE TITLE
EMAILing inactive users (emails from BOINC)

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#11]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Friday Jan 20, 2017 at 20:35 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/10_

----

BOINC users can set in their settings that the BOINC admin (and the team founder) can email them e.g. news.

With such an email also inactive BOINC users might be reactivated

Important to adhere to laws, so it is not spam - otherwise fines :-(

see:
* [Email marketing via team founder newsletter](https://cryptocointalk.com/topic/48049-email-marketing-via-team-founder-newsletter/)
* [hangout 1](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_07_30.MD): 1:23:55

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Saturday Jan 21, 2017 at 20:47 GMT_

----

We've had success sending newsletter emails via world community grid, however mailchip mailinglist is off limits due to requiring compliance with significant EU anti-spam regulations.

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Thursday Jan 26, 2017 at 18:06 GMT_

----

[This](https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1219#entry232409) is another way to inform people

**Comment by grctest** [comment]
The majority of our userbase do not pay attention to github, we can only message our userbase through WCG. Closing the issue due to an inability to complete the task elsewhere.
