### ISSUE TITLE
setup CI that can build all platforms

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#112]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Friday Apr 14, 2017 at 05:27 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/107_

----

responsible for this task:
* @caraka and/or @Tahvok
*later more info by @denravonska

**Comment by skcin** [comment]
<a href="https://github.com/caraka"><img src="https://avatars3.githubusercontent.com/u/3311120?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [caraka](https://github.com/caraka)**
_Friday Apr 14, 2017 at 05:29 GMT_

----

This is already a work in progress

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday May 14, 2017 at 22:19 GMT_

----

How's this coming along? Is this task relating to the web service that @caraka found which was capable of building packages for like 10+ different platforms?

Are there any hurdles in the way of getting this implemented?

Cheers 👍

**Comment by skcin** [comment]
<a href="https://github.com/caraka"><img src="https://avatars3.githubusercontent.com/u/3311120?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [caraka](https://github.com/caraka)**
_Sunday May 14, 2017 at 23:19 GMT_

----

@grctest They are effectively one and the same. In a perfect world, the CI will build for all the platforms we service and serve those binaries from a common interface.

The biggest obstacle at the moment is not enough free time to dedicate to this!

**Comment by TheCharlatan** [comment]
This can be closed, new CI does that.

**Comment by tomasbrod** [comment]
Ask @grctest to get you on task maintainer team, so you can do it yourself.
