### ISSUE TITLE
finding other conference software than Mumble

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#12]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Friday Jan 20, 2017 at 20:50 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/11_

----

e.g. with more protection

mentioned in [hangout 1](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_07_30.MD): 1:25:28

* mentioned there: xmpp, teamspeak, skype, Google hangouts, trillo (unsure about name?)
* others: tox, ...

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Jan 22, 2017 at 15:43 GMT_

----

A certain advantage of mumble is that it has inbuilt recording functionality.

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Saturday Feb 04, 2017 at 21:14 GMT_

----

i went to the #mumble IRC on Freenode, and they said that the IPs shouldn't be publicly viewable. apparently, the murmur server is set up in such a way that we are probably all "admins". :\

**Comment by skcin** [comment]
<a href="https://github.com/denravonska"><img src="https://avatars0.githubusercontent.com/u/135439?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [denravonska](https://github.com/denravonska)**
_Thursday Feb 16, 2017 at 16:57 GMT_

----

As I mentioned on IRC, if we're going to be on YouTube it would be neat with a platform which supports webcams. It doesn't matter if nobody is using webcams from the start, just that the UI makes it easier to follow when listening post-broadcast.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Thursday Feb 16, 2017 at 17:31 GMT_

----

@Peppernrino Could you discuss this with Fuzzy please? Thanks :)

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Saturday Feb 18, 2017 at 09:10 GMT_

----

sure. i'll email him and see what's up.

@Erkan-Yilmaz: i think the app you were talking about was ventrilo. Tahvok(?) suggested Jitsi in the IRC yesterday, and it seems pretty awesome:
https://jitsi.org/

we were also throwing around the idea of twitch, which automatically records and uploads to youtube.

also, i created a bot for the mumble and i currently upload to a site called talkshoe:
http://www.talkshoe.com/talkshoe/web/talkCast.jsp?masterId=142176

if i could find away to bridge the mumble voice chat to the talkshoe account and simulcast, people could follow the live audio and ask IP-anonymized questions from the IRC channel (provided their IRC connection was protected with a bnc or cloak).

**Comment by skcin** [comment]
<a href="https://github.com/gustav1976"><img src="https://avatars3.githubusercontent.com/u/6749756?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gustav1976](https://github.com/gustav1976)**
_Monday Feb 20, 2017 at 07:53 GMT_

----

please switch to foss software like VNC or web-application

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Monday Feb 20, 2017 at 16:30 GMT_

----

speaking of web, something pretty cool that i found this morning: http://meetfranz.com/

also, what do you mean "switch"? mumble IS FOSS.

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Monday Feb 20, 2017 at 17:06 GMT_

----

also relevant: https://github.com/nylira/prism-break/issues/1653

good conversation to keep an eye on regarding this, instead of guessing what is the most secure. :)

**Comment by skcin** [comment]
<a href="https://github.com/grcjamezz"><img src="https://avatars0.githubusercontent.com/u/20879295?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grcjamezz](https://github.com/grcjamezz)**
_Monday Feb 20, 2017 at 19:44 GMT_

----

If there are any ideas and hardware/hosting is needed I am willing to provide it... I have been running an alt murmur server " chitchat.dopeshit.net on the default port with password " dopeshit " . Just because I host it doesn't mean i have to run/admin it and I am fine with giving access and donate it to Gridcoin and whom ever admin it..  So if there is someone out there who wants to try or test linux or windows based alt to a murmur server for mumble clients , if not this one is 100% dedicated right now as an alt if on a bi-saturday week the main was down this one would be around BUT it also could be configured completely around gridcoin and dedicated... Also , I have like a 20 slot vent server running the past 8 years we are also welcome to use...   win / lin I can provide a sandbox , just don't leave a log in it!  Also you CANNOT what so ever hide the ip without a total recode of the server , there is no setting in an .ini or anything I have spent a few weeks searching and trying things its written to be there and as their support says " if you don't want your real ip shown murmer allows connections from tor or another proxy. Thus , there is no way around it the IP is there....   

added: also I have a long running IRCd " currently running Unreal IRCD 3.2 and Anope for services " irc.dopeshit.net that I would be willing to revamp as an irc.gridcoin.us dedicated irc network.
I have hosted many networks overtime , my own with 2 hubs with 3 leafs each along with links to other networks in the past 15 years doing lots in irc host services. Right now a single ircd would be fine , willing to link 2 leafs and grow as our network does if the community likes the idea of their own gridcoin ircd with it configured as we want ie: services and registration and masked ip's etc along with SSL and securing our own chat along with providing a dedicated means of support and yes you can use web clients too.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Saturday Feb 25, 2017 at 13:51 GMT_

----

Discord was affected by cloudbleed: https://blog.discordapp.com/safety-jim-psa-cloudflare-security-issue-77a4ecc48298#.t0yd8cjce

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Thursday Mar 16, 2017 at 14:22 GMT_

----

a new one i stumbled onto: https://riot.im/

**Comment by skcin** [comment]
<a href="https://github.com/LokiToki"><img src="https://avatars0.githubusercontent.com/u/25841155?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LokiToki](https://github.com/LokiToki)**
_Friday Mar 17, 2017 at 08:14 GMT_

----

I had a quick look at riot.im. Looks simple and nice. There are IRC bridges too, so you receive PMs from IRC directly in your bridge-channel and so on... i like it (just a quick first view).

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Tuesday Apr 11, 2017 at 05:37 GMT_

----

another one i found today: https://www.pgi.com/imeet/ :)

and a list of alternatives: https://www.g2crowd.com/products/imeet/competitors/alternatives

**Comment by skcin** [comment]
<a href="https://github.com/tomasbrod"><img src="https://avatars1.githubusercontent.com/u/11995799?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tomasbrod](https://github.com/tomasbrod)**
_Tuesday Apr 11, 2017 at 07:46 GMT_

----

I like mumble because it is open source and works well and has really lightweight server which I am running too (for friends). IRC is open too and has a long tradition. I personally use xmpp and have irc bridge to #gridcoin channels. You can switch to xmpp chatroom, but I see no benefits. It has the same functionality as IRC.

Only thing missing from Mumble+IRC combo is whiteboard support. Maybe **Etherpad** (lite) can supply the need.

My two cents, please dont take as hate.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Apr 30, 2017 at 21:43 GMT_

----

During the 29th hangout, we had issues with the mumble server being laggy and cutting users out. If the issue persists in the future we may need to consider alternative platforms again.

**Comment by tomasbrod** [comment]
https://openmeetings.apache.org/
As much as I like Mumble (foss, very light on resources), it lacks Whiteboard support. The video component of other videoconferencing tools is not of much use for us, but whiteboard, impress or screen sharing would be useful for the Classroom sessions.
For interactive VoIP support, Team-Viewer is usually used, but it does not fit here.
