### ISSUE TITLE
Gridcoin payment add-on for Wordpress

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#123]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Friday Apr 28, 2017 at 15:56 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/118_

----

Who wants to help ?

* gciapita: is anyone working on a gridcoin payment add-on for wordpress?

* Erkan_Yilmaz: it exists already, !coinpayments https://wordpress.org/plugins/coinpayments-payment-gateway-for-woocommerce/
* fediverse: You can buy products with Gridcoin in these shops: https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/28
* gciapita: it doesnt erkan
* gciapita: coinpayments is full of dodgy businesses and i want no affiliation with drug dealers and pornographers, etc.
* Erkan_Yilmaz: well then you have to code one, I guess
* gciapita: i know

* BullShark: Most shop owners would want it to convert to FIAT on the back-end

**Comment by skcin** [comment]
<a href="https://github.com/denravonska"><img src="https://avatars0.githubusercontent.com/u/135439?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [denravonska](https://github.com/denravonska)**
_Friday Apr 28, 2017 at 16:50 GMT_

----

Doesn't the Coinpayments plugin cover this? https://www.coinpayments.net/merchant-tools-plugins

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday May 14, 2017 at 22:28 GMT_

----

Yes, coinpayments does cover this but gciapita doesn't want to associate himself with coinpayments because allegedly dodgey websites use it.. this is the case for all businesses, not just coinpayments, so i think it should be fine just using coinpayments..

**Comment by skcin** [comment]
<a href="https://github.com/MagixInTheAir"><img src="https://avatars1.githubusercontent.com/u/8146140?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MagixInTheAir](https://github.com/MagixInTheAir)**
_Monday Aug 28, 2017 at 10:06 GMT_

----

Any update ? Is the developpement still going ?

**Comment by grctest** [comment]
There was no development in the first place, just a suggestion to create a homebrew payment plugin - the cointopay and coinpayments plugins are sufficient & its use does not directly associate ones self with other websites which use the payment processor.
