### ISSUE TITLE
brainstorm meeting to make wallet more user-friendly

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#126]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Monday May 01, 2017 at 09:10 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/121_

----

see [hangout 29](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_04_29.MD):

* everybody agrees to this but we need concrete steps, ideas
* either everybody who has ideas adds them to the [bugtracker](https://github.com/gridcoin/Gridcoin-Research/issues)
* or we make a meeting and collect/add then those

related/can be done together: #15

**Comment by skcin** [comment]
<a href="https://github.com/Quezacoatl1"><img src="https://avatars1.githubusercontent.com/u/20362508?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Quezacoatl1](https://github.com/Quezacoatl1)**
_Sunday Jul 09, 2017 at 10:09 GMT_

----

Please also see:

https://github.com/gridcoin/Gridcoin-Research/issues/333
https://github.com/gridcoin/Gridcoin-Research/issues/331

**Comment by grctest** [comment]
Just post any UI/UX suggestions to the gridcoin-research repo https://github.com/gridcoin/Gridcoin-Research/issues
