### ISSUE TITLE
General Audience White Paper Development thread

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#139]
<a href="https://github.com/jring-o"><img src="https://avatars1.githubusercontent.com/u/29245250?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jring-o](https://github.com/jring-o)**
_Thursday Jun 15, 2017 at 01:19 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/134_

----

This is a thread to explore ideas regarding the General Audience White Paper detailed in the [Development Outline](https://github.com/gridcoin/Gridcoin-Research/issues/378).

**Comment by skcin** [comment]
<a href="https://github.com/jring-o"><img src="https://avatars1.githubusercontent.com/u/29245250?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jring-o](https://github.com/jring-o)**
_Tuesday Jun 27, 2017 at 20:17 GMT_

----

A general outline of the GAWP can be found at

https://pastebin.com/PAx4h6Nm

or

https://steemit.com/gridcoin/@jringo/a-crash-course-on-the-utility-of-gridcoin

We need sections detailing the reward protocols, pos protocols, superblocks, operation, and a general timeline.  These sections should use as little math as possible -- explain to a smart person that uses computers and currency, but has no idea how they work.

**Comment by RoboticMind** [comment]
Can this be closed now that we have the whitepaper out?

**Comment by NeuralMiner** [comment]
Closing.
