### ISSUE TITLE
make litebit.eu list Gridcoin

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#144]
<a href="https://github.com/LifeEncrypter"><img src="https://avatars0.githubusercontent.com/u/22130319?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [LifeEncrypter](https://github.com/LifeEncrypter)**
_Thursday Jun 29, 2017 at 17:36 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/139_

----

I contacted [LiteBit](https://www.litebit.eu/en) and asked them wether they would add Gridcoin to their exchange.
Since we got a qt wallet they would be able to, but they are charging a one-time fee of 0.25 BTC for adding new coins.

And copied from their response:
"What LiteBit has to offer
-Buying GRC
-Selling GRC
-Hosted wallet for GRC"

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Thursday Jun 29, 2017 at 22:01 GMT_

----

see also in the [forum](https://cryptocurrencytalk.com/topic/85089-make-litebiteu-list-gridcoin/)

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Friday Jun 30, 2017 at 01:21 GMT_

----

If they add Gridcoin for free then it sounds good, I don't think we should be paying a bounty for an exchange that isn't listed on coinmarketcap: https://coinmarketcap.com/exchanges/volume/24-hour/all/

**Comment by skcin** [comment]
<a href="https://github.com/Quezacoatl1"><img src="https://avatars1.githubusercontent.com/u/20362508?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Quezacoatl1](https://github.com/Quezacoatl1)**
_Friday Jun 30, 2017 at 05:41 GMT_

----

It is not an exchange, it is a payment processor exchanging fiat to crypto and back. Like holytransactions.

**Comment by skcin** [comment]
<a href="https://github.com/silent5am"><img src="https://avatars3.githubusercontent.com/u/29739794?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [silent5am](https://github.com/silent5am)**
_Friday Jun 30, 2017 at 05:51 GMT_

----

I have never heard of them. How trustworthy are they? How do they handle privacy/security of customers, etc? Are there any reviews apart from those on their site (which could be fake)?

In general, are fees to list a currency and allow for trade a standard among all services?

Maybe get in contact with one of the more [popular/higher rated](https://www.bestbitcoinexchange.io/) services first and find out if they charge fees and/or what their conditions would be? Then compare with LiteBit and decide if it is a good move based on all the facts.

**Comment by skcin** [comment]
<a href="https://github.com/fab-io"><img src="https://avatars0.githubusercontent.com/u/5780424?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fab-io](https://github.com/fab-io)**
_Friday Jun 30, 2017 at 08:46 GMT_

----

just my 2 cent.

I've used it to buy some BTC and ETH, and so far no problems, BTW my experience is very limited.

Said that, I don't think we have to pay to listed there, since they already earn applying a margin, for example at the moment of writing they sell BTC at €2302 while for Bitstamp BTC is at €2209.

Edit: I'd like to have a pool on this point

**Comment by skcin** [comment]
<a href="https://github.com/LifeEncrypter"><img src="https://avatars0.githubusercontent.com/u/22130319?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LifeEncrypter](https://github.com/LifeEncrypter)**
_Friday Jun 30, 2017 at 09:19 GMT_

----

I also bought btc a few times from them. Only for a little more than 50€, but i had absolutly no problems.

**Comment by skcin** [comment]
<a href="https://github.com/xPh03n1x"><img src="https://avatars2.githubusercontent.com/u/2136825?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [xPh03n1x](https://github.com/xPh03n1x)**
_Wednesday Jul 19, 2017 at 00:00 GMT_

----

I just tried using them to get some BTC, which in turn I'd convert into GRC, but their payment options are rather limited and not as flexible as advertised. Although CC payments are advertised, it doesn't seem like you can use a card issued by US bank.

I agree that paying 0.25 BTC to be listed there doesn't seem to be worth it at the moment.

**Comment by grctest** [comment]
Sufficient consensus against paying the fee to get listed.
