### ISSUE TITLE
LINUX client should have same features as Windows client

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#15]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Saturday Jan 21, 2017 at 02:18 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/14_

----

Features that are missing in the linux wallet:
* no participation in superblock
* UIs: no voting UI, no foundation UI, no Neural Network UI

This is on the [roadmap](https://steemit.com/gridcoin/@erkan/gridcoin-roadmap-2017-2019) for 2017 June/July.

mentioned in [hangout 1](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_07_30.MD): 0:40:00 - 0:42:00

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Saturday Jan 21, 2017 at 20:36 GMT_

----

Rob has been discussing this recently, and it has been included in the roadmap.

**Comment by skcin** [comment]
<a href="https://github.com/TG13088"><img src="https://avatars0.githubusercontent.com/u/25274236?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TG13088](https://github.com/TG13088)**
_Sunday Jan 22, 2017 at 02:42 GMT_

----

Ideally the UI should be Operating System neutral and uniform across all implementations.  This will lead to less confusion for the new user and less aggravation for the Help/Support people that answer their questions.  It should be a small matter to *grey out* items that don't pertain to the operating environment it is being hosted under.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Tuesday Apr 18, 2017 at 00:04 GMT_

----

> @caraka [wrote](https://github.com/gridcoin/Gridcoin-Research/pull/233#issuecomment-294572979):
> The 'windows first' attitude is exactly why we have so many problems with the neural network. For the reputation of gridcoin, Rob, team, etc, we should focus on good c++ code that works on ALL machines, the way that it was intended. Why? because windows isn't nearly as common among gridcoin users as people would think. Because coding for windows and then 'back filling' is nonsense when the language you are coding in is universal. The sooner we lose the .net code bolted into gridcoin, the better off we'll be. We're more stable with diversity, not a monoculture.

I agree that getting all functionality to c++ is important, there are many linux users within the Gridcoin network. We should place a bounty on this development task.

Related tasks: 
https://github.com/gridcoin/Gridcoin-Research/issues/212
https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/94

**Comment by jamescowens** [comment]
This can finally be closed! ;).

https://github.com/gridcoin-community/Gridcoin-Research/releases/tag/4.0.3.0
