### ISSUE TITLE
add Gridcoin to the TenX Card, a debit (and, in time to come, credit) card

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#150]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Monday Jul 24, 2017 at 17:01 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/145_

----

* These people are offering a credit card that converts your crypto directly to USD, EUR or YEN
* They just finished raising $80million
* If we could get them to accept Gridcoin, then GRC would become a major player in crypto.

From [TenX whitepaper](https://www.tenx.tech/whitepaper/tenx_whitepaper_final.pdf):

"To the end-user, we offer the TenX Card, a debit (and, in time to come, credit) card, with an
accompanying TenX Wallet, a mobile wallet that can be funded not only with Bitcoin (**BTC**),
Ether (**ETH**), and Dash (**DASH**) as currently possible, but also with virtually any blockchain
asset in time to come. TenX payment facilities which include the physical and virtual debit card
can be used in almost **200 countries at over 36 million points of acceptance** today. This is
possible as we have card issuance partnerships with major credit card companies such as **VISA**
and **Mastercard**.

Moreover, users and businesses can exchange their blockchain assets seamlessly from one user
to another in a decentralized manner, removing any risk that is usually associated with current
centralized solutions."

[their website](https://www.tenx.tech)

**Comment by grctest** [comment]
http://ocash.io/ will support open.grc when launched, tenx support is unlikely in the short to medium term.
