### ISSUE TITLE
add Gridcoin to Chinese exchange binance dot com

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#151]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Wednesday Jul 26, 2017 at 13:55 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/146_

----

Erkan: the website looks unfinished in my browser
* careful

until further info, assigned to myself

---

user M asked the Chinese exchange binance.com to add GRC

This is the reply: (A)

by M:
> There  are some technique problems that I cannot handle
‎> Would you guys like to fill it?
> ‎To contact binance, just send emails to:  oyyq@binance.com mailto:oyyq@binance.com 
> ‎This is a new Chinese exchange,  so the price will rise if succeed

---
(A) 

Regarding to your suggestion, can you give us further information about Gridcoin. We have several questions in this link, please fill out in it.

https://docs.google.com/document/d/1GKmLZ16HYeKpvA3mI8fG_iN9zQpgq7OX0iUhFOXRY3w/edit 

thanks,

Best wishes,

YQ

---

the google doc lists these: (B)

---
(B) 

Listing a Coin on Binance.com

Please provide the following information if you wish to list your coin on Binance:
Market Cap: What’s your current market capitalization?
Liquidity: Is your coin traded on any other exchange?  What’s the daily trading volume?
Volatility: What’s the price history of your coin?  Where can we see a chart?
Core value: What problem does your coin solve?  Why does it have value?  Why would the value increase over time?
Team: Who is on your team?  How many people?
Development: What stage of development are you in?  Is your source code available on github?
Website: A link to your website.
ICO: Did your coin go through an ICO?  Please provide details, which ICO platform did you use?  How much was raised?
Whitepaper: A copy of your whitepaper, if applicable.
How many users are in your community?  How can we join your community?
Other factor: anything else we should know about your coin that helps it’s listing?  Send us as much info as you can.

Wallet Questions:
Do you have a linux wallet?
How do create a large number of addresses in your wallet?
How to monitor a large number of addresses for deposits?
How to sweep coins from a large number of addresses?
How to sign transactions offline?
Where is your blockchain explorer?

---

related: #89

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Tuesday Aug 29, 2017 at 13:26 GMT_

----

see also #3

**Comment by grctest** [comment]
They're adding one cryptocurrency to their exchange per month, given the number of cryptos applying to this exchange we should focus our efforts elsewhere.

**Comment by mikelambert** [comment]
They currently seem to be adding coins every couple days now, so may be worth considering this again? (The left-hand navbar lists coins and the articles have post-dates.)

https://support.binance.com/hc/en-us/articles/115003793551-Binance-Lists-AppCoins-APPC-

Though the new form to request listing on Binance is over at:
https://docs.google.com/forms/d/e/1FAIpQLSfhibOzGG7I-JIw0Ofj3kFEj9oMhnR-GkajMPhJp7H1URyHJA/viewform


On a speculative bent, I suspect opening GRC to more asian "investors" looking for cheap coins (where many of the masses evaluate "cheapness" by value-per-coin, not market-cap, and look for sub-$1-ish coins), might help raise GRC market value, and then help grow the GRC mining base, too. Not sure if that should be a motivating factor in this github issue, though.

**Comment by tomasbrod** [comment]
One of the motivating issues is the crap that is being thrown at US (and other) exchanges. There are high fees and unless you sign your soul to them, low withdraw limit. For people that want just to exchange and trade it gives a lot of hassle. More alternatives is nice.
Flypme is an example of hassle-free exchange (not market, just strait exchange).

**Comment by razorshaman909** [comment]
From my past experience, it seems that listing in binance not just that simple, including paying 20-100BTC. There is a community vote option, but with current popularity, it seems to be rather hard.
