### ISSUE TITLE
Add Gridcoin to WikiLeaks ' digital cash systems

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#153]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Wednesday Aug 02, 2017 at 06:26 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/148_

----

See [this tweet](https://twitter.com/wikileaks/status/892368985932648449) by WikiLeaks
* What other digital cash systems should @WikiLeaks add to https://wikileaks.org/donate ?

As choice is given:
* Etherium (45%)
* Monero (20%)
* Zcash (11% )
* Other (24%)

The vote is still ongoing for about 6h!
* no matter what happens in next 6h, this task is an ongoing effort to bring GRC onto WikiLeaks' platform!

Please reply to that tweet, and also use hashtag:
* [#GridcoinWikileaks](https://twitter.com/hashtag/gridcoinwikileaks?f=tweets&vertical=default&src=hash)

Further reading:
* [Vote For Gridcoin On Wikileaks !!](https://steemit.com/gridcoin/@trumpman/vote-for-gridcoin-on-wikileaks)

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Wednesday Aug 02, 2017 at 19:17 GMT_

----

result of poll, with 12.204 votes:
* 45% Etherium
* 21% Monero
* 11% Zcash
* 23% Other

**Comment by grctest** [comment]
Likely will never happen.
