### ISSUE TITLE
list all Gridcoin media at 1 place

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#154]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Thursday Aug 10, 2017 at 17:55 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/149_

----

There is:

new logo:
* [repository for storage of all Marketing & Branding assets](https://github.com/gridcoin-community/Gridcoin-Marketing)
* new [logo packs](https://steemit.com/gridcoin/@joshoeah/gridcoin-logo-packs-get-em-while-they-re-hot)

<br>

and:
* [ads, images and banners](https://cryptocurrencytalk.com/topic/50138-gridcoin-ads-images-and-banners/)
* [images on website](https://github.com/grctest/Gridcoin-Site/tree/master/source/Images)
* contest: [create Gridcoin media](https://steemit.com/gridcoin/@erkan/1million-block-event-with-prize-create-gridcoin-media-pictures-videos-songs) (pictures, videos, songs, ...)
* [What do you think about this new picure?](https://steemit.com/gridcoin/@erkan/what-do-you-think-about-this-new-gridcoin-picture) (incl. branding, new logo)

see also task:
* [list + renew videos about Gridcoin (out-of-date)](https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/114)

**Comment by skcin** [comment]
<a href="https://github.com/MagixInTheAir"><img src="https://avatars1.githubusercontent.com/u/8146140?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MagixInTheAir](https://github.com/MagixInTheAir)**
_Monday Aug 28, 2017 at 09:49 GMT_

----

Any media with the new logo ?

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Monday Aug 28, 2017 at 10:03 GMT_

----

seen the "logo packs" link above?

**Comment by skcin** [comment]
<a href="https://github.com/MagixInTheAir"><img src="https://avatars1.githubusercontent.com/u/8146140?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MagixInTheAir](https://github.com/MagixInTheAir)**
_Monday Aug 28, 2017 at 10:11 GMT_

----

Yes. Images with the old logo should be marked as outdated, and we should involve the community into making banners and ads with the new one :) sadly I don't have the skills

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Monday Aug 28, 2017 at 10:28 GMT_

----

ok, I have added the link on top now

**Comment by grctest** [comment]
https://github.com/gridcoin-community/Gridcoin-Site/issues/35 Will add this information to the gridcoin website.
