### ISSUE TITLE
Migrate repo's issues to gridcoin-community org?

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#155]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grctest](https://github.com/grctest)**
_Saturday Aug 26, 2017 at 15:19 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/150_

----

@Erkan-Yilmaz Can you please migrate this repo's issues to the [gridcoin-community repo](https://github.com/gridcoin-community/Gridcoin-tasks/) using the following tool: https://github-issue-mover.appspot.com/

Thanks.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Monday Sep 18, 2017 at 00:21 GMT_

----

@Erkan-Yilmaz Any update on this? Have issues utilizing the linked tool? I used it to move repos from my grctest account to the gridcoin-community repo.

**Comment by grctest** [comment]
Completed by @skcin , great work!
