### ISSUE TITLE
improve UI

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#16]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Saturday Jan 21, 2017 at 02:20 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/15_

----

* NeuralMiner: 
  * "doesn't look professional"
  * "I really like how slick the NXT wallets look: very modern and polished"
* this needs more input

mentioned in [hangout 1](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_07_30.MD): 0:40:00 - 0:42:00
mentioned in [hangout 4](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_08_27.MD): 1:02:00

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Saturday Jan 21, 2017 at 19:27 GMT_

----

Perhaps when we upgrade from QT4 to QT5 we can move some of the UI about?

The chat and exchange buttons should perhaps show more than just 1 option? The exchange button should remind users not to store their coins on an exchange for a long period of time.

**Comment by skcin** [comment]
<a href="https://github.com/TG13088"><img src="https://avatars0.githubusercontent.com/u/25274236?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TG13088](https://github.com/TG13088)**
_Sunday Jan 22, 2017 at 02:42 GMT_

----

Ideally the UI should be Operating System neutral and uniform across all implementations.  This will lead to less confusion for the new user and less aggravation for the Help/Support people that answer their questions.  It should be a small matter to *grey out* items that don't pertain to the operating environment it is being hosted under.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Tuesday Jan 24, 2017 at 11:39 GMT_

----

# Relevant:

[Brainstorming improvements to the wallet's UI](https://cryptocointalk.com/topic/49625-brainstorming-wallet-ui/)
[Translating the client to chinese](https://cryptocointalk.com/topic/40085-translations-simplified-chinese-for-gridcoin-gui/) == https://github.com/gridcoin/Gridcoin-Research/issues/173

**Comment by skcin** [comment]
<a href="https://github.com/denravonska"><img src="https://avatars0.githubusercontent.com/u/135439?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [denravonska](https://github.com/denravonska)**
_Wednesday Feb 08, 2017 at 17:37 GMT_

----

Make staking a matter of changing a radio button from Off to On. If a beacon is needed the user is notified and one is sent, otherwise the wallet is put in the correct state.

**Comment by skcin** [comment]
<a href="https://github.com/denravonska"><img src="https://avatars0.githubusercontent.com/u/135439?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [denravonska](https://github.com/denravonska)**
_Wednesday Feb 08, 2017 at 17:59 GMT_

----

It would be very neat if the wallet UI can be attached to another wallet. For example, I run my wallet headless but very often I would like a UI attached to it to get a better overview. Either that or embedding a web UI inside the headless wallet.

**Comment by skcin** [comment]
<a href="https://github.com/JeramiahSawyer"><img src="https://avatars3.githubusercontent.com/u/1538658?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JeramiahSawyer](https://github.com/JeramiahSawyer)**
_Thursday Feb 09, 2017 at 01:19 GMT_

----

I have been working on this sketch design in photoshop.
Thoughts? Questions? Concerns?
-- Font will be swapped with something maybe less bold
--- Maybe keep font for numerals? its kind of sexy on numbers, just not text.
---- Send/Recv and Transactions icon is now one for drop-down for appropriate selections.
----- Added beacon button as well to the right of home
----- vote box on side for keeping all users on constant update 
![image](https://cloud.githubusercontent.com/assets/1538658/22765004/861f49d4-ee33-11e6-9fb8-21c8cb0051d5.png)

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Thursday Feb 09, 2017 at 11:55 GMT_

----

added as a topic for the [next hangout](https://steemit.com/gridcoin/@cm-steem/gridcoin-community-hangout-024-18th-feb-2017-9pm-gmt-rsvp-and-suggest-topics)

**Comment by skcin** [comment]
<a href="https://github.com/gustav1976"><img src="https://avatars3.githubusercontent.com/u/6749756?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gustav1976](https://github.com/gustav1976)**
_Tuesday Feb 14, 2017 at 15:40 GMT_

----

I'd minimize the unused space in between boxes and move the icontray to the lower left. cool icons!

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Friday Mar 03, 2017 at 14:32 GMT_

----

from @denravonska 

* We should copy that :) https://i.imgur.com/UfEoWoT.png
* or this: http://drasticraven.deviantart.com/art/Bitcoin-Wallet-UI-449781623

**Comment by skcin** [comment]
<a href="https://github.com/denravonska"><img src="https://avatars0.githubusercontent.com/u/135439?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [denravonska](https://github.com/denravonska)**
_Friday Mar 03, 2017 at 14:33 GMT_

----

I like how clean and simple they are. The one by DrasticRaven is maybe on the too simplified side, but I like the aesthetics of it.

**Comment by skcin** [comment]
<a href="https://github.com/LokiToki"><img src="https://avatars0.githubusercontent.com/u/25841155?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LokiToki](https://github.com/LokiToki)**
_Monday Mar 06, 2017 at 09:56 GMT_

----

It's not a simple task. When you look at the modern and fancy wallets you will recognize that they are all minimalist and clean. Normally I like the "keep it simple" principle but you have to consider what kind of people are in the grc community. I dislike the loss of control when something gets too simple due to design. I got a bunch of UX Design training courses and every time they advise to keep the users demands in mind.

I think the actual design is a bit confusing and messed up but i have no concrete idea to improve tbh. The best way to work on this is to discuss it with end-users. Maybe i have an idea later this week.

**Comment by skcin** [comment]
<a href="https://github.com/jericomanapsal"><img src="https://avatars2.githubusercontent.com/u/25622785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jericomanapsal](https://github.com/jericomanapsal)**
_Friday Apr 07, 2017 at 13:46 GMT_

----

Just a thought, aside from visualization of data, we'd also want to access it on every platform (dumb assumption). I suggest a web interface that is simple and straightforward. Take a look at this [demo](http://demo.geekslabs.com/materialize-v1.0/index.html) Since the UI is web-based, the core process will run in background while being viewed/controlled on, say localhost:12345. Giving an option to bind to an interface makes the remote viewing and controlling of the wallet easier. Of course the option to SSH and gridcoinresearchd should not be abandoned.

**Comment by skcin** [comment]
<a href="https://github.com/denravonska"><img src="https://avatars0.githubusercontent.com/u/135439?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [denravonska](https://github.com/denravonska)**
_Friday Apr 07, 2017 at 14:19 GMT_

----

@jericomanapsal I want it pretty much exactly as in that suggestion. Clean and modern. All of the information is available as RPC commands, so as a bonus we would eat our own dog food and make sure the RPC is solid. It should also be possible to embed that in a standard OS UI container for those who prefer an actual application (think Slack web vs Slack app).

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Friday Apr 07, 2017 at 14:52 GMT_

----

There's active work on the GUI at the moment: https://github.com/gridcoin/Gridcoin-Research/pull/233

---

Help brainstorm an UI:
![image](https://i.imgur.com/KsMkkYD.png)
![image](https://i.imgur.com/hpwR91H.png)
![image](https://i.imgur.com/w396gF3.png)
![image](https://i.imgur.com/43fUhkN.png)
![image](https://i.imgur.com/JiITeeq.png)

---

What do people think of 'material' design? 
https://material.io/guidelines/
https://material.io/icons/

**Comment by skcin** [comment]
<a href="https://github.com/LokiToki"><img src="https://avatars0.githubusercontent.com/u/25841155?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LokiToki](https://github.com/LokiToki)**
_Monday Apr 10, 2017 at 08:13 GMT_

----

Although experts say that Material is pretty much outdated i like it a lot and it's better than the current 90's design. :) The Daemon-Web-Control approach is my favorite too. Especially when the daemon gets smaller.

**Comment by skcin** [comment]
<a href="https://github.com/3ullShark"><img src="https://avatars3.githubusercontent.com/u/4031207?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [3ullShark](https://github.com/3ullShark)**
_Monday Apr 10, 2017 at 08:48 GMT_

----

@jericomanapsal @denravonska if you plan to go the service and RPC frontend route check out [Electron](https://electron.atom.io/) it's an open source engine made by the creators of Atom that is used by Slack, Visual Studio Code and Atom etc to build cross platform desktop apps using JavaScript, HTML and CSS.

**Comment by grctest** [comment]
More appropriate to continue this discussion within the gridcoin-research repo than in the tasks repo. AFAIK, both @Peppernrino and @skcin have been working on improving the UI massively and we should be expecting a release soonish.
