### ISSUE TITLE
type 1 Diabetes needs compute power

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#162]
<a href="https://github.com/Wizardofoddz"><img src="https://avatars0.githubusercontent.com/u/11368906?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Wizardofoddz](https://github.com/Wizardofoddz)**
_Monday Sep 04, 2017 at 07:07 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/157_

----

Plug dataset into to crunch for Massachusetts General Hospital
http://www.faustmanlab.org/research/BCGTrials.html
https://www.diabetes.co.uk/forum/threads/but-weve-gone-to-the-moon.111946/page-2#post-1318872
"
It needs the researcher / s to be able to spit the data they need crunched in to small chunks so that it can be downloaded as work units also.

Perhaps if we are lucky someone may see this thread and act on it with WGC and BOINC."

Partnered with WCG and BOINC and Computeforcancer.org

**Comment by skcin** [comment]
<a href="https://github.com/Wizardofoddz"><img src="https://avatars0.githubusercontent.com/u/11368906?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Wizardofoddz](https://github.com/Wizardofoddz)**
_Monday Sep 04, 2017 at 07:10 GMT_

----

DiabetesTrial@partners.org

Phone

Call us at 617-726-4084

Mail

Correspondence can be mailed to:
Dr. Denise Faustman
Massachusetts General Hospital-East 
Immunology Labs
Building 149, 13th Street, Room 3602 
Charlestown, MA 02129

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Monday Sep 04, 2017 at 08:20 GMT_

----

thx for the info
* the forum info you linked is like 40 weeks old
* and on page 3 user moonshot seems to offer help (non-profit that runs BOINC), 5 weeks ago

So, you want someone now to contact the Faustman Lab ?

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Saturday Sep 09, 2017 at 09:37 GMT_

----

ping @Wizardofoddz

**Comment by grctest** [comment]
By all means they can create their own BOINC project, but we aren't going to create a project for them.
