### ISSUE TITLE
328 GRC bounty: notify user in the wallet about important issues (new mandatory version, ...)

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#167]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Wednesday Sep 13, 2017 at 10:47 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/161_

----

We've an open issue [since 13 months](https://github.com/gridcoin/Gridcoin-Research/issues/114) (August 2016) :-(

<br>

This is a feature we need with each update/upgrade for Gridcoin:
* currently we do this - manually - over the existing communication media, but:
  * this is slow
  * may not reach everyone

<br>

Current discussed approaches are:
1. monitoring a burn address
2. making an "alert"
3. in case none of the mentioned/coming ideas work: 
  * think about an option that is "unsafe" but works (e.g. activate in options, but tells clearly: "some of your data may leak for this feature to work correctly" or so) :-(

<br>

If you would like to sponsor this issue, please send your GRCs to address (this resides in my wallet):
* [SF5s9HZBYc3fTPLRsVQtETfGktz6gR4mjK](https://gridcoinstats.eu/address/SF5s9HZBYc3fTPLRsVQtETfGktz6gR4mjK)

As public sponsor your name will be listed in all related announcements:
* e.g. you could also come to IRC  and tell me in private beforehand how much you will donate, it might be hard to get your details otherwise. My IRC nick is: Erkan_Yilmaz
* You can of course also donate anonymously.

<br>

The bounty will be paid out to that person that:
1. sends a merge request to the [offical repo](https://github.com/gridcoin/Gridcoin-Research) that works AND 
2. is implemented in Gridcoin also:
* about 2.: e.g. option3 ("unsafe impl.") above might not be accepted? 
  * needs discussion: _security of network_ vs. _security of individual_ (personally, "security of individual" is more important to me: I added option3 only so we can "move forward" with the issue. Also, I link to the [fork warning](https://github.com/gridcoin/Gridcoin-Research/issues/270) which seems so far to prevent the issue going forward?)
  * if option3 would be selected: after discussion also needs voting on community? but if it is per default off AND gives user clear info about consequences when enabling: then probably not...

<br>

Thanks

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Wednesday Sep 13, 2017 at 14:08 GMT_

----

* see also comments [here](https://steemit.com/gridcoin/@erkan/rfb-request-for-bounty-notify-users-in-gridcoin-wallet-about-important-issues-new-mandatory-version)

<br>

* Current sponsors:
  * 150 GRC (by @personthingman2)
  * 100 GRC (anonym)
  * 78.04 GRC (by @tomasbrod)

**Comment by grctest** [comment]
> monitoring a burn address

If an user is on a fork, they'll never see a transaction hitting this burn address unless it was sent ahead of time (or if the messenger forced themselves to join a forked chain to send the message) - the problem then becomes who would be authorized to send notices to this burn address? A spam problem would likely occur.

> making an "alert"

Emergency alerts are already possible, not utilized by Rob (only person capable of doing so).

We could implement something simple like:

```
If (Difficulty < 0.5) { alert("You may need to upgrade your client!");}
```

> think about an option that is "unsafe" but works (e.g. activate in options, but tells clearly: "some of your data may leak for this feature to work correctly" or so) :-(

Yeah, let's not implement 'unsafe' functionality if we can avoid it..

> security of network vs. security of individual (personally, "security of individual" is more important to me: I added option3 only so we can "move forward" with the issue. Also, I link to the fork warning which seems so far to prevent the issue going forward?)

The security of the network is the absolute priority, without it the security of the individual is irrelevant.

> If you would like to sponsor this issue, please send your GRCs to address (this resides in my wallet):

I feel that this kind of fundraising is inappropriate and borderline begging. If you desire a feature to be implemented then either program it or fund its development yourself; if you lack both the programming capabilities and the funding to pay devs, then creating a foundation poll within the Gridcoin client as it's the established process for requesting funds to be paid to developers for a feature (rather than requesting users send you funds for a feature which may never be implemented).

**Comment by tomasbrod** [comment]
My PR https://github.com/gridcoin/Gridcoin-Research/pull/693 applies to this task. #177 would be better, but this is all I got.

**Comment by jring-o** [comment]
What is going on with this issue?

It will be closed in 7 days if there is no update.

**Comment by jamescowens** [comment]
@iFoggz is working on a PR that willl address this issue.

**Comment by barton2526** [comment]
This is possibly fulfilled with the new update check

**Comment by jamescowens** [comment]
I believe it has.

**Comment by towstone** [comment]
Can someone confirm who the bounty should go to? I'd like to see if we can close another one.

**Comment by towstone** [comment]
Bounty paid:
TX ID: 56b549ca8617e7be98e45bc1353081282b59721071ae775b0b5b2d56b0dabca0
TX ID: ddf6c2d00cef29e9a97ed9cf1a64d6e707f48ff652dba8f62e86e4f6afd80bf9
Can this be closed?

**Comment by jamescowens** [comment]
Yep. Thanks!
