### ISSUE TITLE
investigate exchange flyp.me more: convert from/to Gridcoin (seems like ShapeShift)

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#168]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Monday Sep 18, 2017 at 16:54 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/162_

----

Someone from [flyp.me](https://flyp.me) (see page 3 on their whitepaper: it is built and managed by the current team at [HolyTransaction](https://holytransaction.com)) approached me on IRC about their new exchange:

<br>

I only checked it out quickly, see pic below:

![fly](https://user-images.githubusercontent.com/642286/30553700-55b96b26-9ca2-11e7-9978-04617cf13c58.png)

<br>

For more, please investigate yourself.

I was told also:
* they are private, accountless (no registration) and 
* already support 13 cryptocurrencies and 169 pairs. 
* "It's easy to use and we only need input/output address and amount."
* They have released an open [API](https://flyp.me/api) that allows to accept payment in the supported cryptocurrencies and instantly start an accountless exchange to Gridcoin

<br>

see their twitter account [here](https://twitter.com/flyp_me)

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Monday Sep 18, 2017 at 17:09 GMT_

----

tweeted about this [here](https://twitter.com/GridcoinIRC/status/909826183910625282)

**Comment by grctest** [comment]
Nothing to investigate - we're already integrated.
