### ISSUE TITLE
make GIMPS (Great Internet Mersenne Prime Search) available for Gridcoin rewarding

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#169]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Thursday Sep 21, 2017 at 10:22 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/163_

----

QuintLeo suggested [here](https://bitcointalk.org/index.php?topic=324118.msg22063326#msg22063326):
* "Perhaps Gridcoin should add support for the GIMPS (Great Internet Mersenne Prime Search) project - the holder of something like 8 of the CURRENT "largest primes known"."

<br>

From what I see quickly, they:
* are active since 1996
* Mersenne Research, Inc., a non-profit corporation charitably
  * see [legal](https://www.mersenne.org/legal/)
* have stats:
  * [overall user stats](https://www.mersenne.org/report_top_500/) (top500)
  * [team stats](https://mersenne.org/report_top_teams/)

<br>

It has to be investigated more...
* e.g. update frequency, server load, ...
* e.g. also if a new BOINC project could be made with a wrapper?
* ...

<br>

Definitely a good thing when "something else" besides BOINC is added to Gridcoin
* see [weaknesses](https://github.com/Erkan-Yilmaz/GRC/issues/25#issuecomment-320258684)

**Comment by grctest** [comment]
Not a BOINC based project, it's up to the project owners to set up a BOINC project to tap into more computing power.
