### ISSUE TITLE
proposal: Change to Constant Interest per Block

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Tasks#175]
First, you may have noticed, that a poll was created in a topic of Interest payments. Currently a Coin\*Age interest calculation is used, which uses the Age multiplied by Value of the UTXO multiplied by the interest rate (in correct units) to calculate the reward amount. The main problem with Coin\*Age interest is that, you continue to collect interest even when your wallet is offline. As it is not convenient to keep the wallet open and online 24/7. Big holders noticed this, keep their wallets closed for most of the time and come online only to collect their interest. To keep the network secure, it is important, that big holders keep their wallet open and unlocked for staking.

But they are rewarded the same amount for basically not doing that. For that there exist a *Fixed interest reward*, which was invented in PoSv3 of Blackcoin. It works by not taking the value and age into account and instead paying constant amount as an Interest per block. The higher balance you hold, the more often you stake, and the more of this interest reward you get. But it you take your wallet offline, you are loosing this rewards.

https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/158

**Comment by NeuralMiner** [comment]
CBR included in next mandatory, Betsy.
