### ISSUE TITLE
coding task: Implement a News / Feed tab

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Tasks#177]
Create GUI for News Feed tab, like BOINC Manager has.

Pull data from:
* blockchain messages (could be used for general news)
* alert protocol (works accross forks, good for warnings)
* creation of Polls
* additions and removals of projects to white-list

It is not yet clear whether this feature is wanted. Related to #167.

**Comment by tomasbrod** [comment]
There already exists an alert protocol, independent of the blockchain that can be used to broadcast a message. Like transactions spread across forks, the Alert messages too. Currently, master key is required to sign the alert, which is good. The key should be rotated and redistributed to responsible people who are active memebers.

**Comment by tomasbrod** [comment]
@Peppernrino Suggested adding:
1. flag/icon to each item, representing it's severity and type
   * eg: casual poll, actionable poll, alert, news article
2. system of  "mark as read", so the acted-upon or ignored items will sort lower.

**Comment by RoboticMind** [comment]
What if "news sources" were voted in and they signed everything with their private keys. Example: Gridcoinstats.eu could be voted in as a source of news. They could push news to Gridcoin users signed by their private key.
