### ISSUE TITLE
coding task: Display more details of transaction

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Tasks#179]
* [x] stake details (cpid, mag, reward amounts...)
* [x] block hash transaction is included in
* [ ] beacon details (cpid, pub key, ...)
* [x] vote, poll, project, etc "Message" details
* [ ] mark Message/Contract transaction in transaction list (eg: beacon)

I want this information to be available when user double clicks on a transaction in wallet to view transaction details. And mark as in maybe a different icon for contract/message tx. And mark with different icon when a tx comes with a message.

**Comment by Foggyx420** [comment]
changed the code around on this one as the map was ordered which doesnt really support clearly displayed information. Ive completed the beacon one and i've ran into a big issue with voting. get an out of memory error when putting mtx.hashBoinc into the const string. the hashBoinc for voting is 10K to 20K depending on persons history of transactions etc

**Comment by tomasbrod** [comment]
@Foggyx420 Which beacon details are shown? If you can give me an example i will check the box.
