### ISSUE TITLE
Prevent duplicate superblocks

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Tasks#182]
Reject duplicate superblocks and superblocks which come when one is not needed on network level.

**Comment by Foggyx420** [comment]
hrm iterate back so many blocks back and see if a duplicate is found and if so return error?

**Comment by tomasbrod** [comment]
Also: 4d33b0e4a2a7eb9056ce0085364442d0ed83ae16

**Comment by tomasbrod** [comment]
done
