### ISSUE TITLE
Define a set of task Labels and their purpose

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Tasks#184]
Primary use of labels is filtering of the task. When there are more than one page of tasks, it is tedious to picking one to work on. Different contributors have various capabilities so they will use the labels to quickly filter out the tasks that they can't help with.

**Comment by jring-o** [comment]
Threw this together fairly quickly.  Everyone here knows better than I do what is needed, but here's a start.

Existing Labels:

> BOINC - Proposed improvements to the BOINC platform. 
> Bounty - Specific task with committed bounty
> Bug - No specific Examples
> Discussion - General discussion regarding a specific topic, noncommittal 
> Docs - Tutorials - Documents for use and tutorials
> ~Duplicate~
> Enhancement - Proposals that may or may not be applied
> Exchanges - Tasks related to exchanges
> Feedback Needed - Discussion + Help Wanted + idea
> Hangout - Tasks related to the hangout
> Help Wanted - Coding tasks + noncoding tasks
> Idea - Discussion + feedback needed + help wanted 
> Inform Our User Base - Education based
> ~Invalid~
> Marketing - Marketing discussions and tasks
> Network Mandatory - Discussions, ideas, and proposals that would require mandatory updates
> Newcomers - Ways to help new users
> Poll - Information on polls
> Question - None
> Roadmap - Discussions, ideas, and proposals that could be put on a roadmap
> Wallet - Discussions, ideas, proposals, and tasks that involve the wallet
> Wontfix

Proposed Labels:

Each thread should have at least 1 main label and 1 sub label.

For example:
Documentation | Discussion/Idea
Feature | Proposal
Wallet | Task | Bounty
Documentation | Outreach | Product
Feature | Education | Task/Help Wanted

Main Labels:
Documentation - A thread containing a document anyone can use.
Feature - A code development based thread.
Education - A thread about informing the userbase.
Poll - A thread about a poll in the client.
Outreach - A thread about outreach and/or marketing.
Wallet - A thread about the Gridcoin main client.

Sub Labels:
Discussion/Idea
Question
Task/Help Wanted
Proposal
Bounty
Bug
Product
