### ISSUE TITLE
Survey poll: gridcoin blockchain suppored by BOINC

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Tasks#186]
**WIP**

Purpose of this multi-choice poll is to find out what annoys (word?) girdcoin users the most. The results can will be used to build a view about what problems community finds the most important and also may be used to prioritize work of the contributors. This is a survey poll, the results do not authorize any community-affecting change. 

Question: **Do you think that in addition to stake held, BOINC work should also be weighted in securing the blockchain?**
Expiration: ~40 days, 7th January 2018 14:07:44 CET~

Options:
- Yes
- No
- Abstain

This poll will be created in one variant.
Title: `survey:_gridcoin_blockchain_suppored_by_boinc`~409904~
Share type: Magnitude+Balance

If desired, the discussion can take place on another platform. Let me know, and I will link it here.

**Comment by jring-o** [comment]
I think this should be delayed so we can push for more discussion and get more people involved.  It is a topic that is often misunderstood by many.

I propose a team effort to educate with regards to block creation in Proof of Stake and Proof of Research, the history of Gridcoin staking algorithms and their flaws, and whatever other information will be necessary for this technical discussion to move forward smoothly.

**Comment by tomasbrod** [comment]
Roger that. I won't be creating this poll without approval.
