### ISSUE TITLE
code task: Fix calculation of network stake weight and tts estimations (195 GRC)

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Tasks#188]
https://github.com/gridcoin/Gridcoin-Research/issues/732

Research and implement the updated formula. Bounty will be after a pull request with the implementation and sufficient explanation is merged.

Bounty address [S16seaXG2y7uzbvVgWNMZEUSgvpqqPgS8q](https://gridcoinstats.eu/address/S16seaXG2y7uzbvVgWNMZEUSgvpqqPgS8q) (held in ~staking wallet~, deal with it).

**Comment by barton2526** [comment]
I will commit 50 GRC to a fix as described above.

**Comment by jamescowens** [comment]
If my PR1044 to satisfy this request gets accepted, I request that the bounty be donated to the faucets to encourage participation in Gridcoin.

**Comment by jamescowens** [comment]
pr1044 has been merged. This can be marked closed (complete).

**Comment by tomasbrod** [comment]
The bounty is not resolved. Although I know your wish, i will close it after I resolve the funds.

**Comment by jamescowens** [comment]
That’s fine. I just donated 200 GRC to the Switzerland faucet, so if it is easiest, you can send me the bounty.

**Comment by Foggyx420** [comment]
good work @jamescowens

**Comment by jamescowens** [comment]
Thanks! :)

On Sat, Apr 14, 2018 at 02:06 PM, Paul Jensen wrote:

good work @jamescowens <https://github.com/jamescowens>


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
<https://github.com/gridcoin-community/Gridcoin-Tasks/issues/188#issuecomment-381348477> 
, or mute the thread

**Comment by tomasbrod** [comment]
Sent to Gridcoin.EU faucet as requested. The rest is held by @barton2526.

**Comment by barton2526** [comment]
As per @jamescowens request, I donated my 50 GRC to the gridcoin.ch faucet.

TXID: 756b642ee8fd653f4c3c2aaed8451b5ebad66c963327c4cfca4632c15020d59c

I believe this issue can be closed now @tomasbrod
