### ISSUE TITLE
Gridcoin Guide Chinese Translation

### ISSUE THREAD

**Issue by jring-o** [gridcoin-community/Gridcoin-Tasks#189]
Needs Label:

Documentation | Translation | Help Wanted

Once completed should be compiled and added to the repo in a "translations" folder.

------------------------------------------------

Taken from reddit.  Original guide written in English by AtlanticTechChannel.

-----------------------------------------------

Gridcoin (加密货币) 新学的 手册
Gridcoin (cryptocurrency) beginner guide
-----------------------------------------------
前往 「www.grcpool.com」. 創建一個帳戶. (单击 「sign up」. 「email」 = 你的 email. 「researcher name」 = 你的 用戶名. 「password」 = 密碼. 「Confirm Password」 = 確認密碼)

go to "www.grcpool.com". Create an account. (Click "sign up". "email" = your email. "researcher name" = your username. "password"= password. "confirm password" = confirm password)
------------------------------------------------
下載 和 安装 下載: https://download.gridcoin.us/download/downloadstake/GridcoinResearch.msi (視窗)

download and install the wallet: https://download.gridcoin.us/download/downloadstake/GridcoinResearch.msi (Windows OS)
------------------------------------------------
下載 BOINC: https://boinc.berkeley.edu. 单击 「download」.

download BOINC: https://boinc.berkeley.edu. Click "download".
------------------------------------------------
配置 BOINC. 单击 「view」. 单击 「advanced view」. 
单击 「tools」. 单击 「use account manager」.
在 - 的右邊 「URL」 填写 「https://www.grcpool.com」. 单击 「next」. 輸入您的密碼 和 用戶名

configure BOINC. click "view". click "advanced view".
click "tools". click "use account manager."
to the right of "URL" enter "www.grcpool.com". click "next". enter your password and username.
--------------------------------------------------
前往 「www.grcpool.com」.单击 你的 用戶名. 
单击 藍色 箭头记号 在「hosts」底下.
单击 你的 電腦.
选择 項目. 单击 「add」 和 「save project settings」.

go to "www.grcpool.com". click your username.
click blue arrow under "hosts".
click on your PC
choose a project. click "add" and "save project settings"
---------------------------------------------------
在 BOINC 里面 单击 「Tools」. 单击 「Syncronize with GRCpool.com」.

within BOINC, click "Tools". click "Syncronize with "GRCpool.com".
----------------------------------------------------
打開 GridcoinResearch.exe 在你的電腦.
单击 「Receive」. 单击 你的 Gridcoin 地点. 单击 「copy」.
前往 「www.grcpool.com」.单击 你的 用戶名.
单击 「GRC address」 在「earnings」下方.
复制粘贴 你的 Gridcoin 地点. 輸入您的密碼. 单击 「Set GRC address」.
讓它同步 随着 你的 GridcoinResearch.exe 钱包.

Open GridcoinResearch.exe on your computer.
Click "receive". click your Gridcoin address. Click "copy".
Go to grcpool.com. Click your username.
Click on "GRC address" under earnings.
Copy and paste your Gridcoin address. Enter your password. Click "set GRC address".
Let it sync with your GridcoinResearch.exe wallet.

**Comment by Pythonix** [comment]
Maybe this has been finished with release v3.7.12.0. As it includes chinese translation fixes.
