### ISSUE TITLE
Automated Stake/Fee Splitting

### ISSUE THREAD

**Issue by jring-o** [gridcoin-community/Gridcoin-Tasks#191]
I will be adding to this as the idea develops.  Meanwhile, raise questions and concerns.

- Based on address/user verification.
- Might require contracts.
- A staker or cruncher can automatically split their stake reward/research reward to these accounts.
- The user can also split a fee, either for a transaction or MRC if we choose to impliment MRC or any other fee that the blockchain generates, based on the protocol parameters.
- If you understand payroll deductions for charities like United Way, you know where I'm going with this.

This might present a fair and secure way to fund BOINC projects, Gridcoin marketing campaigns, bounty based developments, faucets, general research, charities and relief efforts, personal projects, and other endeavors. Fund distribution could be manual, automatic, static, dynamic, or a combination, and could be tied into the network and its economic requirements.

**Comment by Mercosity** [comment]
We've discussed this before and I'm all for it .. would take us away from the derisive problems of foundation funding ..

**Comment by jring-o** [comment]
Moved to #202 

Closing Issue.
