### ISSUE TITLE
Control BOINC from within Gridcoin wallet GUI

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Tasks#192]
There has been mention before of integrating BOINC into the Gridcoin wallet - could this possibly be a solution to the problem? For example, a sub-version of BOINC that can only be used and has its GUI in the Gridcoin wallet, ideally developed in conjunction with BOINC so that this problem doesn't come up again?
There was a Idea, and I still support it: to replace (parts of) the boinc *manager* in the gridcoin wallet gui. The reason is: less icons in the notification area and more centralized user interface. However this plan does not want to modify, replace, or integrate the core BOINC client daemon in any way. Only the user interface.

**Comment by jring-o** [comment]
i think i heard @TheCharlatan mention that lederstrumpf is making a front end that integrates the two

**Comment by tomasbrod** [comment]
In that case, he should post about it.

**Comment by ZipovUA** [comment]
It's interesting idea to substitute boinc manager as it's not ideal - so it will be good if gridcoin community will improve boinc manager functionality faster then boinc community.

Problem that I see that gridcoing also has no time resources to work on this project :(

So to resolve this problem gridcoin should raise it's value - to gridcoin community will have enough money to be able to get full-time developers - so they will work on such improvements like integration part of boinc manager into gridcoin wallet

**Comment by grctest** [comment]
I think it's best to keep them separate, simpler that way. There can always be third party clients or simplified interfaces like that created by pools.
