### ISSUE TITLE
Slack access requires invitation

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Tasks#195]
We are telling random users to contact various users at Slack, but they are blocked by the invitation requirement. An easy means of joining Gridcoin discussion should be provided.

https://steemit.com/gridcoinstats/@rufusfirefly/gridcoinstats-thinks-i-m-using-a-proxy#@rufusfirefly/re-roboticmind-re-rufusfirefly-re-roboticmind-re-rufusfirefly-gridcoinstats-thinks-i-m-using-a-proxy-20171220t144754187z

**Comment by jring-o** [comment]
i support reopening the slack, but at the same time i do enjoy the tranquility that comes with an invite only slack.

an alternative is discord:

https://discord.me/page/gridcoin

many people have discord already, it's easily accessible, it has voip im generally idling in when working (ive had some fun voice to voice conversations with gridcoin community members), and Gunde is always there answering questions.

we could work 2 tiered.  discord is the onboard platform and slack is 2nd tier invite only.

here is the discord: https://discord.me/page/gridcoin

**Comment by tomasbrod** [comment]
Or we can have multiple invite only and public rooms on [Matrix](https://matrix.org/).
I am evaluating it currently.

**Comment by tcblack** [comment]
With the recent opening of rocketchat on chat.gridcoin.io together with a bridge to slack, it appears that we are prepared to begin phasing out Slack.  
If that is the case than I would propose we stop distributing Slack invitations and focus on rocketchat.  Once the decision to transition is complete this could be closed.

**Comment by NeuralMiner** [comment]
The Slack invite is now public and listed on all our official sites. 
Good to close this issue?

**Comment by NeuralMiner** [comment]
Closing.
