### ISSUE TITLE
Unconfirmed transaction

### ISSUE THREAD

**Issue by b-f-** [gridcoin-community/Gridcoin-Tasks#197]
Transaction not confirmed in 6 days (confirmation took seconds only). Both sending and receiving address show balance 0. Locale is Slovene.
When trying to query addresses involved, nothing shows up here:
https://www.gridcoinstats.eu/tx/f00b729b0fa07919af615979e93c2e2e3fa571148d00daf9f9578ff51699af1d

Stanje:

 0/nepotrjeno
Datum: 21. 12. 2017 21:30
Prejemnik: polo S338gCByKYGZBYcQbmBQCkTNkWktMM75aH
Dolg: -218.7620317 GRC
Provizija transakcije: -0.0001 GRC
Neto koli?ina: -218.7621317 GRC
ID transakcije: 6175172afafe95672bd3c9b1c4c24be587c2e9a0be801e402fc57542ecabd0d4

{
"bhLenght" : 19,
"bhType" : "Unknown",
"blockhash" : "0000000000000000000000000000000000000000000000000000000000000000"
}

Informacije

Dolg: -218.7621317 GRC

Transakcija:
CTransaction(hash=6175172afa, nTime=1513888191, ver=1, vin.size=1, vout.size=1, nLockTime=0)
CTxIn(COutPoint(e35a47e5bd, 0), scriptSig=304402201a0225aedcdaf1ac)
CTxOut(nValue=218.7620317, scriptPubKey=OP_DUP OP_HASH160 37bde09a40aeac4266e5f604b52c0d8918aeefe2 OP_EQUALVERIFY OP_CHECKSIG)

Notes:
 

Vnosi:
SF47oxfoLGdXPvGE2mXyQFmJoebMhcQ87U SF47oxfoLGdXPvGE2mXyQFmJoebMhcQ87U Koli?ina=218.7621317 GRC IsMine=pravilno

**Comment by Foggyx420** [comment]
this transaction occurred on a fork and thus does not exist. there is a minor ui display bug regarding these transactions which is solved and will be in future release. if your concerned about this you can always run 

checkwallet in RPC console

**Comment by b-f-** [comment]
Thank you for quick reply.
checkwallet
{
"mismatched spent coins" : 1,
"amount in question" : 218.76213170
}

**Comment by Foggyx420** [comment]
no problem u can repairwallet or walletrepair (which ever it is -- im not by a computer) and it'll correct the balance if it has no yet
