### ISSUE TITLE
Generic exception when trying to vote

### ISSUE THREAD

**Issue by b-f-** [gridcoin-community/Gridcoin-Tasks#198]
Wallet v3.6.3.0-unk. Vote for issue poll. Please note: wallet is unlocked.
Previous wallet version would not let me vote, stating that CPID must be older than poll period. Yet my CPID is older than duration of poll.
Platform: WIN10

![image](https://user-images.githubusercontent.com/2358754/34386062-19283bd2-eb27-11e7-8852-502f3abf0486.png)

**Comment by tomasbrod** [comment]
Well, too bad. I have no idea what went wrong. At least now your vote is registered.
Regarding that cpid age message, for that exact reason, a second poll, with share type of CPIDCount, was created. CPIDCount polls do not have that cpid or stake age requirement (iiac).
See also https://github.com/gridcoin/Gridcoin-Research/issues/219 .
I suggest closing this issue.
