### ISSUE TITLE
Collect CBR economy alternatives

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Tasks#199]
There were several alternatives posted, as to how high that constant block reward interest should be.
#175 
From the results, poll will be made to decide the amounts.
Note: the amount does not have to be time-constant, despite the name, it can be function of any network-global variable, eg: time, supply (-1), difficulty, netweight(-1), but _not_ miner-local variable (mag, stake, coin\*age).

**Comment by jring-o** [comment]
i'll get on this closer to the end of the roadmap polls.

**Comment by jring-o** [comment]
this can be closed @tomasbrod
