### ISSUE TITLE
100k GRC bounty -> make a secure and opensourced Gridcoin pool

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#2]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Friday Jan 20, 2017 at 15:17 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/2_

----

Gridcoin has only 1 pool, and when this would not work anymore it'd be bad for newcomers.
It works ok, but the payout is not immediate

Thus the idea is to make an opensourced one:
https://cryptocointalk.com/topic/49262-open-source-project-gridcoin-pool-boinc-account-manager/

Dis-/Advantages of a pool: https://steemit.com/gridcoin/@erkan/pool-or-solo-mining

mentioned in [hangout 1](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_07_30.MD): 
* 0:55:50-0:59:10
  * @fkinglag pay Katie a bounty ? 
  * @spassbold "definitely worth to pay quite a lot to get this opensourced"
* 0:10:00

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Jan 22, 2017 at 15:40 GMT_

----

Katiee would likely only open-source the pool if she closed down pool.gridcoin.co, in which if there was no immediate replacement we may disenfranchise the existing pool users (over 1000).

I do believe that creating an open-source pool kit is a high priority item though, multiple pools will create competition which will hopefully drive innovation.

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 15:46 GMT_

----

we have now a bounty for this task:

[Quez](https://cryptocointalk.com/user/21179-quez/): "I set up a bounty of 10,000 GRC for the individual or group who finishes the secure open source pool project."
https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1217#entry232096

I think, this is his github account: cc @Quezacoatl1

**Comment by skcin** [comment]
<a href="https://github.com/frank0051"><img src="https://avatars2.githubusercontent.com/u/3454785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [frank0051](https://github.com/frank0051)**
_Sunday Jan 22, 2017 at 17:17 GMT_

----

I don't use pools because I want the BOINC credit, but how do we get Katiee to provide her code? Or is someone else actively working on a new pool source? I'll put in 10K GRCs as well.

@Erkan-Yilmaz Can you edit the title so we know how much the bounty is up to?

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 17:19 GMT_

----

@frank0051 edited, and thank you for the bounty

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 18:00 GMT_

----

[DasTholo](https://cryptocointalk.com/user/20615-dastholo/) added also 20k GRC as bounty:

"I would increase the bounty by 20000 GRC!"

see https://cryptocointalk.com/topic/49262-open-source-project-gridcoin-pool-boinc-account-manager/page-3#entry232122

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 18:56 GMT_

----

"QZ and me started a repository with issues to start a collaborative implementation":

"OSS Gridcoin pool that pays regularly to clients in proportion to their BOINC contribution."
https://github.com/gustav1976/grcpool

https://cryptocointalk.com/topic/49262-open-source-project-gridcoin-pool-boinc-account-manager/page-3#entry232128

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 19:02 GMT_

----

Vortac added: "+20k GRC for open-sourced Gridcoin pool"
https://steemit.com/gridcoin/@erkan/get-bounties-for-helping-team-gridcoin#@vortac/re-erkan-get-bounties-for-helping-team-gridcoin-20170122t185716409z

https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1217#entry232131

**Comment by skcin** [comment]
<a href="https://github.com/frank0051"><img src="https://avatars2.githubusercontent.com/u/3454785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [frank0051](https://github.com/frank0051)**
_Sunday Jan 22, 2017 at 19:09 GMT_

----

Dude, we're changing the GRC world here - this bounty is going to be HUGE!

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 19:22 GMT_

----

lennstar added: "you can get 10K from me for the pool too"
comment [here](https://steemit.com/gridcoin/@erkan/get-bounties-for-helping-team-gridcoin)
https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1217

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 20:20 GMT_

----

> Katiee would likely only open-source the pool if she closed down pool.gridcoin.co, 
> in which if there was no immediate replacement we may disenfranchise the existing pool users (over 1000).

stats from [fediverse](https://cryptocointalk.com/topic/50958-dpp-and-dpr/):
* "Katie's pool: 1 account to which 1988 accounts contribute to, 26.8% of them active"

So, 533 active users there currently

BUT, after a certain event the 1455 inactive users would try to come back, and then BOOM, nothing there :-(

cc @grctest

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 21:33 GMT_

----

someone asked [here](https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1218#entry232145) what a pool is:

I've added my thoughts there what I'd expect from a pool, in short: 
* same features as Katie's pool
* eliminating known disadvantages of pools:
  * e.g. that pool members are also able to influence Gridcoin polls (e.g. on the pool website + the majority outcome of this is used by the pool operator to vote in the Gridcoin poll itself)

another thing to add:
* "charitable pool: I want to give x % of my earnings to a charity + select which charity XYZ to give it to" (mentioned in [hangout 5](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_09_03.MD))

Also, see #54:
approach account managers, POW pools about helping us with opensource pool

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Monday Jan 23, 2017 at 21:24 GMT_

----

[Alien](https://cryptocointalk.com/user/161-a-l-i-e-n/): "I would add 30K GRC to the bounty, what address should I send to?  Thanks"

https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1218#entry232217

**Comment by skcin** [comment]
<a href="https://github.com/Quezacoatl1"><img src="https://avatars1.githubusercontent.com/u/20362508?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Quezacoatl1](https://github.com/Quezacoatl1)**
_Tuesday Jan 24, 2017 at 17:43 GMT_

----

I have set up a bounty GRC address for those who wish that I take care of their bounty payment.
SHGHP2BVCpbwVxX9cqoc9xt8aTToPxSyes
http://gridcoinstats.eu/addresses.php?a=view&id=SHGHP2BVCpbwVxX9cqoc9xt8aTToPxSyes
The address curently contains 30k GRC from Alien and 10k from myself.

**Comment by skcin** [comment]
<a href="https://github.com/sergiofbsilva"><img src="https://avatars1.githubusercontent.com/u/1778577?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sergiofbsilva](https://github.com/sergiofbsilva)**
_Friday Feb 10, 2017 at 20:18 GMT_

----

das Leben ist nicht leicht :-)

**Comment by skcin** [comment]
<a href="https://github.com/Quezacoatl1"><img src="https://avatars1.githubusercontent.com/u/20362508?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Quezacoatl1](https://github.com/Quezacoatl1)**
_Friday Feb 10, 2017 at 20:26 GMT_

----

BTW, development efforts can be seen at grcpool.com
http://gridcoinstats.eu/addresses.php?a=view&id=SHGHP2BVCpbwVxX9cqoc9xt8aTToPxSyes now counts 60k GRC

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Saturday Feb 11, 2017 at 18:27 GMT_

----

I talked in [hangout 23](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_02_04.MD) about my ideas of what should go into the pool kit

**Comment by skcin** [comment]
<a href="https://github.com/Quezacoatl1"><img src="https://avatars1.githubusercontent.com/u/20362508?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Quezacoatl1](https://github.com/Quezacoatl1)**
_Saturday Feb 11, 2017 at 18:52 GMT_

----

@Erkan-Yilmaz can you maybe summarize your ideas here, maybe you even have more? I'd like to give the list to BGB who is currently working on grcpool.com :)
You can also go to the pool website, maybe you have constructive critizism?

**Comment by skcin** [comment]
<a href="https://github.com/bryhardt"><img src="https://avatars2.githubusercontent.com/u/6340624?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bryhardt](https://github.com/bryhardt)**
_Saturday Mar 04, 2017 at 18:57 GMT_

----

just saw this thread,  @Erkan-Yilmaz I would like to hear anything you want about the pool. The bulk of things are working ok so far. so i am tidying things up for open sourcing and creating apis. So it would be a great time to entertain more ideas.

**Comment by skcin** [comment]
<a href="https://github.com/LokiToki"><img src="https://avatars0.githubusercontent.com/u/25841155?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LokiToki](https://github.com/LokiToki)**
_Monday Mar 06, 2017 at 10:14 GMT_

----

@bryhardt i just read this and considering to build the pool. When your project is almost finish i cancel my research. If you need help feel free to initiate me. :)

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Monday Mar 06, 2017 at 16:44 GMT_

----

@bryhardt From the recent discussions in the hangouts, the following issues would be very cool:
* ***Voting within the pool*** --> forwarding user's voting intention towards the GRC client (though, you cannot 100% accurately divide your weight between options, so it'd have to be a first past the post voting system within the pool, unless the voting mechanism within the client was improved).
* ***A GRC:Computation market!*** --> Users select a 'pool handles project selection' option, these hosts become floating computing resources which can be 'rented' out & pointed towards a specific whitelisted project. This would enable a GRC:Computation economy which would be good for liquidity, would enable us to compete directly against Golem/SONM/Iex.ec and could would be an extra source of revenue for both the users crunching within the pool & the pool operator (who would take a sale fee). [This idea was generated on reddit - WallOfText!](https://www.reddit.com/r/gridcoin/comments/5wb4bl/suggestion_make_another_type_of_list_greenlist/).
* ***BotNet detection*** --> We've recently found evidence of BOINC botnets utilizing boincstats. When the open-source pool kit is released, the pool will obfuscate the attached hosts of users - the ability to flag an user for many IP addresses and/or many hostname variations would help remove botnets from the picture (obviously they could create their own hidden pool service, but keeping them off the legit pools would keep pool admins out of trouble).
* ***Rain forwarding*** --> If the pool staking address receives a transaction that is not a POS|DPOR transaction, then it's potentially a sendmany 'project rain' transaction. Forwarding these GRC to users, taking their % of pool mag into account would be great.

Cheers 👍

**Comment by skcin** [comment]
<a href="https://github.com/bryhardt"><img src="https://avatars2.githubusercontent.com/u/6340624?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bryhardt](https://github.com/bryhardt)**
_Monday Mar 06, 2017 at 19:47 GMT_

----

- **Voting** --> I am not up to speed on how the voting system internals work. Would this require the pool to capture the votes of researchers then casting a single vote from the pool's client based on what the pool voting mechanics captured? The client can only send 1 vote correct?

- **Computation Market** --> definitly interesting... this seems like something that is doable at the surface

- **BotNet** --> yup, i need to add some more reporting and could look for these

- **Rain** --> I think this currently works partially... if the pool wallet receives any extra funds, it will disperse them automatically. A perfect scenario would be to know what project the rain should go to and pay those specific researchers instead of everybody.

**Comment by skcin** [comment]
<a href="https://github.com/Vortac2"><img src="https://avatars0.githubusercontent.com/u/24814168?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Vortac2](https://github.com/Vortac2)**
_Monday Mar 06, 2017 at 21:33 GMT_

----

The new pool looks completely finished to me, great work. Sent 20k GRC to the bounty address.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Monday Mar 06, 2017 at 22:00 GMT_

----

> **Voting** --> Would this require the pool to capture the votes of researchers then casting a single vote from the pool's client based on what the pool voting mechanics captured? The client can only send 1 vote correct?
> 

Indeed, gridcoinstats automatically picks up new polls, if you were to create a simple php poll for active gridcoin polls then you could decide how to vote with the pool's magnitude.

You cannot divide up your vote weight more than equally between multiple poll options unfortunately. We could create a gridcoin issue regarding that.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Monday Mar 06, 2017 at 22:06 GMT_

----

Additional idea: 
* 2 Factor Authentication?

**Comment by skcin** [comment]
<a href="https://github.com/frank0051"><img src="https://avatars2.githubusercontent.com/u/3454785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [frank0051](https://github.com/frank0051)**
_Tuesday Mar 07, 2017 at 05:42 GMT_

----

I a little confused, where do we see the pool that's being developed?

**Comment by skcin** [comment]
<a href="https://github.com/Vortac2"><img src="https://avatars0.githubusercontent.com/u/24814168?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Vortac2](https://github.com/Vortac2)**
_Tuesday Mar 07, 2017 at 07:43 GMT_

----

www.grcpool.com

**Comment by skcin** [comment]
<a href="https://github.com/LokiToki"><img src="https://avatars0.githubusercontent.com/u/25841155?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LokiToki](https://github.com/LokiToki)**
_Tuesday Mar 07, 2017 at 08:17 GMT_

----

@bryhardt i watched your videos and this looks awesome! Great work! Normally i don't like php but if it's done good it will do the trick. ;)

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Tuesday Mar 07, 2017 at 08:43 GMT_

----

> I'm a little confused, where do we see the pool that's being developed? 

It's in closed source development at the moment.

**Comment by skcin** [comment]
<a href="https://github.com/bryhardt"><img src="https://avatars2.githubusercontent.com/u/6340624?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bryhardt](https://github.com/bryhardt)**
_Tuesday Mar 07, 2017 at 17:06 GMT_

----

It is forked on my github, https://github.com/bryhardt/grcpool
It is not all there as I am pushing things as I double check what I am putting on there...

**Comment by skcin** [comment]
<a href="https://github.com/grcjamezz"><img src="https://avatars0.githubusercontent.com/u/20879295?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grcjamezz](https://github.com/grcjamezz)**
_Tuesday Mar 07, 2017 at 18:24 GMT_

----

Great work @bryhardt , I signed up yesterday upon seeing it in the stats and checked it out...Great simple interface and loaded with lots of info , project , user and payout thats great!  Is there something with your pool and Amicable Numbers the rest of us don't know currently? The largest percent of work in the pool is on that project at almost 25%. Also great videos , very descriptive and in depth.. Curious if you are familiar with the Android Boinc client " Native Boinc " ? I was watching your video on how to attach Android Boinc clients to an account manager/pool etc and you do not need to edit an .apk file with that version you just goto " Manage Client " and " Synchronize with Bam " and it's actually generic and you just give your own url / user name / password and walla! This is extremely less work and extremely easier that the method shown on your video. Literally , install and attach.  Thought I'd pass that along as it might make things easier to expand the android Boinc user base both within your pool and beyond. Anyway thank you for open sourcing your creation! Go Team Gridcoin!

**Comment by jring-o** [comment]
I'm not sure where this bounty stands, but I'm wondering if the development of https://grc.arikado.ru/
meets the requirements. 

If it does, I would propose that the bounty be split in some way between @bryhardt and sau412.

Again, not sure where this stands or what the requirements are, just following up and keeping the conversation alive.

Thoughts?

**Comment by Vortac2** [comment]
Has this bounty ever been paid out?

**Comment by jring-o** [comment]
What happened with this bounty or development? Was it fulfilled? If it was, was it paid out? If not, is it still live?

If there is no response to this comment within a week, this issue will be closed.

**Comment by Vortac2** [comment]
To my knowledge, this bounty has never been paid out and the bounty address still holds 81k GRC. We shouldn't close this issue before those funds are taken care of. IMO, we should pay the pool devs and be done with it.

Bounty address:
https://gridcoinstats.eu/address/SHGHP2BVCpbwVxX9cqoc9xt8aTToPxSyes

**Comment by jring-o** [comment]
Who holds the funds?

**Comment by jefftrex** [comment]
Why was this never paid out? The address still shows as holding 81.000 coins..

**Comment by jamescowens** [comment]
That address belongs to Quez I think. @jring-o?

**Comment by jefftrex** [comment]
Not to be a bother, but gonna go ahead and bump this for resolution. The bounty is more than completed at this stage so just needs to be paid out. Is this wallet no longer accessible? @Quezacoatl1 ?

**Comment by Quezacoatl1** [comment]
OMG i nearly forgot about that. I believe @bryhardt and I talked about it a good while (2 or 3 years ago?)

I'll have a look whether I can access those funds as they obviously are not part of my main wallet.

Fingers crossed. 

Of course I will pay my "debts" in any case, so no worries.

**Comment by Quezacoatl1** [comment]
Do we have a consensus on who will get how many GRC?

**Comment by Quezacoatl1** [comment]
Found them :)

**Comment by jamescowens** [comment]
Did this get paid?

**Comment by barton2526** [comment]
bump

**Comment by jamescowens** [comment]
Let's split this 50/50 between the two pool operators and be done with it.

**Comment by bryhardt** [comment]
i am fine with that. i would like the share divided into the 3 pools equally,   so it will go out to the pool crunchers.

SCuWqRwmEi6HCuPv78tPJyi6gjsARDVA4u
SA3TAMA8DWVCuRDaxfUFqpe53yqxija9Hw
S9BEUqGeZ74R3K24VTL9T8wnrRcgqNxsMe

**Comment by sau412** [comment]
I'm fine with that too. My address is S23BULLyXUkpqZWnbx7epCaxxMSUhDcXnS

**Comment by Quezacoatl1** [comment]
50% of the balance went to S23BULLyXUkpqZWnbx7epCaxxMSUhDcXnS -> TXID [db1bf5dca8da90b200a790831ba12222e2ec5ff10522a577677032a2772d1718](http://main.gridcoinstats.eu/tx/db1bf5dca8da90b200a790831ba12222e2ec5ff10522a577677032a2772d1718)

50% * 1/3 of the balance went to SCuWqRwmEi6HCuPv78tPJyi6gjsARDVA4u -> TXID [09ccda8093b20e4add8d83d5ff9281aa0a90ab6ea5d3801e6a9a00baf8ffca97](http://main.gridcoinstats.eu/tx/09ccda8093b20e4add8d83d5ff9281aa0a90ab6ea5d3801e6a9a00baf8ffca97)

50% * 1/3 of the balance went to SA3TAMA8DWVCuRDaxfUFqpe53yqxija9Hw -> TXID [311c37a0ecbee03d114a6792a99cc4f88daecbe0b0cb1da3584780cfd6f34610](http://main.gridcoinstats.eu/tx/311c37a0ecbee03d114a6792a99cc4f88daecbe0b0cb1da3584780cfd6f34610)

50% * 1/3 of the balance went to S9BEUqGeZ74R3K24VTL9T8wnrRcgqNxsMe -> TXID [ba6235ad1381d2664f8414c43aacd92f17eefa748af08fa8e2011db5d4e62e0c](http://main.gridcoinstats.eu/tx/ba6235ad1381d2664f8414c43aacd92f17eefa748af08fa8e2011db5d4e62e0c)

We can close this one :)

**Comment by dblanch256** [comment]
Many thanks for that!

I was wondering where the extra 300 came from!

Dedicated gridcoin fan and top pool donator (dblanch256).

David C Blanchard
MIT '76

*"If I have seen a little farther than others, it is because I have stood
on the shoulders of giants"*   -- Isaac Newton


*"If I have not seen as far as others, it is because giants were standing
on my shoulders."*  -- Hal Abelson


*"In the field of Computer Science, we stand on each others' feet."*  --
Richard Hamming
