### ISSUE TITLE
Gridcoin-Tasks Cleanup

### ISSUE THREAD

**Issue by G-UK** [gridcoin-community/Gridcoin-Tasks#206]
This repository has a lot of tasks which are outdated, inactive, or just are not tasks. I propose a clean-up closing many of the older tasks or consolidating into single new tasks.

The main benefits are that users will find it easier to make a meaningful contribution and find things that actually need doing. Also it should increase focus on the things that are higher priority.

I have done a quick pass through all the open tasks and I believe that the following are what should be currently open based on activity and ongoing discussions in the community.

### Code:
Linux Neural Network (#15)
Set-up Wizard (#20)
In-Wallet Alerts / Communication (#167)(#177)
Remove Team Requirement (#98)
OpenSource Gridcoin Pool (#2)
OpenSource BlockChain Explorer (#76)
Control BOINC from Gridcoin wallet GUI (#192)
.Conf Files (#204)
Gridcoin Bridges (#203)

### Marketing:
Coinpayments (#30)(#65)
Chinese Translation (#189)
Whitepaper (#3)

### Participation:
Attracting new Developers (#9)(#128)
Slack Invitations (#195)
Mumble Alternatives (#12)

### Process:
Define a set of task Labels and their purpose (#184)
Project Listing (#6)(#19)(#194)
Project De-Listing (#201)
Gridcoin 2018 Budget (#205)
Gridcoin Treasury (#202)

Some others will need updating/recreating based on Roadmap vote outcomes:
#135, #171, #172, #173, #174, #175, #183, #199

Unknown but recent and have bounties:
#176, #188 

I recommend everything else is Closed. Closed Tasks can of course still be referenced and re-opened if required.

**Comment by jring-o** [comment]
Keep #202 open please.

**Comment by G-UK** [comment]
Oops, thought I'd listed that as a good one.

**Comment by tomasbrod** [comment]
Write to @grctest for permission to maintain task tags.

**Comment by tomasbrod** [comment]
Does G_UK have the edit rights yet?

**Comment by jring-o** [comment]
You'll be happy to know, @G-UK, that this is getting done and this task is being closed due to completion
