### ISSUE TITLE
Commercial projects: Cyclone feature 

### ISSUE THREAD

**Issue by ragnaroklow** [gridcoin-community/Gridcoin-Tasks#208]
Right now there arent really any commercial projects AFAIK because gridcoin is using exclusively boinc but in the future there may be for profit projects in which case I think there should be a fee paid to the network for it's computing power as a whole. I'm not against commercial projects unlike many because they are still fulfilling one of the core principles of Gridcoin, they're not wasting energy on useless hashing.

 Right now it's possible to rain projects individually but such a venture should be required to rain for gridcoin as a whole and not just one project to ensure that crunchers do it by choice and not  because it's x times more profitable when you add the rained value to the equation.

Right now it's possible to rain manually one project or do a script to do it but it would be interesting to implement a method by which it would be possible to rain large amounts of Gridcoin (let's say 1k+) split evenly between all projects. Which is why I called it Cyclone, Tsunami could be interesting as well but it's not the same thing. :p

I'm not a dev by any means but having Rain already, it seems to me that it wouldnt be the hardest thing to implement and it could help grow Gridcoin significantly in the future. 

Having a feature like this would allow to implement requirements for these commercial projects.
Example: 1000 GRC rained per X TFLOPS of compute done.

Edit: I apologize if I didnt do this right, It's my first time here :o

**Comment by tomasbrod** [comment]
You did right.
Problem to a network-wide rain is that Gridcoin does not know how much user contributed to a project. We only know how much you contributed to a project compared to everyone else on that project. We do not even know how much user contributes to project x versus project y.
Mechanism for getting money from for profit projects back into the network is different and difficult topic.

**Comment by ZipovUA** [comment]
@tomasbrod  what improvement should be made to get know how much calculation was made for specific project / sub-project?

In why pool does not have this information if in every project's page we can see information about tasks, their results and how much time and what machine resources user spent to perform that tasks?
