### ISSUE TITLE
Whitelist & Greylist Listings

### ISSUE THREAD

**Issue by G-UK** [gridcoin-community/Gridcoin-Tasks#209]
04/04/2018 -

Project Listings are now being updated on my Temporary Website
[https://gridcoin.ddns.net](https://gridcoin.ddns.net)

**Comment by G-UK** [comment]
Link to Accepted Process:
https://github.com/gridcoin-community/Gridcoin-Tasks/issues/194

Link to Demonstration Spreadsheet (as used for above chart) 17th Feb 2018 Snapshot:
https://teamgridcoin.slack.com/files/U7DMXPRPB/F9AU8PNUD/whitelist_17-02-18.ods

Link to Demonstration Spreadsheet explanation:
https://teamgridcoin.slack.com/files/U7DMXPRPB/F9BJ4T1CM/Listing__Proposal_V1_Spreadsheet_Description

**Comment by Quezacoatl1** [comment]
DrugDiscovery@Home and Universe@Home will be temporarily removed asap

**Comment by tomasbrod** [comment]
https://climateathome.info/climateathome/ <- project to track

**Comment by tomasbrod** [comment]
Goofyx is not new project. I remember it since 2015

**Comment by G-UK** [comment]
I should have probably put something along the lines of re-launched. It's more that there is no longer term trend of work availability on this latest project server set-up.

I believe the original was merged into "Grid Computing Center" which then later broke up. The NCI work was then re-launched as a seperate project and now finally(?) the CPU tasks have been re-launched as a seperate project.

**Comment by Quezacoatl1** [comment]
POGS has been removed from the whitelist, probably forever but for now according to the greylist. Thanks @G-UK mentioning it
