### ISSUE TITLE
Collect related articles and resources

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Tasks#210]
There have been a lot of research performed, and documented in a form of articles on Steemit platform. Sadly these articles will fall out of the Trending section of our tag. We must not let the work to be forgotten. Please collect such articles and resorces, for example here.

**Comment by jring-o** [comment]
we try to collect them all in the state of the network reports.  sometimes there are a few that sneak by -- are you looking for anything in particular?

**Comment by tomasbrod** [comment]
Nothing in particular. SoTNs are posted only by you?

**Comment by jring-o** [comment]
I post them but they are compiled by parejan and myself

**Comment by tomasbrod** [comment]
yeah that's an example. Let's compile links to all SoTNs.
