### ISSUE TITLE
Eliminate Team Requirement by Tying participation the Beacon along with DWP.

### ISSUE THREAD

**Issue by tcblack** [gridcoin-community/Gridcoin-Tasks#215]
Would it work to leave the team requirement behind by tying participation to the Beacon?  

1. Open the wallet 
2. Find Button (See issue #214) that says "Join Gridcoin Network" and click it. Your CPID joins the blockchain (beacon)
3. Based on an implementation of DWP, Clients attempting to build a superblock retrieve all the beacons from the blockchain, and build from that list instead of the team gridcoin requirement.

In connection with this see: _Request: Beacon Status Button in the Wallet #214_   ⛓ 

The button is in place because right now sending a beacon is cryptic.  Why not color code it clearly: Green - Beacon is on the network. Yellow - Beacon is 5 months old and needs renewal. Red - you have no beacon matching your current CPID on the network.
Bonus: hover over the JOIN button and see your receiving address attached to your beacon.
based on https://www.reddit.com/r/gridcoin/comments/83erhx/solo_mining_without_being_part_of_the_gridcoin/

**Comment by tomasbrod** [comment]
#170 account association proposal and CM's version, which I do not have a link to.
