### ISSUE TITLE
Gridcoin 2019 Budget

### ISSUE THREAD

**Issue by jring-o** [gridcoin-community/Gridcoin-Tasks#225]
# Gridcoin 2019 Budget

### How long will this budget cover?

January 1st - December 31st 2019

### How much money do we have?
Without a treasury system, we have to operate under the assumption that we will be using existing Foundation funds for the 2019 budget.

The foundation has about 32 million GRC.

Using the current price of .01 USD, that gives us 320,000 USD.

Source: 

https://coinmarketcap.com/currencies/gridcoin/historical-data/?start=20171011&end=20181011

### How much money have we spent so far?
773.09 hours from July 2017 through Sept 2018 (14 months)

Since some of these hours are $30 and some are $60, I am not going to estimate GRC or $ spent for this time.

Source: 

https://cryptocurrencytalk.com/topic/85404-developer-compensation/?page=7

### Development Estimate for 2019
55 hours/month at $60/hr = $3,300/mo

We can estimate $40,000 to budget for development in 2019.

Using the current price of .01 USD, that gives us 4,000,000GRC budgeted for development in 2019. This number will inform funding as we define development as 50% of the entire budget.

### Introduction

Gridcoin has grown to the point where organization has become necessary. A budget will help by structuring financial and human resources to optimize production. With a clear and public budget, those already in the community will know where production focuses lie, and those outside the community will know what resources we have to offer for their contributions. 

This budget defines leadership roles and guaranteed funds for four departments.

Budget for January 1st 2019 - December 31st 2019

#### _Total Funding:_ 

8 Million GRC

This equals 25% of total foundation funds.

#### _Priorities:_
Development Purse
Marketing
Outreach

#### _Allocation:_ 

Development Purse - 65%
Marketing - 25%
Outreach - 10%

#### _Department Funding:_

Development Purse - 5,200,000 GRC
Marketing - 2,000,000 GRC
Outreach - 800,000 GRC

#### _USD Equivalents at .01 USD per GRC:_

Development Purse - 52,000 USD
Marketing - 20,000 USD
Outreach - 8,000 USD

### Departments

Each department would have a multi-sig wallet or address separate from the foundation. This wallet would hold the allocated funds which would be released when a proposal is accepted, or when a minor endeavor is approved. 

The list of priorities for each department would be defined and published by the core team of each department as defined by the larger community. Action on any major decisions or proposals would require a network wide vote while the core team of each department would be responsible for any minor endeavors.

We propose this major minor structure to help facilitate rapid response for non-resource heavy and time sensitive initiatives. Network polls require 6 weeks to be accepted which can sometimes hinder or completely block our ability to take advantage of time sensitive opportunities. Furthermore, it can be a daunting task to develop a full proposal for a network poll when requesting a few hundred USD for a project or endeavor.

#### _Development Purse_

The development purse is a fund reserved for developer use on top of core development pay.

Core developers continue to be reimbursed at an hourly rate directly from the foundation based on hours they submit. The development purse is there to give them the freedom to create development bounties without the need to run month long polls, should the need arise. As stated above, any major bounty would still require a network poll.

- **Implementation Bounties:** For example, if we have assets that need to be implemented into the GUI the team in charge of the development purse could create a bounty to implement these assets.

- **Bug Bounties:** For example, if a bug is found and responsibly disclosed to the core team, a reward can be claimed. If the bug is patched, a greater reward can be claimed. Reward totals would be at the discretion of the core team 

- **Translation Bounties:** For example, a bounty to translate the wallet into a specific language.

#### _Marketing_

The marketing department is responsible for managing funds reserved for marketing initiatives. Major requests from the marketing budget would require a network poll, though the core marketing team would be able to create bounties for minor tasks such as building a style guide (https://github.com/gridcoin-community/Gridcoin-Tasks/issues/224) and other assets.

- **Marketing Campaigns:** Major initiatives that require design and implementation teams.

- **Advertisements:** One time or repeating ads that require design and, if repeating, maintenance.

- **Announcement and news articles:** Brief write-ups on major announcements and news items. These would be posted on subreddits, medium, and anywhere else that the core team deems appropriate. 

- **Assets:** Banners, logos, designs.

#### _Outreach_

The Outreach department is responsible for managing funds reserved for education and direct contact with other entities and institutions. Major initiatives and expenses would require network votes while minor initiatives such as funding minor meetups would be approved or rejected by the outreach team.

- **Educate:** Educate institutions and individuals regarding the blockchain, cryptocurrency, BOINC, and Gridcoin in particular.

- **Create:** Help institutions create BOINC projects for data they would like to have crunched.

- **Introduce:** Form the beginnings of relationships and partnerships by attending conferences, workshops, and meetups. 

### Evaluation Period

To ensure the the requirements of the network are met throughout the year, we propose breaking the budget into two six month periods. The first period will be initiated by the acceptance of this budget. If a department wishes to propose changes to their allocated budget for the second period, they will create a poll six weeks before the end of the first period. If their changes are accepted, the appropriate modifications will be made for the second period of this budget.

### Choosing Teams
This needs to be discussed at length. Some ideas to start the conversation:

- Each team could require at least 1 OP
- Teams could be chosen by OPs
- Teams could be voted in

**Comment by barton2526** [comment]
Suggestion: Adjust percentages of funding allocations.  Instead of:

Development Purse - 65%
Marketing - 25%
Outreach - 10%

I think it would make more sense to drop development to 50%, seeing as dev funding is separate from this proposal (excluding the mentioned bounties, etc).  I am curious as to hear the thoughts on an allocation like this:

Development Purse - 50%
Marketing - 40%
Outreach - 10%

**Comment by jring-o** [comment]
makes sense to me. will change it after some time for more feedback
