### ISSUE TITLE
Update CCT subforum description

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Tasks#226]
It currently says this:
> A Proof-of-Research cryptocoin that compensates users for BOINC contributions in science, math, and technology for the benefit of humanity with a variable block reward based on the share of network contribution, with 87 second blocks. Current Money Supply: 367 million. Inflation Rate: Investor Interest: 1.5% (APY/Supply). Proof Of Research: 5% (APY/Supply). Max Block Subsidy: 50. Blocks per day: 1000. 

which is outdated.

**Comment by ShmoogleOsukami** [comment]
This has been sorted. I managed to get CCT to update the information some months back.
