### ISSUE TITLE
[Whitelist] Remove project Drug Discovery from the Whitelist?

### ISSUE THREAD

**Issue by G-UK** [gridcoin-community/Gridcoin-Tasks#228]
This is the main discussion thread as per #227 for removal of Drug Discovery from the Whitelist

I will look to get a vote up to remove this project from the Whitelist once the Poll definitions vote finishes.

The project has been dead since Feb 18 with no updates since and the website is also dead.

This should tidy things up our end. We can always re-visit it if the project ever restarts.

**Comment by tomasbrod** [comment]
What is the relation to #227 ?

**Comment by G-UK** [comment]
#227 Says

> Main Poll Discussion Thread on Github or Reddit

As that vote will pass I am ensuring that we have a discussion thread that meets the requirement, I've only referenced it as these will be the first polls under the new Poll Definitions.

**Comment by dblanch256** [comment]
Well, Drug Discovery was nice while it lasted.

But clearly it's not reliable, so it appears to have earned its removal status from Gridcoin!
