### ISSUE TITLE
 [Whitelist] Remove project Citizen Science Grid from the Whitelist?

### ISSUE THREAD

**Issue by G-UK** [gridcoin-community/Gridcoin-Tasks#229]
This is the main discussion thread as per #227  for removal of Citizen Science Grid from the Whitelist

I will look to get a vote up to remove this project from the Whitelist once the Poll definitions vote finishes.

The reason for removing this project from the whitelist is that for the last few months it has only been producing a trickle of work causing similar issues that were experienced previously with the Sourcefinder Project.

In essence, there is so little work available that only very few users can actually get workunits. This in turn means that if you are lucky enough to grab a work unit you get a disproportionately large reward for actually doing very little.

**Comment by G-UK** [comment]
Cross post of a Q&A from Slack/Rocket to save duplication.

> jringo 10:44 PM
> why hasn't CSG's WAS greylisted it?
> 
> G_UK 11:06 PM
> Because the amount of work is stable, just too low to support more than 1 or 2 people. There is currently no way of reliably telling how much work a project has we can only spot significant changes, it's the same issue we had with Sourcefinder last year.
> 
> There has been quite a bit of discussion recently in #development between @jamesowens @ilikechocolate001 and @cy about how we deal with this without manual intervention so it can be dealt with by the blockchain / scraper automatically.

**Comment by tomasbrod** [comment]
I suggest manually grey-listing the project instead of fully removing it from the whitelist. This way it can be re-added when the situation clears without a poll.

**Comment by G-UK** [comment]
Only issue with manually greylisting is that we have no procedure to decide when it should be re-whitelisted (or one that lets us manually greylist).

I'd love to just do it that way as it is probably the most reasonable way to deal with CSG. However I'm conscious of us just doing it causing problems in the community and potentially being misconstrued.

**Comment by mistermarmot** [comment]
There is no Compute Availability = (Compute Speed/Active Users) + (WU Queue/100) in the Proposals for Whitelisting. 
[#194](https://github.com/gridcoin-community/Gridcoin-Tasks/issues/194)
[#227](https://github.com/gridcoin-community/Gridcoin-Tasks/issues/227)

Yet that column is on the [webpage created by G-UK](https://gridcoin.ddns.net/pages/project-list.php) and appears to be the only criteria for giving Citizen Science Grid the flag "Unsuitable for Rewards" on that webpage, as CSG is not violating any of the current agreed upon criteria.  (WAS = 0.59, ZCD=1)
That webpage is being linked as an official source in the help chat for us to look at the whitelist so it's not appropriate for the project to be shown as Unsuitable on criteria the community hasn't agreed to.

If Compute Availability is to be used as a criteria for Whitelisting then it needs to be discussed and a community proposal started.

If you don't flood your cache and properly set up your project priorities, it is easy to get a couple of CSG WU's every week.  Even so, it is light on work and I don't have an objection to a whitelist vote.

I DO object to that web page stating the project is "Unsuitable for Rewards" on unaccepted standards during the voting period and having Gridcoin team members being told to review that page.

**Comment by G-UK** [comment]
You are correct, "Project Suitability" is not an official stat and it is not used to Whitelist or Greylist projects (Which is why CSG is still Whitelisted and other projects are not). You have a point though, and the column did used to say experimental or unofficial or something which seems to have disappeared at some point. I'll re-add the Unofficial title to the column just so it is clear.

The idea of the column is that It uses some ideas that are being thrown around on Slack on how to improve how we manage project listings and therefore tries to give a better picture on what projects are suitable.

I think it is pretty obvious that the current process does need improving as what I put together was just a first step in getting the project lists in some form of order. As we see with Sourcefinder and now CSG, it is far from perfect.

One final point, I never meant my site to be "official". I put it together as a personal learning exercise expecting it to be temporary.
