### ISSUE TITLE
Updated White Paper Proposal

### ISSUE THREAD

**Issue by jring-o** [gridcoin-community/Gridcoin-Tasks#230]
<h1>Updated White Paper Proposal</h1>

<h6>Poll Type: Outreach</h6></center>

<h2>Useful Links</h2>

[Proposed White Paper](https://gridcoin.world/Gridcoin%20Whitepaper%20Draft.pdf)
[Current White Paper](https://gridcoin.us/assets/img/whitepaper.pdf)
[Poll Definitions, Requirements, and Validation Parameters](https://github.com/gridcoin-community/Gridcoin-Tasks/issues/227)
[Current White Paper Proposal (From March 2018)](https://www.reddit.com/r/gridcoin/comments/83ammm/the_gridcoin_white_paper_proposal/)

<h2>Overview</h2>

[Reddit Discussion Thread](https://www.reddit.com/r/gridcoin/comments/cewdjz/poll_updated_white_paper_proposal/)
[Steemit Discussion Thread](https://steemit.com/gridcoin/@jringo/poll-updated-white-paper-proposal)

Gridcoin approved its first white paper on April 20th, 2018. The proposal for that paper stated that, 

>As Gridcoin continues to grow and further define its utility, structures, infrastructures, and use-cases, major additions and revisions may be required. Any major change to the vision, philosophy, and intent expressed in the white paper will require a follow-up blockchain-based poll for implementation.

We think that it has become necessary to use this clause. 

The combined development and growth of the Gridcoin protocol, infrastructure, and community has culminated in a new, more detailed white paper written from the ground up.

We view this paper as more coherent, more encompassing, and more accessible.

We propose declaring this new paper the official Gridcoin white paper.

<h2>Format</h2>

The proposed white paper breaks Gridcoin into four distinct sections:

1. The Gridcoin Network
1. The Gridcoin Blockchain and Protocol
1. Gridcoin Incentives
1. Gridcoin Values

We believe the proposed paper more clearly and completely details these aspects of Gridcoin when compared to the current paper.

Additionally, the proposed paper describes the new Oracle mechanism used to collect cruncher statistics.

<h2>Audience</h2>

The proposed white paper assumes an audience with limited blockchain knowledge, but with the propensity to explore beyond the content of the paper itself. 

It introduces blockchain and cryptoeconomic principles along with Gridcoin specific technology and operational structures.

We believe that this tone efficiently introduces the reader to the potential of blockchain technology and Gridcoin as well as Gridcoin’s current system, operation, and protocol. 

We also believe that this tone encourages the reader to seek out more information by joining the community, doing their own additional research, or otherwise engaging in the Gridcoin ecosystem.

<h2>Moving Forward</h2>

This poll seeks network approval of the content of the proposed paper as presented.

If accepted, the proposed paper will become the content for the new Gridcoin white paper.

If accepted, formatting and design work will begin to arrange the content into a polished paper. The polishing process is expected to take up to four weeks from the end of this poll.

This work might include:

- The addition of footnotes
- The addition of a terminology page
- The addition of a cover page
- The addition of side-bars
- Beautification of the paper 

If accepted, any future major change to the vision, philosophy, and intent expressed in the white paper, or the addition or removal of any section will require a blockchain-based poll for implementation.

If accepted, minor edits to wording, formatting, and definitions will be made at the discretion of the contributors listed in the contributors section of this proposal.

If rejected, the current white paper will continue to serve as the Gridcoin white paper. The current white paper is linked in the useful links section of this proposal.

If rejected, feedback from this proposal’s discussions may be taken into account and changes may be made in order to propose this paper again. There is no timeline for these changes and presenting a second paper to the community.

<h2>Contributors</h2>

This paper is the result of the work of: 

- jringo 
- Whoisterrencelee
- Nateonthenet

Additional contributions were made by:

- Roboticmind
- James C. Owens
- Several people in the #marketing channel on Gridcoin’s slack
- Discussions from participants of The Gridcoin Fireside

<h2>Funding</h2>

This has been an entirely volunteer-based initiative taken on by long standing contributors. There is no official request for funding or reimbursement for this work, however anyone can make a poll to release funding from the foundation to the organizers and builders of this paper.

Otherwise, anyone is invited to donate or side-stake to the GRC address:

_SHtGjsa41Kjws463xgZSms8vETqkDYH3io_

From there, any donations will be distributed among the contributors.

<h2>Proposal</h2>

We propose the presented content become the basis of a new Gridcoin white paper.

[Proposed White Paper](https://gridcoin.world/Gridcoin%20Whitepaper%20Draft.pdf)

<h2>Poll</h2>

This poll seeks network approval of the proposed content as the content for the new Gridcoin white paper.

This poll is classified as an outreach poll and is subject to all requirements and validation parameters defined in the _Poll Definitions, Requirements, and Validation Parameters_ document, linked below.

https://github.com/gridcoin-community/Gridcoin-Tasks/issues/227

**Poll Question**
_Do you support the proposed content as the new Gridcoin white paper?_

**Poll Options**
_Yes
No
Abstain_

**Poll Duration**
_4 weeks_

**Poll Validation Requirements**
_40% AVW_

**Begin Date** July 18th, 2019
**End Date** August 15th, 2019

**Comment by nottoseethesun** [comment]
The "Economics" section of the whitepaper needs a sentence or two more in terms of explanatory text about CBR and ERR if the chart is to include those figures.  Another option may be to remove them if that would make sense, because simpler is better.

Also, the "Economics" section of the whitepaper needs to at least briefly explain the underlying dynamic of the GRC inflation rate.  For example, the inflation rate is shown to be decreasing in the included chart, but no sense of why that is so is given in the explanatory text.

**Comment by jring-o** [comment]
> The "Economics" section of the whitepaper needs a sentence or two more in terms of explanatory text about CBR and ERR if the chart is to include those figures. Another option may be to remove them if that would make sense, because simpler is better.
> 
> Also, the "Economics" section of the whitepaper needs to at least briefly explain the underlying dynamic of the GRC inflation rate. For example, the inflation rate is shown to be decreasing in the included chart, but no sense of why that is so is given in the explanatory text.

Good catch. I will probably edit the chart to remove the terms. This was copy/pasted from the CBR proposal, where those terms were explained with the chart, and no one noticed.

I will also try to explain why the rate decreases.

**Comment by jring-o** [comment]
Update 1:

https://www.reddit.com/r/gridcoin/comments/ckhhlm/update_1_updated_white_paper_proposal/

**Comment by jring-o** [comment]
This proposal was approved and the final product is under development. This issue has been closed.
