### ISSUE TITLE
Add "Your Vote" Column To Polls Tab In Wallet

### ISSUE THREAD

**Issue by dblanch256** [gridcoin-community/Gridcoin-Tasks#231]
Many times I cannot recall whether or not I've already voted in a particular poll.  The underlying reason for this is two-fold.  1) I'm getting older, and 2) Many of these polls are long duration.

I was told that the wallet allows me to vote multiple times (without complaint) as a mechanism for changing my mind (only the last vote counts) and I would suggest keeping this feature.

However, I'd like the capability to "see at a glance" whether I voted (per each issue) and what option I selected.  I think that both of these goals could be met by adding a column named YOUR VOTE to the existing ones on the polling pane.  [Probably no need to include a date.]  

This feature would allow me to verify that there is no active poll in which I haven't participated.

**Comment by jring-o** [comment]
Hey @dblanch256 post this on the technical issues board. That's where the devs pay the most attention.

https://github.com/gridcoin-community/Gridcoin-Research/issues
