### ISSUE TITLE
LOTTERY to reward block stakers

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#24]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 00:48 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/22_

----

goal: increase staking participation

* e.g. via an external script that rewards randomly(?) one of the block creators

questions:
* how much reward is enough?
* 1x daily ?

mentioned in [hangout 22](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_01_21.MD):

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Jan 22, 2017 at 15:01 GMT_

----

>Perhaps creating a monthly lottery (external payment/rain (sendmany) script) where by having staked a block is en entry into a lottery to win x GRC? We could take the addresses were used to stake as the reward address.

**Comment by skcin** [comment]
<a href="https://github.com/frank0051"><img src="https://avatars2.githubusercontent.com/u/3454785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [frank0051](https://github.com/frank0051)**
_Sunday Jan 22, 2017 at 17:01 GMT_

----

This would be nice. 5-10 GRCs would probably be enough - that's 5x to 10x larger than the largest payouts on eobot faucet. Now, when I mine is that considered staking too?

**Comment by skcin** [comment]
<a href="https://github.com/MagixInTheAir"><img src="https://avatars1.githubusercontent.com/u/8146140?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MagixInTheAir](https://github.com/MagixInTheAir)**
_Monday Aug 28, 2017 at 20:49 GMT_

----

I like the idea... Just a question : where would the grc given come from ?

**Comment by grctest** [comment]
It'd be a 3rd party whom implemented this, it wouldn't be difficult to implement but there hasn't been much interest in the concept this year.

**Comment by NeuralMiner** [comment]
IMO CBR accomplishes the goal of increasing staking participation. Good to close?
