### ISSUE TITLE
Security expired

### ISSUE THREAD

**Issue by philipswift** [gridcoin-community/Gridcoin-Tasks#240]
https://gridcoin.world/ is unsafe. Please right this off as nothing has happened and we have too many Gridcoin URL's as well as all the social media. source: Sectigo RSA Domain Validation Secure Server CA

**Comment by jamescowens** [comment]
@jring-o Can you please address. We should get the certificate updated or take gridcoin.world down until it is ready.

**Comment by caraka** [comment]
imho, the easiest thing to do is forward the url to gridcoin.us until such time as a new site and/or cert is available.

**Comment by philipswift** [comment]
That would not be good for SEO and all the bots would still rank it as unsafe. It should be removed.

**Comment by jring-o** [comment]
All set. Sorry for the delay

**Comment by philipswift** [comment]
Please do not be sorry, good things take time.
