### ISSUE TITLE
WhiteList SiDock@home

### ISSUE THREAD

**Issue by Aurum420** [gridcoin-community/Gridcoin-Tasks#244]
This poll seeks approval to whitelist the SiDock@home project thus allowing participants to earn GRC for completing work units for the project. Instructions for this poll are from https://gridcoin.us/wiki/whitelist-process.html.

Poll funding was provided by CPID 3c077620e211d1237d796b34fe93941d.

**Whitelisted Project Admins** are active on their BOINC forum: 
Crtomir aka Dr. Črtomir Podlipnik
Natalia aka Dr. Natalia Nikitina
hoarfrost aka Maxim Manzyuk
Dr. Marko Jukić
Dr. Ilya Kurochkin
Alexander Albertian

**Poll Discussion**
Github is the best place since BOINC forums are ineligible for WhiteListing talk.
https://www.reddit.com/r/gridcoin/comments/mbrcaf/sidockhome_poll_discussion_thread (Moderator: RoboticMind)
https://steemit.com/gridcoin/@roboticmind/sidock-home-whitelist-poll-discussion-thread (Moderator: RoboticMind)

**Poll Question**
Should Gridcoin whitelist the BOINC project SiDock@home ???
https://www.sidock.si/sidock/

**Poll Options**
Yes or No. Also Abstain for the indecisive. Since a majority (>50%) must vote Yes to pass an Abstain vote is mathematically equivalent to a No vote. A recent GRC poll showed that 73.56% of the Magnitude+Balance voters thought this actually makes sense.

**Poll Duration**
21 days

**Poll Validation Requirements**
A whitelist poll is approved if the majority vote yes, it gets an active vote weight of 40% or greater, and the above steps are met, the project is now on the whitelist. Active vote-weight (AVW) is a calculated average of the vote weight actively securing the network for the duration of the poll, plus the network magnitude, less the magnitude of any crunching pools. The formula for AVW is:

AVW = (AverageDifficulty x 9544371.769) + (TotalNetworkMagntiude - AveragePoolMagnitude)(AverageMoneySupply)/(5.67 x TotalNetworkMagnitude)

**Comment by barton2526** [comment]
Has the project admin been contacted?

**Comment by RoboticMind** [comment]
> Has the project admin been contacted?

On the last (invalid) poll, one of the people working on the projects said this, but I'm not 100% sure if this would count https://www.sidock.si/sidock/forum_thread.php?id=72&postid=589
```
Gridcoin. Good idea ;-). Do you have experience how to set this.

Crtomir
```

I am going to contact the them to double check if they're still interested now especially with the strain from Formula BOINC 


> Since a majority (>50%) must vote Yes to pass an Abstain vote is mathematically equivalent to a No vote...

This is not the case. Abstain votes are disregarded when determining which option wins. They are meant to increase % of AVW without having to have a strong opinion (i.e a vote that I see a poll, but just don't have an opinion vs not seeing a poll altogether ). I should probably clarify this in the whitelist-process wiki page (which is just describing, but not the definition of the rule). I said there that the majority needs to vote yes, but I meant that it just needs to get more yes votes than no votes to pass

**Comment by jamescowens** [comment]
@Aurum420 Why can't you follow the rules? The minecraft@home folks did. The poll is supposed to have a yes, no, and abstain choices.

**Comment by jamescowens** [comment]
Despite that, I think the community would be willing to treat the poll as valid anyway. You may be putting the large stakeholders in a difficult position regarding this, and it may make the AVW% difficult to achieve.

We need to see recent communications with the project admins to ensure the project is ready for the volume that the Gridcoin network will bring.

**Comment by jamescowens** [comment]
Looks like they do wingman checks. I am going to vote yes. The poll is not valid though until all of the requirements in addition to the poll are met.

**Comment by RoboticMind** [comment]
>  The poll is supposed to have yes, no, and abstain choices.

It looks like it does have all three? Are you looking at the correct poll (the "Whitelist Sidock@home" one and not the "Sidock@home" poll)?

**Comment by jamescowens** [comment]
You are right. I was looking at the earlier one by mistake I think.

**Comment by jamescowens** [comment]
@Aurum420 It looks like this is a good project. I am personally voting yes. My only concern from reading up on it is the short deadline for tasks...

**Comment by startailcoon** [comment]
How is this statement true?

> Yes or No. Also Abstain for the indecisive. Since a majority (>50%) must vote Yes to pass an Abstain vote is mathematically equivalent to a No vote. A recent GRC poll showed that 73.56% of the Magnitude+Balance voters thought this actually makes sense.

Abstain is not counted as anything as it is in there to make sure the poll has been accepted by enough investors, 40%. A minimum of 40% of the active coins has to vote for the poll to be valid. Then Yes and No are weight against each other.

**Comment by Crt123** [comment]
I'm pleased to announce that the core group of the SiDock@Home project approved GridCoin idea, but we need some time to prepare our servers and also to set up checkpoints (important task in our priority list). We estimate that we will be ready to launch GridCoin in two months. What are next steps.

Crtomir from  SiDock@Home

**Comment by RoboticMind** [comment]
> but we need some time to prepare our servers and also to set up checkpoints (important task in our priority list).We estimate that we will be ready to launch GridCoin in two months

That is perfectly okay and other projects have done this before! This just means that you won't be added to the whitelist immediately after the poll, but that's happened with some other projects before 

> What are next steps

Waiting to see if this poll passes and then letting us know when you are ready to be whitelisted (assuming the poll passes)

---

Also,  I have created Reddit and Steemit threads:
* https://www.reddit.com/r/gridcoin/comments/mbrcaf/sidockhome_poll_discussion_thread/
* https://steemit.com/gridcoin/@roboticmind/sidock-home-whitelist-poll-discussion-thread
@Aurum420 could you edit your post to add those to the discussion thread section? I'm really happy to say that this is a valid poll now!

**Comment by Aurum420** [comment]
> Has the project admin been contacted?
Yes: https://www.sidock.si/sidock/forum_thread.php?id=72&postid=589#589

**Comment by Aurum420** [comment]
> @Aurum420 Why can't you follow the rules? The minecraft@home folks did. The poll is supposed to have yes, no, and abstain choices.
Owens are you blind? Look at the poll, it has your ridiculous Abstain category even though it's equivalent to voting NO.

**Comment by jamescowens** [comment]
I saw that and I took back my comments.

**Comment by jamescowens** [comment]
Abstain is NOT equivalent to voting no. If it was you would not need an abstain category.

**Comment by barton2526** [comment]
This poll has failed to reach the required AVW (40%) for validation.

https://www.gridcoinstats.eu/poll/8ca2dcb7b6b3943cacf922dac6699514b517bcad9b8100061d7f73163a7b4728/1/

**Comment by Aurum420** [comment]
> Abstain is NOT equivalent to voting no. If it was you would not need an abstain category.

Abstain is absolutely equal to NO. Using abstain is absurd in this context. What legitimate use does Abstain have here? The definition for winning is greater that YES/(ABSTAIN+NO) > 50%. Ergo, if ABSTAIN + NO > 50% then it loses.

**Comment by Aurum420** [comment]
> This poll has failed to reach the required AVW (40%) for validation.
> 
> https://www.gridcoinstats.eu/poll/8ca2dcb7b6b3943cacf922dac6699514b517bcad9b8100061d7f73163a7b4728/1/

This definition is ridiculous. How is it relevant??? Where does one even look this nonsense up???
AVW = (AverageDifficulty x 9544371.769) + (TotalNetworkMagntiude - AveragePoolMagnitude)(AverageMoneySupply)/(5.67 x TotalNetworkMagnitude)

**Comment by Aurum420** [comment]
GRC to make fake cactus but not look for Covid drugs. Gridcoin fails again.

**Comment by RoboticMind** [comment]
It is likely that having two simultaneous SiDock polls is the reason that this did not get the needed AVW. A lot of people mistakenly voted on the wrong one. I strongly doubt it is related to SiDock at all. I would strongly advise waiting until the project is ready until making any further polls on this (I would recommend that someone else make this poll). 

If you want to know where the definition of AVW is, it's given linked to in the very link to the whitelist process wiki page you posted at the top of the poll. As well it can be found in the voting wiki page with https://gridcoin.us/wiki/voting#active-vote-weight or more directly https://gridcoin.us/wiki/voting#11-vote-weight-and-active-vote-weight

> How is it relevant

So polls don't get approved with few people on the network voting. AVW aims to find the amount of voteweight that's active on the network. In essence it's: `active balance + (network magnitude - pools' magnitude)` but weighted according to how each part contributes to a vote 

> Abstain is absolutely equal to NO. Using abstain is absurd in this context. What legitimate use does Abstain have here? The definition for winning is greater that YES/(ABSTAIN+NO) > 50%. Ergo, if ABSTAIN + NO > 50% then it loses.

@Aurum420 That is not the definition or how the votes are determined. It's yes/no > 50% with abstains removed. Abstain is meant to help say "I see this poll, but I don't have strong opinions on it" vs not voting at all. In short, it increases AVW without having to have a strong opinion, so you can see that people are aware of the poll vs just not voting or aware of it.

**Comment by nathanielcwm** [comment]
The poll was very clearly positive towards whitelisting so I'd believe that if it was done again without the errorneous poll that it would easily be able to meet the requirements to be whitelisted.

**Comment by startailcoon** [comment]
For the record, mentioned Poll about vote weight is [Poll Tx 9dc313...](https://www.gridcoinstats.eu/poll/9dc313ac8912c950bd9ccbb29498134c3080a5744ec2f51ba4e520d070d40d62). 

This poll casually asks the Community about their view on the Abstain option in polls, and if they think it makes sense to have it.

Out of an active vote weight of 237 112 786 (53.4% of total), a total of 25 254 890 (10.65% of AV-W) did vote on this poll.
This can be seen as a low voting return, as the polls usually have > 20%, and Decision polls require > 40%.

The result was an agreement on the Abstain being a valid question.

Option | Vote %
-|-
Yes | 73.57% 
No | 15.19%
Abstain | 11.25%

While OP mentions this in the header, it needs to be clarified that "Abstain" is not a "No" vote.
The following statement is false as Yes/No votes are weight against each other, while Abstain is used to make sure enough of the community has engaged in the poll.

> Since a majority (>50%) must vote Yes to pass an Abstain vote is mathematically equivalent to a No vote.

**Comment by Aurum420** [comment]
So are you saying that the poll vote is decided by Yes/(Yes+No) > 50% ??? It does not say that anywhere in the Wiki.
"To pass, a poll must get a majority of the vote and must be at or above the poll’s active vote weight (AVW) requirement." 
(https://gridcoin.us/wiki/voting.html)
There's not one word saying that Abstain is in the denominator or not in the denominator. And since Abstain is a vote it is included in the denominator. I.e., Yes/(Yes+No+Abstain) > 50%. The formula may be coded as you say but the text does not say so.

**Comment by RoboticMind** [comment]
@Aurum420  It's on the first wiki page you linked the top of this thread 

> A whitelist poll is approved if the majority (excluding abstentions) vote yes, it gets an active vote weight of 40% or greater, and the above steps are met, the project is now on the whitelist

https://gridcoin.us/wiki/whitelist-process.html

The wiki does not defined the rules. I have clarified on the whitelist page, but I missed adding that to the voting wiki page. I will update that soon now

**Comment by barton2526** [comment]
Has anyone contacted the SiDock admins to see if they would be ready to try this poll again?

**Comment by Aurum420** [comment]
How will this poll ever pass if it requires AVW > 40% for validation? Convenient that when devs want to get paid it only requires 20%. AVW should be abandoned as it gives control to a few with the largest balances. The largest balances have zero magnitude rendering magnitude inconsequential, likely the wallets of aggregators. After watching approval for QuChemPedIA be sabotaged and the governing disaster of trying to whitelist SiDock I doubt there will ever be another legitimate science project whitelisted again. No, why bother?

**Comment by barton2526** [comment]
> How will this poll ever pass if it requires AVW > 40% for validation? 

Minecraft passed in February with 46.5% AVW (https://www.gridcoinstats.eu/poll/d49c5ba4863a9c6ba914a627625ff2d76262f45fef6135bcca382f772dd3cdfd)

> Convenient that when devs want to get paid it only requires 20%. 

The dev poll received 47.5% AVW (https://www.gridcoinstats.eu/poll/c8a5d3417f3bacd086fd1cb1be84c00f659fcdddd945d404a421b30e287a4211)

> AVW should be abandoned as it gives control to a few with the largest balances. The largest balances have zero magnitude rendering magnitude inconsequential, likely the wallets of aggregators. After watching approval for QuChemPedIA be sabotaged and the governing disaster of trying to whitelist SiDock I doubt there will ever be another legitimate science project whitelisted again. No, why bother?

The "disaster" of SiDock's poll(s) failing was entirely your own.  You didn't bother to follow procedure 3 separate times and no one knew which poll was legitimate because you created so many incorrect polls.

I am asking if anyone has contacted the project to see if we can try this again, correctly this time.  Perhaps if you don't get involved it might pass.

**Comment by Crt123** [comment]
Dear Colleagues,

I do not understand the procedure to adopt gridcoin, it is quite
complicated if I am honest. Yes, it would be nice that volunteers of SiDock
would get some reward for their work,
but on the other hand, we have a lot of work to do in the scientific part
of the project: to maintain CMDock, the docking software; and to analyze
results of virtual screening etc
I will contact my close collaborators to set a strategy for gridcoin.

Crtomir

**Comment by denravonska** [comment]
> AVW should be abandoned as it gives control to a few with the largest balances.

AVW is just a way to set a lower bar for a poll to be accepted. It's a good enough of a tool to filter out topics that aren't of any interest to the community. Removing it would have no impact over what the whales can and cannot do. On the contrary, removing it gives more control to the whales.
