### ISSUE TITLE
WhiteList SiDock@home Round 2

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Tasks#249]
This poll seeks approval to whitelist the SiDock@home project

Poll Discussion
Github is the best place since BOINC forums are ineligible for WhiteListing talk.
https://www.reddit.com/r/gridcoin/comments/nty89j/sidockhome_poll_discussion_thread/
https://steemit.com/hive-161364/@roboticmind/whitelist-sidock-home-round-2-or-poll-discussion

Poll Question
Should Gridcoin whitelist the BOINC project SiDock@home?
https://www.sidock.si/sidock/

Poll Options
Yes, No, Abstain

Poll Duration
21 days

Poll Validation Requirements
A whitelist poll is approved if the majority vote yes, it gets an active vote weight of 40% or greater, and the above steps are met, the project is now on the whitelist.

See previous poll (https://github.com/gridcoin-community/Gridcoin-Tasks/issues/244)

Project admin approval: https://www.sidock.si/sidock/forum_thread.php?id=131

**Comment by RoboticMind** [comment]
For ease of reading, here's the project admin approval message:

> Hello everyone,
> 
> we want to be whitelisted in Gridcoin (anytime), so you will be able to receive this cryptocurrency for scientific computing. We believe that Gridсoin is ethical. This is also a chance to increase awareness of the project. 

<br> 

Title:  "SiDock@home is going to join Gridcoin"
Author:  Natalia (Project administrator) (Project developer)

**Comment by markjhealey** [comment]
Yes

**Comment by RoboticMind** [comment]
@markjhealey make sure to vote in your wallet as only saying things here doesn't count as a vote. For more information on how to do that see https://gridcoin.us/wiki/voting#voting-on-a-poll

**Comment by markjhealey** [comment]
@RoboticMind Good point, guess I need more coffee today...

**Comment by mitjaviskric** [comment]
Yes

**Comment by RoboticMind** [comment]
@markjhealey make sure to vote in your wallet as only saying things here doesn't count as a vote unfortunately. For more information on how to do that see https://gridcoin.us/wiki/voting#voting-on-a-poll

**Comment by throny** [comment]
Voted yes but only 287 voters in total? Seems it will be hard to beat the 40% tho.. Would really love to add this project to my hosts.

**Comment by div72** [comment]
@throny The poll has passed 40% AVW [according to gridcoinstats.](https://www.gridcoinstats.eu/poll/d3c5a547312acb4b97ae37594cadfc98bc72d174dfc9c5892fa4b4a3e9c1f25b)

**Comment by RoboticMind** [comment]
The poll has now ended and it passed and was validated. SiDock@Home is now on the whitelist and will be in the next superblock!


The vote was ~97% yes to ~1.5% No to ~1.4% Abstain by voteweight. As well the poll reached the 40% AVW threshold. 
Gridcoinstats.eu reports the AVW at around 43%, but the bash script I wrote to calculate AVW reports it at ~47%. Either way, this poll is validated
