### ISSUE TITLE
Improving incentivization system. 

### ISSUE THREAD

**Issue by Weber462** [gridcoin-community/Gridcoin-Tasks#256]
What ways can we improve the project GRC rain?
"The ability of a project to "donate" GRC into a distribution account, where that account would define over how long to distribute those funds."

**Comment by Weber462** [comment]
Just experienced first rain today.  I think it would be less confusing if the issuer could add why, who, frequency, quantity, and duration in message.  I don't know if this is even possible.

**Comment by barton2526** [comment]
Rain messages were removed in the Ingrid release due to spam and abuse.

**Comment by Weber462** [comment]
Yeah, i just learned about that.  Its unfortunate.  If you cant say why, whats the incentive?  Hopefully we can  make contacting crunchers more efficient via other means then wallet.
