### ISSUE TITLE
Collaboration for the "unrealistic at this point"!

### ISSUE THREAD

**Issue by PrestackI** [gridcoin-community/Gridcoin-Tasks#262]
Making this post so I can collate the Idea for the poll.

I was told that certain Goals were unrealistic. https://www.mersenneforum.org/showthread.php?t=13196&page=18

I am making a Survey Poll to see if there is a enough people willing to make the "unrealistic" a reality!

After discussing it with a project operator (Rebirther of SRBase), I am focusing the poll on the following question.

Should we try for Goal 14 of "Complete S79 to n>=100K: 6971 k's for k>3K n=50K-100K"?

Vote "Yes".

Vote "No".

Vote "Abstain".

**Comment by makeasnek** [comment]
I am confused by what this poll is proposing. IIRC there are a certain subset of bases the project doesn't make WUs before because they think there's no interest in them. So you want Gridcoiners to volunteer to do these WUs, but the WUs don't exist, are you going to make an entirely new BOINC project?

**Comment by PrestackI** [comment]
@makeasnek I was asking a simple question. 

Should we try for goals that are deemed "unreasonable" by the Scientists?

**Comment by hucker75** [comment]
Your question is not simple.  Are you asking us to do it seperately as gridcoiners?  If so how?  Or are you asking if we should pester the scientists to do unrealistic goals when they want to concentrate the resources on something else?

**Comment by PrestackI** [comment]
As gridcoiners, we can join Rebirther. 

Rebirther did the pestering, 9.1M tasks to achieve the goal.

They have stated it, https://srbase.my-firewall.org/sr5/forum_thread.php?id=1812

I am surprised my interaction has set such a task.

**Comment by PrestackI** [comment]
@makeasnek I did interaction and it yielded the true amount to accomplish the goal.

The result is 9.1M workunits to accomplish the goal in 11 weeks.

**Comment by PrestackI** [comment]
The majority voted "Abstain", but 25% voted "Yes".

I see that as a win! It only takes 25% of us to achieve random goals!

**Comment by hucker75** [comment]
No, the vote on Gridcoin was 62% yes, 30% abstain, 7% no.  Or have you also created the poll elsewhere?

**Comment by PrestackI** [comment]
![image](https://github.com/gridcoin-community/Gridcoin-Tasks/assets/24862419/6d0d9f18-a86f-42d1-a7dd-ee7339534214)

I got 62% "Yes"?

My spot check says otherwise.

**Comment by PrestackI** [comment]
@hucker75 What showed you 62% "Yes"?

**Comment by hucker75** [comment]
My gridcoin wallet shows this:

![image](https://github.com/gridcoin-community/Gridcoin-Tasks/assets/66015018/d0379036-3c8a-411a-9014-1a713aa3dd8b)

**Comment by hucker75** [comment]
No matter which is right, yes is far higher than no.  Abstain doesn't count.  Those are people who don't care either way so don't matter.

**Comment by PrestackI** [comment]
Great!

But, What?

Why and How do we see a difference?

**Comment by hucker75** [comment]
I don't understand what you're asking me.

**Comment by PrestackI** [comment]
Okay. I pressed refreshed before my last response.

It appears that maybe the Presentation of the Date changes things?

I only propose that because of the screenshot.

**Comment by hucker75** [comment]
I don't know what you mean, what is "presentation of the date"?  I simply said it ought to refresh itself.  When I view a news page on the internet, I don't expect to have to refresh it or get last week's news.

**Comment by PrestackI** [comment]
Can you refresh and post another screenshot?

The Elders are telling me that it should be closer to my screenshot.

**Comment by hucker75** [comment]
As I already said, refreshing made it the same as yours.  But I shouldn't have had to do so.  I believed what it first told me.

**Comment by jamescowens** [comment]
We cannot do a continuous refresh on polling, because the calculations are too heavyweight. It is probably a good idea to indicate the height at which the poll results were calculated, and also define a "stale" indicator.

**Comment by hucker75** [comment]
Continuous wouldn't be needed, just keep it reasonably up to date.
