### ISSUE TITLE
Treasury and Mandatory Sidestaking Poll

### ISSUE THREAD

**Issue by jring-o** [gridcoin-community/Gridcoin-Tasks#263]
**NOTE:**

**The "X" percentage IS NOT the percentage sent to the treasury**

The 15-30% is the hard-coded maximum that the protocol will be technically capable of sending.

The actual percentage to be sent to the treasury will be determined in a future poll.

In terms of percentages, this poll is determining a safety measure of the mechanism, nothing more.

## Introduction

This proposal outlines the establishment of a Gridcoin Treasury, a financial structure designed to support the sustainability and growth of the Gridcoin network. Central to this system are **Parent/Child Wallet** relationships and **Mandatory Sidestakes**. Parent wallets are primary wallets that belong to verified organizations, such as the Gridcoin Treasury. Child wallets are subwallets of a parent and are dedicated to various initiatives of the parent, such as research grants, development grants, and outreach grants. 

The treasury will be funded through network fee allocation and through the Mandatory Sidestaking mechanism. This system aims to provide a transparent, efficient, and democratic means of funding critical projects and community endeavors, ensuring the long-term success and innovation of the Gridcoin ecosystem.

This proposal asks for approval of the proposed treasury structure, along with your opinion on a hard-coded maximum rate that the Gridcoin protocol will ever allow redirected for a user’s earned rewards.

## Introduction to Mandatory Sidestaking 

Mandatory Sidestaking is a forward-thinking approach where a specified portion of the rewards from a staked block is automatically allocated to another wallet—specifically, the Gridcoin Treasury. 

This method expands upon the proven mechanisms of voluntary sidestaking and MRC fees, where 80% of generated fees are directed to the foundation, demonstrating a successful precedent within our network.

Mandatory Sidestakes can be granularly defined, meaning any subset of fees and rewards can be affected by the requirement at any rate.

## Treasury Structure 

The treasury will be structured with one parent wallet and an undefined number of children wallets. Each child wallet, besides those proposed in this instantiating proposal, must be approved by the Gridcoin network via the Treasury Child Wallet Proposal process. The parent wallet and each child wallet will have their own independent rules governing how funds within the wallet are released.

The parent wallet is a general use wallet. It will be the first wallet created as detailed in the “Proposed Initiation” section of this proposal.

The proposed instantiating children wallet for the treasury are:

**Development Grants**

For funding development and maintenance of Gridcoin and the Gridcoin ecosystem

**Research Grants**

For funding scientific research

**Distributed Computing Grants**

For funding development and maintenance of distributed computing projects

## Funding the Treasury with Mandatory Sidestaking 

The sustainability and expansion of the Gridcoin network are contingent upon a reliable and robust funding mechanism. Mandatory Sidestaking is proposed as a foundational component of this financial structure, ensuring a consistent and democratic allocation of resources to the Gridcoin Treasury. 

The Mandatory Sidestaking system is designed to be intuitive, flexible, and transparent. When a Gridcoin user successfully stakes a block, a predetermined percentage of their reward is automatically designated as a sidestake. This sidestake is then directed to the Treasury's parent wallet or to one of the specific children wallets, depending on the user's preferences and the predefined rules.

## Implementation

Implementation of the Gridcoin Treasury and Mandatory Sidestaking will take place in multiple phases.

**Phase 1:** Defining safety variables, Treasury structure, and future developments (This Poll) 

**Phase 2:** Development of Child Wallets and processes

**Phase 3:** Defining future variables (A poll for a later date)

### Proposed End-State of Treasury and Mandatory Sidestaking:

**Sidestake Percentage Maximum:**

It is proposed that a safety measure be hard-coded into the Gridcoin protocol. This safety measure will guarantee that no more than X% of the total rewards received by a network participant is redirected to any other wallet.

The percentage being chosen by this poll **is not** the rate that will be redirected from earned rewards. It is the absolute maximum that the protocol will allow. It is intended to guard against any bugs and malicious behavior across the network.

The actual mandatory sidestake rate will be determined in a future poll. Those rates are Y and Z as defined below.

**Allocation to the Parent Wallet:**

A fixed Y% of each mandatory sidestake will be automatically allocated to the Treasury’s parent wallet. This portion represents a general fund, ready to be deployed across a wide range of needs and opportunities as determined by network consensus and governance protocols.

**User-Directed Allocations:**

The remaining Z% of the mandatory sidestake provides users the flexibility to support specific initiatives within the Treasury structure. Participants can decide which children wallets (e.g., Development Grants, Research Grants, Distributed Computing Grants) receive what percentage of their Z%, tailoring their contributions to align with personal interests or perceived network needs.

**Dynamic:**

The Y and Z percentages can all be adjusted by changing values in the protocol. These values can be static numbers or dynamic protocols of their own. Perhaps the allocation of Mandatory Sidestakes shifts based on the needs of the network as determined by some set of future metrics. This flexibility also enables expansion of Child Wallets to include more than the three instantiating children.

## Proposed Initiation

1. We propose establishing the treasury with the single Parent Wallet.
2. We propose setting the maximum mandatory sidestake at the percentage determined by this poll. 
3. We propose continuing development to reach the proposed end-state detailed above.

**IMPORTANT:** This poll is seeking approval for and input on the foundations of Mandatory Sidestaking and the Treasury. Mandatory sidestaking will not begin until _at least_ the next mandatory update to Gridcoin.

## Next Steps

Should this proposal be approved by the network:

1. The value of X will be set at the winning percentage. 
2. Development will continue on the treasury structure and mandatory sidestake mechanism as detailed in this proposal.
3. Mandatory Side Staking will be implemented at or after the next Gridcoin mandatory release.
4. Development will proceed on implementing the three instantiating children wallets in the treasury, along with their corresponding fund-release processes.
5. Development of the Treasury Child Wallet Proposal process will proceed.
6. A future poll on the values of Y and Z as detailed in the proposed end-state will take place when the necessary technical infrastructure is in place.

## Conclusion

This proposal presents a comprehensive and strategic plan to establish the Gridcoin Treasury, a financial bedrock designed to bolster the network's sustainability and growth. With a Mandatory Sidestaking mechanism and a structured treasury, we're not just creating a funding mechanism but also a dynamic engine where increased network activity directly translates to enhanced treasury resources. This, in turn, fuels further expansion and development of the Gridcoin network. The next steps, following the treasury's formation and initial seeding through Mandatory Sidestaking, will focus on driving and incentivizing activity within the Gridcoin network. By doing so, we ensure a self-reinforcing cycle of growth and innovation, where every transaction and participation in the network not only contributes to its current operations but also to its future potential. 

## The Poll

**Question:** Do you approve of the proposed treasury structure and mandatory side stake mechanism?

**Answers:**
- Yes, if the maximum mandatory side stake (X) is 10%
- Yes, if the maximum mandatory side stake (X) is 15%
- Yes, if the maximum mandatory side stake (X) is 20%
- Yes, if the maximum mandatory side stake (X) is 25%
- Yes, if the maximum mandatory side stake (X) is 30%
- No
- Abstain

**Comment by jamescowens** [comment]
The mainnet poll was valid.
![image](https://github.com/gridcoin-community/Gridcoin-Tasks/assets/7529186/8caff6b7-511e-4648-abea-c79121086747)

Based on the results, the maximum mandatory sidestake (limit) will be 25%.
![image](https://github.com/gridcoin-community/Gridcoin-Tasks/assets/7529186/8a5fc49b-ec81-497f-a880-118a3ff467a9)
