### ISSUE TITLE
Stress Testing Consensus.

### ISSUE THREAD

**Issue by PrestackI** [gridcoin-community/Gridcoin-Tasks#264]
**Should we use this Fork to break consensus even further?!?!?!?**

Jim already let us know the Fork was caused by an error.
Let's break it further by making dueling polls. 
One on the Fork and one on the Main (Non-Fork).

I am curious to know what a poll on a Fork would look like compared to the Non-Fork chain.

I made this post to attach to the poll Non-Fork chain.

The ultimate goal of the poll is to improve consensus overall!

We need a volunteer to make a poll on the Fork chain of the poll for good measure...
@jamescowens Can you do it?

**Comment by flammobammo** [comment]
I have been drawn to this post from the URL provided in the Gridcoin Wallet 'survey' question as background information for the question of 'Shoudl we use this Fork to break consensus even further?' in relation to 'Gridcoin Testing Consensus' as a title of the pool. As a common user of Gridcoin Wallet I am not presented with sufficient information to dive deeper into this subject to be able to provide a response to the poll. The options are Yes, No, or Abstain, and I'm not abstaining, hence why I'm here. But there is not sufficient information to be able to respond. It is therefore my considered opinion that this Survey be withdrawn and a more detailed Survey posted, with appropriate background information explained in a suitable way such that the majority of Gridcoin users would reasonably understand the question being asked.

**Comment by jamescowens** [comment]
The poll didn't cross the fork boundary.

**Comment by jamescowens** [comment]
Making a new poll on the other fork will be with a different hash so it will be considered a different poll. The votes will not be intermixed. No need to do this exercise I think.

**Comment by flammobammo** [comment]
The poll question lacks the secondary thread as required by the Gridcoin rules for posting a poll: https://gridcoin.us/wiki/voting.html


> I have been drawn to this post from the URL provided in the Gridcoin Wallet 'survey' question as background information for the question of 'Shoudl we use this Fork to break consensus even further?' in relation to 'Gridcoin Testing Consensus' as a title of the pool. As a common user of Gridcoin Wallet I am not presented with sufficient information to dive deeper into this subject to be able to provide a response to the poll. The options are Yes, No, or Abstain, and I'm not abstaining, hence why I'm here. But there is not sufficient information to be able to respond. It is therefore my considered opinion that this Survey be withdrawn and a more detailed Survey posted, with appropriate background information explained in a suitable way such that the majority of Gridcoin users would reasonably understand the question being asked.
