### ISSUE TITLE
reach out to BOINC projects: GRC donate button (from coinpayments)

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#29]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 01:05 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/27_

----

@grctest : "We should reach out to BOINC projects, asking them to add a donate button (or one of those 'one-name' things) to their website so that we can easily donate GRC to them."

There is a template letter available to do this (ask @Peppernrino)

questions:
* only whitelisted BOINC projects ?
* check letter
* should we get an official email from gridcoin.us ? (ask @grctest)

mentioned in [hangout 22](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_01_21.MD):

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Jan 22, 2017 at 15:42 GMT_

----

I think we'll have the highest success rate with whitelisted projects.

I don't think it'll be necessary to use an official gridcoin.us email address; many projects do not provide public email addresses, we'll likely have to create a topic in their message boards and also private messaging the project admins/moderators via the project's inbuilt messaging system.

Do you think making this mandatory would be effective?

**Comment by skcin** [comment]
<a href="https://github.com/MagixInTheAir"><img src="https://avatars1.githubusercontent.com/u/8146140?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MagixInTheAir](https://github.com/MagixInTheAir)**
_Monday Aug 28, 2017 at 20:31 GMT_

----

I think it is a good idea to make it mandatory when a good part of the whitelisted projects agreed on adding a donate button - If we don't wait, it may lead to deleting project for the mere reason they didn't put a button. On the other hand, it could be a very good communication for grc and I think it is a good idea :)

**Comment by skcin** [comment]
<a href="https://github.com/tomasbrod"><img src="https://avatars1.githubusercontent.com/u/11995799?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tomasbrod](https://github.com/tomasbrod)**
_Monday Aug 28, 2017 at 21:45 GMT_

----

Gridcoins purpose is to augment BOINC and not to impose limits and restrictions. Therefore I don't agree with requiring donate button as a requirement to enter the white-list.

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Tuesday Aug 29, 2017 at 13:41 GMT_

----

iirc, most of the BOINC admins I asked in the [interviews](https://steemit.com/gridcoin/@erkan/interview-guide-with-boinc-admins-v4) did not want the button

**Comment by grctest** [comment]
Incredibly unlikely that BOINC projects will do this, at the workshop many opposed endorsing Gridcoin. If projects are accepting crypto they should be asked if they also accept gridcoin, but in the mean time this task has an impossible goal - closed.
