### ISSUE TITLE
bounty: 15k GRC -> create DPOR whitepaper (how does Gridcoin weight blocks)

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#3]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Friday Jan 20, 2017 at 15:21 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/3_

----

There is 
* an existing doc available, see [hangout 1](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_07_30.MD): 0:15:47 and 
* also a summary (with graphs) https://steemit.com/gridcoin/@cm-steem/pos-dpor-stake-weight-balance

@grctest (cm): maybe bounty is possible

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Saturday Jan 21, 2017 at 19:54 GMT_

----

I agree that a bounty could be worthwhile, the creation of a DPOR whitepaper will ensure that we can all understand the current state of DPOR & then improve upon it.

**Comment by razorshaman909** [comment]
Is the bounty still available, native chinese speaker here, haven't done whitepaper transalation before, been into cryptocurrency for 2 months, already getting hang of most things, including trading, really love gridcoin and would like to help.

**Comment by RoboticMind** [comment]
Is this still relevant?

**Comment by tomasbrod** [comment]
The task is. Not sure about the bounty.

**Comment by barton2526** [comment]
Who holds this bounty?

**Comment by jring-o** [comment]
This issue is no longer relevant and has been closed.
