### ISSUE TITLE
reach out to shops from coinpayments: to enable GRC

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#30]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 01:08 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/28_

----

There is a template letter available to do this (ask @Peppernrino)

These shops already allow GRC (please thank them [here](https://twitter.com/GridcoinIRC/status/836925777262362624))
* [store list](https://www.coinpayments.net/store-directory-coin-GRC) (29 shops)

questions:
* which shops first ? see [list](https://www.coinpayments.net/store-directory)
* check letter
* should we get an official email from gridcoin.us ? (ask @grctest)

mentioned in [hangout 22](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_01_21.MD): 

related to: #27

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Jan 22, 2017 at 14:58 GMT_

----

Does someone have a link to the template letter?

Should we track the list of stores, whether or not they've been contacted and if they've agreed to add GRC (or even responded)?

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 15:10 GMT_

----

@Pepperino should have the latest version, but it should be checked again

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Wednesday Jan 25, 2017 at 21:21 GMT_

----

just saw this, sorry guys!

http://pastebin.com/H94zJfbM

let me know any changes, etc.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Monday Jan 30, 2017 at 09:13 GMT_

----

Has anyone reached out to any stores yet, any responses?

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Friday Feb 10, 2017 at 14:37 GMT_

----

There is a poll ongoing until April 9:
* [Will you contact an online store to accept Gridcoin via coinpayments.net?](https://steemit.com/gridcoin/@erkan/gridcoin-poll-will-you-contact-an-online-store-to-accept-gridcoin-via-coinpayments-net-vote-until-april-9-2017)

current standing:
* 38% of the voter shares say YES
* 37% I Intend To Accept Grc Online Myself

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Feb 19, 2017 at 16:50 GMT_

----

3 shops already accept Gridcoin :-)

https://www.reddit.com/r/gridcoin/comments/5uy394/coinpaymentsnet_grc_shop_directory_buy_hot_sauce/

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Tuesday Feb 28, 2017 at 10:57 GMT_

----

4 shops now accept Gridcoin, woo! We need more! :D

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Saturday Mar 18, 2017 at 23:31 GMT_

----

mentioned in [hangout 26](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_03_18.MD): making a bounty for this task

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Sunday Mar 19, 2017 at 15:21 GMT_

----

edited the template to be more positive, and to include the suggested links. :)

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Sunday Mar 19, 2017 at 18:19 GMT_

----

Fucking Machine Fun - http://www.fmachinefun.co.uk/

confirmed add. 🥇

**Comment by skcin** [comment]
<a href="https://github.com/SirArian"><img src="https://avatars2.githubusercontent.com/u/26534306?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SirArian](https://github.com/SirArian)**
_Monday Mar 20, 2017 at 04:32 GMT_

----

You can get raw honey with Gridcoin, though it doesn't show up when you filter it by coin.

http://drapis.com/

I am rather new to Gridcoin, and not super experienced with cryptocoin in general, but I've a pretty good basic understanding of the concepts, and would be willing to contact companies about accepting Gridcoin. Is there a rhyme or reason to the order of companies, or just randomly pick one?

**Comment by skcin** [comment]
<a href="https://github.com/LokiToki"><img src="https://avatars0.githubusercontent.com/u/25841155?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LokiToki](https://github.com/LokiToki)**
_Monday Mar 20, 2017 at 08:50 GMT_

----

@SirArian when it doesn't show up, how u can pay with GRC? Oo

**Comment by skcin** [comment]
<a href="https://github.com/SirArian"><img src="https://avatars2.githubusercontent.com/u/26534306?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SirArian](https://github.com/SirArian)**
_Monday Mar 20, 2017 at 13:53 GMT_

----

On that store at least it shows up when you pick your payment method. It has a list of about forty different cryptocoins, and one of them in Gridcoin.

**Comment by skcin** [comment]
<a href="https://github.com/LokiToki"><img src="https://avatars0.githubusercontent.com/u/25841155?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LokiToki](https://github.com/LokiToki)**
_Tuesday Mar 21, 2017 at 08:37 GMT_

----

@SirArian Seems to be regional dependent. I just see this coins.
![coins](https://cloud.githubusercontent.com/assets/25841155/24138813/0442603e-0e1a-11e7-9bb4-521dbadb4710.png)

**Comment by skcin** [comment]
<a href="https://github.com/SirArian"><img src="https://avatars2.githubusercontent.com/u/26534306?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SirArian](https://github.com/SirArian)**
_Tuesday Mar 21, 2017 at 14:21 GMT_

----

@LokiToki Ignore me, I don't know what I'm talking about. I saw GCR and read it as GRC, and wasn't paying enough attention to see that the symbol was wrong...

I sent them an email, and will report back here if/when they reply.

**Comment by skcin** [comment]
<a href="https://github.com/SirArian"><img src="https://avatars2.githubusercontent.com/u/26534306?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SirArian](https://github.com/SirArian)**
_Wednesday Mar 22, 2017 at 04:25 GMT_

----

Now they do accept Gridcoin, for real this time, at [DrApis Portuguese raw honey](http://drapis.com/). If you want honey or beeswax or other bee products, head over there and give him some business.

Now to pick the next company to email. I also almost entirely rewrote the email based on the one linked to, and used it. If you want my version I can provide it.

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Friday Mar 24, 2017 at 13:39 GMT_

----

7 shops in total accept now Gridcoin (24 days ago: only 4)

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Saturday Mar 25, 2017 at 05:49 GMT_

----

in total it's 9 shops now:
I've added the adult category also above:
7 shops with non-adult products, and 2 which require you to be 18+

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday May 14, 2017 at 12:14 GMT_

----

over 20 shops accept now Gridcoin (thanks @PeppernRino) 
* [https://twitter.com/GridcoinIRC/status/863725648405200896](tweet)

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Friday Jun 09, 2017 at 19:45 GMT_

----

We need to pay $300 for another 90 days coin hosting on coinpayments:
https://www.coinpayments.net/coinhosting-step2-CE

Anyone fancy taking on the expense then creating a foundation expense proposal?

**Comment by skcin** [comment]
<a href="https://github.com/frank0051"><img src="https://avatars2.githubusercontent.com/u/3454785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [frank0051](https://github.com/frank0051)**
_Wednesday Aug 02, 2017 at 20:51 GMT_

----

29 shops now. 

https://www.coinpayments.net/store-directory-coin-GRC

**Comment by NeuralMiner** [comment]
Coinpayments no longer accepts GRC.
