### ISSUE TITLE
bring GRC into openbazaar

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#32]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 01:11 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/30_

----

https://openbazaar.org
https://twitter.com/openbazaar

mentioned in [hangout 22](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_01_21.MD):

**Comment by NeuralMiner** [comment]
GRC available for trade on OB: 
https://openbazaar.org/blog/New-OpenBazaar-Release-Enables-Trading-1500-Cryptocurrencies/
https://openbazaar.com/discover/results?q=&acceptedCurrencies=BTC&b0_coinType=grc&b1_rating=0&b2_moderators=all_listings&type=cryptocurrency&sortBy=relevance
