### ISSUE TITLE
Request Shapeshift integrate GRC 

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#33]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 01:13 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/31_

----

@grctest : "Despite Coinami's help, the continued response from ShapeShift is that Gridcoin is on a 'discovery list' and that they are not looking to add further coins in 2017, how disappointing."

* unless we get liquidity up ?
* anyways, people should contact them (tweets, email, ...) to bring attention to this

mentioned in [hangout 22](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_01_21.MD): 

related: #24

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Jan 22, 2017 at 15:35 GMT_

----

If we had ShapeShift support, it would result in being able to spend GRC on Purse.IO too.

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Wednesday Mar 22, 2017 at 09:52 GMT_

----

Shapeshift adds Golem https://twitter.com/customminer/status/844470613553156097

**Comment by skcin** [comment]
<a href="https://github.com/MrControl"><img src="https://avatars3.githubusercontent.com/u/27393212?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MrControl](https://github.com/MrControl)**
_Friday Aug 04, 2017 at 22:34 GMT_

----

https://twitter.com/ShapeShift_io/status/890604002399989761

Several new coins have been added over the last week or so, but there is no news about GRC.  Should we start a "letter campaign" of some sort as a community?

**Comment by grctest** [comment]
Further requests to shapeshift will likely yield the same canned response, but it's worth a shot to continuously bug them for integration.
