### ISSUE TITLE
raising bounties (for opensourced software/apps)

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#37]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 01:22 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/35_

----

In hangout 22 discussed: that bounties for opensourced software/apps is always welcome

see also: [get bounties for helping team Gridcoin](https://steemit.com/gridcoin/@erkan/get-bounties-for-helping-team-gridcoin)

questions:
* requirements for the product?
  * e.g. opensourced stuff, with a good licence for us
* how much bounty ?
* "And to be really trustworthy these bounties could be paid beforehand into a certain (multisig?) address, so the people know they really get it paid" (see [forum](https://cryptocointalk.com/topic/52091-grcsidedevelopment/#entry232121))

some ideas: category: [bounty](https://github.com/Erkan-Yilmaz/Gridcoin-tasks/labels/bounty)

mentioned in [hangout 22](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_01_21.MD):

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Jan 22, 2017 at 14:23 GMT_

----

>requirements for the product

Yeah, if development is being funded by the foundation it must be open source. We shouldn't subsidize companies.

>how much for each bounty

https://github.com/gridcoin/Gridcoin-Research/issues/184
https://cryptocointalk.com/topic/51761-gridcoin-roadmap/#entry231272
We should assign risk and priority to each commit in the backlog, then create bounties for the highest priority items.

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 16:54 GMT_

----

> how much for each bounty

* 100k GRC bounty for making a secure, opensourced Gridcoin pool: #2
* $50 or $100 bounty -> developping PoSv3: #43

https://steemit.com/gridcoin/@erkan/get-bounties-for-helping-team-gridcoin

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Thursday Jan 26, 2017 at 17:11 GMT_

----

i was also thinking it would be cool if we could fund a pool of devs to make some working linux GPU drivers...

**Comment by grctest** [comment]
@startailcoon Was recently talking about a possible escrow system within gridcoinstats for holding bounties in a secure manner.
