### ISSUE TITLE
strong points of GRC (as template to send out to various places)

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#41]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 01:36 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/38_

----

Phay mentioned like a normal CV has:
* I have achieved this and that
* and so on
* can be done via Google docs together

mentioned in [hangout 22](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_01_21.MD): by Phay

related to: #24

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Jan 22, 2017 at 14:14 GMT_

----

* [Came 1st in the 2016 FormulaBOINC challenge](https://steemit.com/gridcoin/@cm-steem/team-gridcoin-came-1st-in-the-2016-formulaboinc-challenge)
* Gridcoin rewards verified volunteer distributed computing on behalf of BOINC project administrators on top of proof of stake.
* We've been holding [dozens of decentralized polls](https://steemit.com/gridcoin/@erkan/gridcoin-polls-january-2017)!
* Gridcoin has recently been integrated into [Coinomi](https://coinomi.com/), [CoinPayments.Net](https://steemit.com/boinc/@cm-steem/gridcoin-community-hangout-022-21th-jan-2017-9pm-gmt-rsvp-and-suggest-topics#@cm-steem/re-cm-steem-re-cm-steem-gridcoin-community-hangout-022-21th-jan-2017-9pm-gmt-rsvp-and-suggest-topics-20170116t183457956z) & [OpenLedger](https://bitshares.openledger.info/).
* Team Gridcoin [now has 100k+ hosts crunching for science](https://steemit.com/gridcoin/@vortac/gridcoin-team-has-100-000-hosts-crunching-for-science)!
* The BOINC community has 200k+ active volunteers and a total of 4million+ volunteers. There is significant room for the Gridcoin userbase to grow within the BOINC community.

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Thursday Jan 26, 2017 at 10:41 GMT_

----

mentioned in [hangout 6](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_09_10.MD):

* from where does Gridcoin get its value ?
  * more energy efficient than Bitcoin
  * faster block/confirmation times
  * buying b/c: increase vote weight, speculators, raining
  * active, transparent community, see e.g. IRC, mumbles
  * helping science
  * when one stops with a coin, here at GRC you can still use your PC for other things, while an ASIC may not be suitable for all things

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Monday Mar 06, 2017 at 12:24 GMT_

----

see also:[Why Gridcoin are better than Bitcoin](https://cryptocointalk.com/topic/52861-why-gridcoin-are-better-than-bitcoin/#entry234717)

**Comment by skcin** [comment]
<a href="https://github.com/gustav1976"><img src="https://avatars3.githubusercontent.com/u/6749756?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gustav1976](https://github.com/gustav1976)**
_Monday Mar 06, 2017 at 12:32 GMT_

----

this could be consolidated on wiki.gridcoin.us

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Tuesday May 02, 2017 at 19:53 GMT_

----

related: #124

**Comment by jring-o** [comment]
See:

https://gridcoin.world/
https://gridcoin.world/Gridcoin%20Highlights%20Final.pdf
