### ISSUE TITLE
contact Lykke exchange (where we applied) also, so they accept us

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#42]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 01:40 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/39_

----

we applied to Lykke exchange 
* https://cryptocointalk.com/topic/51655-lykke-exchange/

please contact them additionally (email, [twitter](https://twitter.com/LykkeCity)) to bring more attention to it, thx

mentioned in [hangout 22](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_01_21.MD):

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Jan 22, 2017 at 14:59 GMT_

----

Related: https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/24

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Wednesday Aug 02, 2017 at 06:17 GMT_

----

see:
* [Vote for Gridcoin to be added to Lykke exchange](https://steemit.com/gridcoin/@scalextrix/vote-for-gridcoin-to-be-added-to-lykke-exchange)

and also:
* "122 votes for Golem and just 22 for Gridcoin. Marketing does pay off." ([here](https://www.reddit.com/r/gridcoin/comments/6qxxhx/most_desired_tokens_on_lykke_exchange_vote_for/?st=j5umejwr&sh=0e432fae))

**Comment by NeuralMiner** [comment]
Lykke has changed its listing process. The exchange has been added to the exchange listing document for followup.
