### ISSUE TITLE
select good, decentralized exchanges for Gridcoin

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#43]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 01:43 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/40_

----

@grctest from RSVP:

We should apply to:
* https://cosmos.network
* https://interledger.org/ (Hangouts: https://soundcloud.com/user-878991006 )
* http://heatledger.com/ (CCEDK associated)
* https://komodoplatform.com/dex-whitepaper/ (Just a whitepaper for now? SuperNet's EasyDEX)
* https://www.instantdex.org/2016/09/28/forum-disabled-easydex-soon/ (InstantDEX vs EasyDEX vs Iguana?)
* https://bcexchange.org/ ( Unsure of validity, but they mention the addition of altcoins).
* https://etherex.org/ (Site down!)
* https://wavesplatform.com/ (If we partnered with one of their gateways then GRC may be traded with tokens on their platform, low likelihood though).

Any more anyone knows of?

Some of these platforms could result in whales moving into GRC from major alts.

mentioned in [hangout 22](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_01_21.MD): 

related: #39

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Jan 22, 2017 at 14:59 GMT_

----

Related: https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/24

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Jan 22, 2017 at 16:56 GMT_

----

EtherEX is now back online.

Edit: I have just contacted the Heat Ledger team, directing them to this task. Here's hoping :)

We have the OPEN.GRC:OPEN.HEAT trading pair featured on the [dashboard of the Gridcoin BTS UI](https://bitsharestalk.org/index.php/topic,23722.0.html).

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 19:12 GMT_

----

@Peppernrino found the twitter accounts so far:

https://twitter.com/heatcurrency
https://twitter.com/cosmos_hq
https://twitter.com/KomodoPlatform
https://twitter.com/Interledger
https://twitter.com/MagicNxt

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Monday Jan 23, 2017 at 17:53 GMT_

----

i was also mentioning that we might be able to setup an anonymous wishlist/point of sale using https://twitter.com/delivery_code

**Comment by skcin** [comment]
<a href="https://github.com/MagixInTheAir"><img src="https://avatars1.githubusercontent.com/u/8146140?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MagixInTheAir](https://github.com/MagixInTheAir)**
_Monday Aug 28, 2017 at 20:34 GMT_

----

Any updates ?

**Comment by grctest** [comment]
No updates on these decentralized exchanges adding Gridcoin, we've got Bitshares and BISQ support at least. Users will need to repeatedly request support for GRC on these exchanges, but given our current coinmarketcap ranking it's unlikely we'll be prioritized.

**Comment by grctest** [comment]
We should contact the following Bitshares gateways to replace OpenLedger:
* Rudex
* Crypto-Bridge
* Easydex
