### ISSUE TITLE
$50 or $100 bounty -> developping PoSv3

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#46]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 17:35 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/43_

----

technical details: [here](https://github.com/gridcoin/Gridcoin-Research/issues/106)

quoting bounty from @frank0051 from there:
"
Given this, if it helps at all, I am going to vote yes on this item but **I'm also willing to donate $50 or $100 to the development of this**. While it's not much, maybe if other people are willing to do so it could be a bigger incentive.
"

see also: https://cryptocointalk.com/topic/52091-grcsidedevelopment/

keep in mind:
* there's a related poll still ongoing, see [here](https://steemit.com/gridcoin/@erkan/gridcoin-poll-should-we-implement-posv3to-combat-low-network-stake-weight-vote-until-february-8)

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Jan 22, 2017 at 19:17 GMT_

----

Vortac: "but can we really implement PoSv3 on a bounty? What if someone offers even a larger bounty tomorrow for reverting back to PoSv2? The [vote](https://steemit.com/gridcoin/@erkan/gridcoin-poll-should-we-implement-posv3to-combat-low-network-stake-weight-vote-until-february-8) has just begun on this, shouldn't we at least wait until the vote is over?" ([forum](https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1217#entry232131))

cc @Vortac2

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Jan 22, 2017 at 20:19 GMT_

----

Regarding the poll, I agree that creating the poll was a premature knee-jerk. https://github.com/gridcoin/Gridcoin-Research/issues/106#issuecomment-273724480

Technical polls should last at least two months in order to drive attention to a topic.

A better poll would ask if they had read the github issue and huppdiwupp's proposals (as a pre-req checklist), then ask if they are content with the current pos:dpor balance or if they would prefer one of huppdiwupp's proposals as well as include 'posv3' features as options (fixed rewards, no offline interest gained).

We should also look into creating the survey using surveymonkey, it might get more info across than the wallet (though it wouldn't have mandate due to no balance/mag weight).

**Comment by skcin** [comment]
<a href="https://github.com/barton2526"><img src="https://avatars0.githubusercontent.com/u/20938755?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [barton2526](https://github.com/barton2526)**
_Sunday Jan 22, 2017 at 21:26 GMT_

----

Seeing as I have just begun running the 7 day logging experiment, I see no point in getting ahead of ourselves with PoSv3.  Let us get all the facts before we start jumping to development.

**Comment by skcin** [comment]
<a href="https://github.com/frank0051"><img src="https://avatars2.githubusercontent.com/u/3454785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [frank0051](https://github.com/frank0051)**
_Monday Jan 23, 2017 at 06:52 GMT_

----

@barton2526 : I would like to see 30 days of history if at all possible - that would also help inform https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/23 

Thoughts?

**Comment by skcin** [comment]
<a href="https://github.com/barton2526"><img src="https://avatars0.githubusercontent.com/u/20938755?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [barton2526](https://github.com/barton2526)**
_Monday Jan 23, 2017 at 07:19 GMT_

----

@frank0051 Past 7 days I cannot guarantee full node stability (i.e. no downtime).  To be fair, even 7 days is pushing it.  If my internet or power goes out for even 1 second I lose all data with my current setup.  Let's get the 7 day numbers and then work on a better solution.

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Saturday Feb 11, 2017 at 17:10 GMT_

----

2 new polls related to this topic:

* [Are you concerned regarding low network stake weight participation?](https://steemit.com/gridcoin/@erkan/gridcoin-poll-are-you-concerned-regarding-low-network-stake-weight-participation-vote-until-march-13) (vote until March 13)

* [Should the DPOR:POS mechanism be rebalanced?](https://steemit.com/gridcoin/@erkan/gridcoin-technical-poll-should-the-dpor-pos-mechanism-be-rebalanced-vote-until-june-11) (vote until June 11)

**Comment by skcin** [comment]
<a href="https://github.com/MagixInTheAir"><img src="https://avatars1.githubusercontent.com/u/8146140?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MagixInTheAir](https://github.com/MagixInTheAir)**
_Monday Aug 28, 2017 at 09:34 GMT_

----

Updates ?

**Comment by skcin** [comment]
<a href="https://github.com/tomasbrod"><img src="https://avatars1.githubusercontent.com/u/11995799?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tomasbrod](https://github.com/tomasbrod)**
_Monday Aug 28, 2017 at 17:29 GMT_

----

The polls were misleading, even the results were not clear. I think there should be a series of very specific polls, like:
* Should interest rate be reduced to xx%?
* Should PoS interest be replaced by fixed block rewards?

All of them should have link to clear description of the topic, what the options mean and what are the expected effects, pros and cons of them. So voters can actually know what they are voting for.
#45

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Monday Sep 18, 2017 at 08:16 GMT_

----

see also new poll:
* [Should Gridcoin implement fixed POS block rewards?](https://steemit.com/gridcoin/@erkan/technical-poll-should-gridcoin-implement-fixed-pos-block-rewards-vote-until-oct-1) (vote until Oct. 1)

**Comment by grctest** [comment]
POSv3 is not going to be implemented, fixed blocks may be implemented however that's a different topic.
