### ISSUE TITLE
analytics on solo miners (new ones, gone again, activity level, ...)

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#49]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Monday Jan 23, 2017 at 11:25 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/46_

----

back in August: though gaining more miners, the activity level of miners dropped
  * new miners have problems ?
  * newbie boost misused ?

starting points:
* e.g. boincstats shows new team members
* CPID leaderboard
* search patterns in usernames

also important for:
* checking on cheating for: [foundation funds in the new faucet](https://steemit.com/gridcoin/@erkan/gridcoin-poll-sponsored-fund-for-gridcoinstats-eu-faucet-20k-grc-paid-via-foundation-funds-vote-until-january-29)

mentioned in [hangout 2](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_08_13.MD): 1:44:30 + mentioned in [hangout 7](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_09_17.MD)

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Monday Jan 23, 2017 at 13:25 GMT_

----

There's like 500 active users out of 1400+ in the pool.
There's only like 1500 registered in the NN ([perhaps due to beacons expiring](https://github.com/gridcoin/Gridcoin-Research/issues/183)), out of 12k+ total in team Gridcoin.
There's 200k active BOINC users, out of 4 million total registered.

Looking at the active:total BOINC users, you can see the apathy after a while, people lose interest.

**Comment by grctest** [comment]
You can see most of these figures on gridcoinstats now.
