### ISSUE TITLE
How-To: Run the windows wallet client under Linux via WINE

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#52]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Monday Jan 23, 2017 at 13:56 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/49_

----

@fkinglag wanted to create such a doc once

not sure about its status, and keep the roadmap in mind:
* "[The linux client will get same features as the Windows version (e.g. Voting UI, Foundation UI, Neural Network UI)](https://steemit.com/gridcoin/@erkan/gridcoin-roadmap-2017-2019)"

but that is for June/July, perhaps even later when other problems come in

mentioned in [hangout 2](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_08_13.MD):

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Monday Jan 23, 2017 at 14:07 GMT_

----

I believe that @fkinglag managed to get it almost fully working, though he was using [PlayOnLinux](https://www.playonlinux.com), not Wine.

**Comment by skcin** [comment]
<a href="https://github.com/Tahvok"><img src="https://avatars3.githubusercontent.com/u/6513056?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tahvok](https://github.com/Tahvok)**
_Sunday Apr 23, 2017 at 15:30 GMT_

----

Doesn't Rob and some other developer work on a qt ui for this?

**Comment by skcin** [comment]
<a href="https://github.com/tomasbrod"><img src="https://avatars1.githubusercontent.com/u/11995799?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tomasbrod](https://github.com/tomasbrod)**
_Monday Apr 24, 2017 at 16:58 GMT_

----

@Tahvok There is qt gui for voting and of course the wallet. The neural network and everything around it is still in dotnet. However there are plans to port everything either to cross platform c# mono or better yet to C++.

**Comment by RoboticMind** [comment]
Can this be closed since there isn't any .NET code in the wallet anymore?
