### ISSUE TITLE
Once Bitshares has implemented fixes, reset the GRIDCOIN MPA!

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#54]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grctest](https://github.com/grctest)**
_Monday Jan 23, 2017 at 15:58 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/51_

----

https://github.com/bitshares/bitshares-core/issues/216
https://bitsharestalk.org/index.php/topic,23334.msg299146.html#msg299146

TL;DR: The GRIDCOIN MPA suffered a 'blackswan' event, where a massive pump on Poloniex (upper double digit rise) then a subsequent dump a couple days later caused the collateral backing the GRIDCOIN MPA tokens to be insufficient & the BTS system locked the asset.

Turns out there wasn't the ability to unlock/reset the asset after the blackswan event, this has resulted in further development to the Bitshares network (and will require a hard fork on their network!).

Once the fixes are in place, I will reset the MPA & we'll be back in fully decentralized business! 👍

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Apr 30, 2017 at 21:51 GMT_

----

https://github.com/bitshares/bsips/blob/master/bsip-0017.md BSIP is still listed as a draft, it might be a while before we get the 'GRIDCOIN' MPA operational again. Given the volatility of GRC's price we may repeatedly encounter 'blackswan' events though..

**Comment by grctest** [comment]
https://github.com/bitshares/bsips/blob/master/bsip-0018.md BSIP 18 is working on fixing the global settlement issues, so we should be able to revive GRIDCOIN in less than a month's time.

**Comment by grctest** [comment]
BSIP 18 was implemented & the GRIDCOIN MPA is operational again!
