### ISSUE TITLE
investigate: assign team admins with lesser permission

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#64]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Tuesday Jan 24, 2017 at 13:52 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/61_

----

it seems: the team founder can create + give less rights to team admins

mentioned in [hangout 4](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_08_27.MD) for investigation

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Tuesday Jan 24, 2017 at 14:21 GMT_

----

I checked, there is not the ability to assign sub-admins with less privileges. Besides, what would be the point?

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Tuesday Jan 24, 2017 at 15:36 GMT_

----

listen at pos: 1:23:50

it was about dividing tasks/responsibilities 
(e.g. b/c Rob would not have time for tasks like emailing users or other tasks), 
and NM thought there is such an option, and you wanted to check 
@Peppernrino checked at that time and saw such an option (assigning team admins), at position 1:28:00

perhaps not each BOINC project has it, because they use different BOINC server versions ?

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Tuesday Jan 24, 2017 at 16:18 GMT_

----

I can select another user to transfer the full team admin rights to, that's about it.

Highly probable that BOINC projects are running old code, you can tell if they're still not running the bootstrap front-end.

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Tuesday Jan 24, 2017 at 16:28 GMT_

----

from http://asteroidsathome.net/boinc/team_admins.php?teamid=******

"Add or remove Team Admins

You can select team members as 'Team Admins'. Team Admins can:

    Edit team information (name, URL, description, country)
    View the team's join/quit history
    Moderate the team forum, if any (admins get email notification of moderation events and red X reports) 

Team Admins cannot:

    Change the team founder
    Remove members
    Add or remove Team Admins 

If a Team Admin quits the team, they cease to be a Team Admin.

We recommend that you select only people you know and trust very well as Team Admins."

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Saturday Feb 04, 2017 at 21:29 GMT_

----

i think we just need to make a list of all the projects that this is possible.

being that i founded a BOINC-wide team, i might be able to admin on every page. i'll let you know.

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Thursday Mar 16, 2017 at 22:35 GMT_

----

according to Amicable's founder page, admins can also send messages to users.

**Comment by skcin** [comment]
<a href="https://github.com/MagixInTheAir"><img src="https://avatars1.githubusercontent.com/u/8146140?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MagixInTheAir](https://github.com/MagixInTheAir)**
_Monday Aug 28, 2017 at 20:50 GMT_

----

Updates ?

**Comment by grctest** [comment]
Given that we don't use team forums within BOINC projects, I don't think it's neccessary to allocate sub-team-admins.
