### ISSUE TITLE
create posters, flyers, ... (for marketing activities, showing your personal interests, ...)

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#66]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Wednesday Jan 25, 2017 at 11:36 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/63_

----

* e.g. for distributing on universities
* but can be also everywhere else, thus different posters/flyers/stickers/... need to be created for different target groups
* we can include some of the existing pics from the ads already
* for various target groups: slogan/motto search, is in other task: #64

mentioned in [hangout 5](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_09_03.MD): 0:55:07

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Wednesday Jan 25, 2017 at 13:27 GMT_

----

A4 sized posters - I could place these in Computer Science areas of my Uni, likewise so could many other Gridcoin users.

**Comment by skcin** [comment]
<a href="https://github.com/phdGuru"><img src="https://avatars2.githubusercontent.com/u/18561366?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [phdGuru](https://github.com/phdGuru)**
_Monday Jan 30, 2017 at 02:32 GMT_

----

_Hi ,..
( We all like Google translator. It is sometime funny  : )_
  
Well, we are just 2 guys Started web-design studio in 2006. And i'm a big fan of Gridcoin. 

Not only does it reward you for doing REAL helpful research, It's reward system is designed to pay you in the same way as a pay per share pool so you are rewarded fairly based on the work you do. I know many people already run Gridcoin node, but just think how many people invested resources in ephemeral coins that disappear in next month. Just look for 1 Satoshi coins at exchanges, to see what I mean. We must say thanks God for Gridcoin and bless his developers. Okey) Now more about a topic.

#### Let me introduce art/poster promotion campaign for Gridcoin
I see a lack of good attractive art in Gridcoin crypto-space. To spread the world and promote Gridcoin we run crowdfunding campaign to create a series of posters. This will be a big A3 poster, flyers for different audience, and stickers. Anyone can check current state of balance at block explorer. When our goal minimum 0.8BTC will be reached we notify members. Art will be send to members after 8-10 days by email. Send your email, by the way. Art illustrations will be available at Creative Common license.  Print, share at soical media,, use in your articles, twitter, etc. Every member who will send 4$ will receive a sticker, 14$ or more: 1 poster + 1 sticker + 1 flyer. And 40$ all stickers and posters that we will create for Gridcoin project.

Official campaign address **GRC**  _S7jau7YsU8TH2iqYruJVA1Sxb939BJJe8B_

#### Why our poster campaign will be successful?
Risk exist in any project. But I will do my best to make nice and attractive art. And a big chance that it will going viral. This will lead to growth of Gridcoin currency user base and as a result GRC value at the end.
Links to samples of art will be attached bellow in this thread.
About the author.
I`m ordinary BOINC user, started to mine and trade GRC in 2014, like many other peoples here. I am creative thinking man.
Nominated of award in design at "Exhibition advertising and printing 2015" [1] [Remadays](http://www.remadays.com.ua/index.php/ru/)
Old member of reddit Gridcoin community, somebody already know me. Who not know, i am moderator of [2] [/r/gridcoinjobs](https://www.reddit.com/r/gridcoinjobs/) on reddit.
Active evangelist of citizen science and cryptocurrencies. 
 
Thanks for you attention !
**phpguru**

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Monday Jan 30, 2017 at 03:47 GMT_

----

only $700? where do i sign!??!

**Comment by skcin** [comment]
<a href="https://github.com/Mxmlln1"><img src="https://avatars3.githubusercontent.com/u/25661098?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mxmlln1](https://github.com/Mxmlln1)**
_Friday Feb 10, 2017 at 13:08 GMT_

----

I would distribute something that was A4/A5 in size if someone just created a design I could print off myself.
I think I would start with pinning them up on local University and College notice boards, especially in Computer buildings etc just as grctest said! I would hand some out as well.

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Saturday Feb 11, 2017 at 18:10 GMT_

----

see also: https://cryptocointalk.com/topic/50138-gridcoin-ads-images-and-banners/

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Saturday Feb 18, 2017 at 13:35 GMT_

----

also in smaller form, so people can show their contributions:

"something to keep at my desk at work, a poster or similar, that is unobtrusive and fairly small to express that I am interested in these things. "
(from: [Something to express my interest in Gridcoin and BOINC in general](https://www.reddit.com/r/gridcoin/comments/5uj826/something_to_express_my_interest_in_gridcoin_and/))

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Thursday Aug 10, 2017 at 14:27 GMT_

----

see also:
* [1million block event with prize: slogan + meme contest](https://steemit.com/gridcoin/@erkan/1million-block-event-with-prize-slogan-meme-contest)

**Comment by wisecracka** [comment]
Hey all, I designed some posters and they're currently in the marketing section of our GitHub.

https://github.com/gridcoin-community/Gridcoin-Marketing/tree/master/Gridcoin_Posters
