### ISSUE TITLE
create coordinated AMA thread

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#68]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Wednesday Jan 25, 2017 at 12:02 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/65_

----

e.g. "ask the community anything", and then several users answer there
  * https://www.reddit.com/r/AMA/

* what strategy to use ?
* bundle with other ads/marketing activities ?

mentioned in [hangout 5](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_09_03.MD)

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Wednesday Jan 25, 2017 at 13:19 GMT_

----

/r/iAMA has more than 15million subscribers where as /r/AMA has approx 150k subscribers.

/r/ama rules:
>Moderators can use their discretion to remove posts they think need to be (advertising, repeated reposting of the AMA, no identification [My friend said I should do an AMA, AMA.], or otherwise posts that we feel may deteriorate the subreddit.

/r/iama rules:
> Obvious nonsense or advertising will be removed - this is up to the discretion of the moderators.

I believe that moderators may perceive the AMA as advertising & censor/ban our attempts at an AMA. It's worth inquiring about the idea though.. 

> AMAs need to be about something you have done, not something that you plan to do at some point or are in the process of doing.

Gridcoin isn't in the past tense, technically it's something actively present..

---

We could do an AMA on the less serious AMA subreddits (there's a few) if we're rejected from the main AMA subs. Alternatively, we could do one on Steemit (where censorship does not exist).

edit: Perhaps we'd have the least mod resistance on /r/InternetAMA/ ?

**Comment by skcin** [comment]
<a href="https://github.com/fkinglag"><img src="https://avatars0.githubusercontent.com/u/7227910?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fkinglag](https://github.com/fkinglag)**
_Wednesday Jan 25, 2017 at 14:17 GMT_

----

I also suggest r/casualAMA as another source/venue to help us do this. Having a charity-related thing we could do at the same time would help exposure throughout. Have we ever had any ideas for charity endorsement?

r/AMA, years ago, was changed in order to deter the amount of people constantly making AMA's. In some cases the AMA would be a hit and now the rules are set in place in order to control a narrative on Reddit. We see r/AMA used now as a venue for celebrities and projects to pump their products up into this narrative for exposure. I don't know how they can have these rules against advertising when clearly every AMA made has something being plugged. Reddit was supposed to be a non-profit.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Wednesday Jan 25, 2017 at 14:27 GMT_

----

> Have we ever had any ideas for charity endorsement?

https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/62

**Comment by grctest** [comment]
I think this would be a train wreck if we attempted this, hangouts are far more appropriate for getting personal responses & since we'd be forced to use smaller obscure ama subs this would be unlikely to recruit significant quantities of users.
