### ISSUE TITLE
bring folding@home into BOINC/Gridcoin

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#70]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Thursday Jan 26, 2017 at 09:22 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/67_

----

* see "[FAH on BOINC](https://folding.stanford.edu/home/faq/faq-high-performance/#ntoc15)" why they stopped
* [recent](https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1218) explanation by @grctest:
  * "What's probably more feasible would be to extend the NN to folding@home, but it would require hardcoding within the client.
  * Alternatively, one could create a BOINC project, establish a method of proving FAH account ownership, then replicate their rewarded score into RAC?"

mentioned in [hangout 6](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_09_10.MD) at begin

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Thursday Jan 26, 2017 at 09:38 GMT_

----

I believe that the 18th Gridcoin Hangout might shine some light onto the feasibility of rewarding F@H via Gridcoin as we spoke with the Curecoin team. We should certainly encourage foldingcoin and curecoin to extend their reward mechanism to include the folding BOINC projects.

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Thursday Jan 26, 2017 at 10:10 GMT_

----

from chat:

Optilasgar: Folding@Home had a BOINC testing project once, but retired it and went back to their solo application. Why would they start a 2nd test?

* Erkan_Yilmaz: more pcs, faster reaching their goals
* and the info in link in the github says they had it in 2006, so in 10 years more things may have changed BOINC wise

**Comment by skcin** [comment]
<a href="https://github.com/MagixInTheAir"><img src="https://avatars1.githubusercontent.com/u/8146140?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MagixInTheAir](https://github.com/MagixInTheAir)**
_Monday Aug 28, 2017 at 21:34 GMT_

----

Any updates from F@H ?

**Comment by skcin** [comment]
<a href="https://github.com/tomasbrod"><img src="https://avatars1.githubusercontent.com/u/11995799?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tomasbrod](https://github.com/tomasbrod)**
_Monday Aug 28, 2017 at 21:40 GMT_

----

I support this idea.

The problem is that Gridcoin's current NN system requires CPID to track work done by miner, which i believe Folding does not support.

If Account IDs are to replace CPIDs ([SAAp](https://github.com/gridcoin/Gridcoin-Research/wiki/DEV-CPID-Ownership#secure-account-association-proposal-tomasbrod)), and [DWPp](https://github.com/gridcoin/Gridcoin-Research/wiki/DEV-Neural-Network#dynamic-withess-participation--proposal-tomasbrod) is implemented, this could be very easy to implement on top of that system.

**Comment by grctest** [comment]
How can we establish proof of F@H account ownership though? We currently go by CPID, but if we switch to UserID whilst requiring a proof-of-userid mechanism on their website, we may be unable to prove F@H account ownership unless we copy foldingcoin/curecoin's account verification process?
