### ISSUE TITLE
Improve the performance on single board computers (increase staking participation)

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#72]
<a href="https://github.com/skcin"><img src="https://avatars1.githubusercontent.com/u/14943931?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [skcin](https://github.com/skcin)**
_Thursday Jan 26, 2017 at 14:06 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/69_

----

If we improve the performance on single board computers like the raspberry pi maybe more users will stake 24/7. 
We could provide ready to deploy images to make it easy to get started. (similar to www.peerbox.me)
Or at least provide precompiled gridcoin wallets because compiling on these devices takes some time.

Not everyone has cheap electricity and can afford to run a x86 pc 24/7.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Thursday Jan 26, 2017 at 14:18 GMT_

----

open:
https://github.com/gridcoin/Gridcoin-Research/issues/166

closed:
https://github.com/gridcoin/Gridcoin-Research/issues/153
https://github.com/gridcoin/Gridcoin-Research/issues/157

PiGrid guys should dedicate some time towards this, it's integral to the success (or basic operation) of their distributed hardware. The RAM utilization of the Gridcoin client currently exceeds some low power devices.

Scalextrix has had success recently with monitoring the Gridcoin client on his RPi.

---
Quoting the low stake weight issue to draw attention: https://github.com/gridcoin/Gridcoin-Research/issues/106

**Comment by skcin** [comment]
<a href="https://github.com/denravonska"><img src="https://avatars0.githubusercontent.com/u/135439?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [denravonska](https://github.com/denravonska)**
_Sunday Feb 05, 2017 at 08:41 GMT_

----

I have an ongoing quest for reducing the RAM usage and I believe it can be taken down to the same levels as the Bitcoin wallet. By loading the Gridcoin block data on demand instead of keeping it all in memory should free up some resources. However, it would come at the cost of CPU usage according to Rob. If I manage to solve the RAM issue I'll see if the potential CPU spike can be taken down.

Though I'd want a word on gridcoin/Gridcoin-Research#203 first to avoid unnecessary refactoring.

**Comment by skcin** [comment]
<a href="https://github.com/denravonska"><img src="https://avatars0.githubusercontent.com/u/135439?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [denravonska](https://github.com/denravonska)**
_Tuesday Feb 21, 2017 at 16:32 GMT_

----

My original plan didn't work out due to slow disk access on the Pi. However, I have done some work to reduce the requirements somewhat. Are we at an acceptable level now or do we need to decrease it further?

**Comment by grctest** [comment]
I think it's been improved to an acceptable level - several users have taken to using arch over ubuntu for low power devices, if it gets worse then creating an issue on the gridcoin-research repo is appropriate.
