### ISSUE TITLE
Build a FOSS block explorer site

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#76]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Peppernrino](https://github.com/Peppernrino)**
_Thursday Jan 26, 2017 at 17:17 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/73_

----

This way, everyone can contribute/fix bugs, and no one would have an unfair advantage or insight into numbers or trends that aren't readily apparent to most daily users. Also, any adshare gained could be redistributed to other Gridcoin projects, not retained by a single person.

If one was feeling up to the task, this could also be used as an opportunity to start the previously discussed Gridcoin/CureCoin/Foldingcoin "Science Coin Consortium" joint block explorer site.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Friday Jan 27, 2017 at 09:43 GMT_

----

There's open source block explorer libraries we can use, however these don't cover any of the custom elements within the GRC network.

It'd be really cool if either gridresearchcorp or gridcoinstats were to open source in return for a fat bounty (which would offset potentially lost ad revenue).

---

> no one would have an unfair advantage or insight into numbers or trends that aren't readily apparent to most daily users.

Most of the gathered data by startail is publicly displayed, thus there is an equal level of access to transparent data.  In terms of having an unfair advantage, there's nothing stopping users from gathering BOINC statistics to compare against the NN to aid in competitive crunching.

**Comment by skcin** [comment]
<a href="https://github.com/Peppernrino"><img src="https://avatars2.githubusercontent.com/u/18277943?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Peppernrino](https://github.com/Peppernrino)**
_Saturday Jan 28, 2017 at 07:13 GMT_

----

except maybe skill level, or computer savvy. i'm talking about AVERAGE people. normies. 😛 lol

**Comment by skcin** [comment]
<a href="https://github.com/grcjamezz"><img src="https://avatars0.githubusercontent.com/u/20879295?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grcjamezz](https://github.com/grcjamezz)**
_Monday Apr 03, 2017 at 07:06 GMT_

----

Awesome idea @Peppernrino. 

Yes as CU said " Most of the gathered data by startail is publicly displayed, thus there is an equal level of access to transparent data." 

But the other 99.2% of us have no idea how to access that data let alone read/use or display the NN data I guess in the same fasion moving from ASCII to binary blocks and gridcoinresearchcorp not being able to read the blocks now , startails site does and RTmoney_ is well versed in gridcoin.

**Comment by skcin** [comment]
<a href="https://github.com/Erelas"><img src="https://avatars3.githubusercontent.com/u/29852022?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erelas](https://github.com/Erelas)**
_Sunday Jul 09, 2017 at 21:49 GMT_

----

This "normie" would like to help, and has very little idea where to start.  I do however, understand the concept of not re-inventing the wheel and would hope that offering a bounty to gridresearchcorp or gridcoinstats would be the way to go.  Once the source was in hand, then if for nothing else, in the interest of learning more about it, I would personally be willing to host an explorer.

**Comment by skcin** [comment]
<a href="https://github.com/bryhardt"><img src="https://avatars2.githubusercontent.com/u/6340624?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bryhardt](https://github.com/bryhardt)**
_Sunday Jul 09, 2017 at 21:59 GMT_

----

i would be more than willing to host an explorer with the pool. just didnt want to duplicate either or step on toes. i have some experience running explorer for another not so normal coin, so another one would be cool.

**Comment by skcin** [comment]
<a href="https://github.com/Erelas"><img src="https://avatars3.githubusercontent.com/u/29852022?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erelas](https://github.com/Erelas)**
_Sunday Jul 09, 2017 at 22:16 GMT_

----

Educate me!  No seriously, without being too much of a bother, I am happy to learn to do new things.

**Comment by skcin** [comment]
<a href="https://github.com/frank0051"><img src="https://avatars2.githubusercontent.com/u/3454785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [frank0051](https://github.com/frank0051)**
_Wednesday Aug 02, 2017 at 20:46 GMT_

----

Just curious, given we have at least 3 block explorers, how come none of our community members have open-sourced theirs???

**Comment by skcin** [comment]
<a href="https://github.com/frank0051"><img src="https://avatars2.githubusercontent.com/u/3454785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [frank0051](https://github.com/frank0051)**
_Monday Aug 07, 2017 at 14:24 GMT_

----

I've added a suggestion to one of the Steem It posts about open-source block. Up-vote it so we can get on CM's radar, haha. https://steemit.com/gridcoinstats/@sc-steemit/brainstorming-gridcoinstats-ideas-thread-25-sbd-in-prices#@frank0051/re-sc-steemit-brainstorming-gridcoinstats-ideas-thread-25-sbd-in-prices-20170807t142205918z

**Comment by skcin** [comment]
<a href="https://github.com/Erelas"><img src="https://avatars3.githubusercontent.com/u/29852022?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erelas](https://github.com/Erelas)**
_Monday Aug 07, 2017 at 18:10 GMT_

----

AH, glad you sent another e-mail because I totally missed your first one.
HOnestly, not to avoid your question, I really don't have an answer.  For
all I know it might be part of a thesis or something scholastic and he
wishes to keep it under wraps until published?  Honestly no clue and I
don't have the technical knowledge to answer adequately.  Thanks for the
info though, I will take a look at the FOSS stuff you sent the link to,
might be able to figure it out eventually :)

**Comment by NeuralMiner** [comment]
Completed here: https://github.com/gridcoin-community/BlockExplorer
