### ISSUE TITLE
Integrate any required/desired tools into the gridcoin-community org

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#79]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grctest](https://github.com/grctest)**
_Monday Jan 30, 2017 at 14:46 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/76_

----

https://cryptocointalk.com/topic/52186-gridcoin-community-development-process-idea/#entry232500

We've created a gridcoin-community organization, where we can explore improved github workflow.

What tools should we directly integrate into the org or individual repos? We can add them as long as they're free, any requests?

https://github.com/integrations?utf8=%E2%9C%93&query=

Originally raised:
https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/41

**Comment by skcin** [comment]
<a href="https://github.com/denravonska"><img src="https://avatars0.githubusercontent.com/u/135439?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [denravonska](https://github.com/denravonska)**
_Monday Jan 30, 2017 at 14:51 GMT_

----

We can consider following [gitflow](https://github.com/nvie/gitflow). It's pretty well adapted so if we start using it as well people know what to expect in terms of branching, merging and releases.

**Comment by skcin** [comment]
<a href="https://github.com/LokiToki"><img src="https://avatars0.githubusercontent.com/u/25841155?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LokiToki](https://github.com/LokiToki)**
_Tuesday Mar 14, 2017 at 10:15 GMT_

----

I'm totally new to github and would like to see the correct usage of the default tools. Additionally i would advise to keep it as simple as possible with a clear structure. 

Is this community org repo ready-to-use? If yes i put it in the next easy-dev-start Virtual Machine instead of the master-branch.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Tuesday Mar 14, 2017 at 12:59 GMT_

----

The community org repo is behind master in terms of development, you should include the official gridcoin-research repo's development branch instead.

**Comment by tomasbrod** [comment]
Is this still relevant? We have Travis CI included, and I do not see any other <TOOL> that might be needed.

**Comment by NeuralMiner** [comment]
Closing.
