### ISSUE TITLE
another Thunderclap campaign ?

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#80]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Tuesday Jan 31, 2017 at 18:25 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/77_

----

last one: [4 months ago](https://www.thunderclap.it/projects/46914-science-currency-gridcoin)

"The beauty is you can use it for basically any event — be it the launch, funding news, stats announcement, a pivot, etc." (from [here](https://medium.com/@lucdudler/6-things-you-should-know-before-using-thunderclap-bc0855efb4db#.7oscscpzh))

has to be decided when and about which event

mentioned in [hangout 7](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_09_17.MD):

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Wednesday Feb 01, 2017 at 16:06 GMT_

----

I don't think it's worth doing another ThunderClap campaign, we saw negligible results on google analytics from twitter & it quite heavy on the twitter spam in the weeks running up to the 'clap'.

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Wednesday Feb 08, 2017 at 21:21 GMT_

----

mentioned in [hangout 8](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_09_24.MD): to use an image if possible next time

check if image is only allowed for pro accounts ?

**Comment by skcin** [comment]
<a href="https://github.com/gustav1976"><img src="https://avatars3.githubusercontent.com/u/6749756?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gustav1976](https://github.com/gustav1976)**
_Tuesday Feb 14, 2017 at 15:36 GMT_

----

we want to launch a thunderclap when the website "gridcoin.io" is ready. will be in 3-5 weeks.

**Comment by grctest** [comment]
Thunderclap campaign underway for gridcoin.io
