### ISSUE TITLE
Create a more user friendly macOS / OSX tutorial

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#82]
<a href="https://github.com/PsiPhiTheta"><img src="https://avatars0.githubusercontent.com/u/25353324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [PsiPhiTheta](https://github.com/PsiPhiTheta)**
_Thursday Feb 02, 2017 at 22:06 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/79_

----

As I just finished helping my friend out to set up his Gridcoin wallet, I noticed a lot of extra work had to be done and research on various other websites was required to get everything up and running smoothly. It seems like the installing Gridcoin on OSX wiki page is seriously outdated and I believe the community could do with having a properly built installation package for mac present on the main Gridcoin website with simple clear instructions. This would avoid individual users having to mess around and tweak many things to get everything going. I truly believe the simpler the steps and the easier to get going the more Gridcoin users can be attracted.

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Thursday Feb 02, 2017 at 22:44 GMT_

----

I assume [this](http://wiki.gridcoin.us/OS_X_Guide) is the wiki page you are referring to ?

**Comment by skcin** [comment]
<a href="https://github.com/PsiPhiTheta"><img src="https://avatars0.githubusercontent.com/u/25353324?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [PsiPhiTheta](https://github.com/PsiPhiTheta)**
_Thursday Feb 02, 2017 at 22:59 GMT_

----

Yup

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Sunday Feb 19, 2017 at 09:21 GMT_

----

see also: [Streamline OSX build process](https://github.com/gridcoin/Gridcoin-Research/issues/211)

**Comment by skcin** [comment]
<a href="https://github.com/acey1"><img src="https://avatars0.githubusercontent.com/u/13197251?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [acey1](https://github.com/acey1)**
_Sunday Sep 03, 2017 at 09:28 GMT_

----

Done son! The OS X Guide and new logo implemented on the Wiki. Have a look here: 

http://wiki.gridcoin.us/OS_X_Guide

**Comment by grctest** [comment]
Great work @acey1

**Comment by acey1** [comment]
Thank you @CM
