### ISSUE TITLE
improving Gridcoin presence on steemit

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#87]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Wednesday Feb 08, 2017 at 21:35 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/84_

----

These can be separated later on as own tasks, first let's see which useful, ...

pinging: @grctest

* go on steem **radio channels/streams**
  * see task: [go to other coins' conference calls/meetups/podcasts](https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/21)
* promotion/**boost** on steemit
  * to get into popular lists/pages
* make own **Gridcoin steemit web frontend** for the steemit backend
  * has only Gridcoin content then (or also selected others)
  * web dev needed
* join some steem **upvote groups**
* (use tags in posts more)

The effects of above may be increased/attention when combined with:
  * creating a Gridcoin witness: #85

Mentioned in [hangout 8](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_09_24.MD).

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Friday Apr 21, 2017 at 19:19 GMT_

----

I've created https://beyondboinc.net to help improve Gridcoin's presence on Steemit.
I'll customize it to promote BOINC/Gridcoin in the navigation bar.

**Comment by grctest** [comment]
I think we've done well getting Gridcoin promoted/active/trending on steemit, don't think this needs a task anymore.
