### ISSUE TITLE
maintaining presence on BeyondBitcoin calls

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#96]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Saturday Mar 18, 2017 at 23:42 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/92_

----

every Friday is the BB conference call:
* appearing there will keep people from other coins interested in Gridcoin

mentioned in [hangout 26](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_03_18.MD) and others

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Saturday Mar 18, 2017 at 23:47 GMT_

----

I cannot always attend the BeyondBitcoin hangouts and we miss the hangouts frequently, these hangouts are great exposure for Gridcoin and the Beyond Bitcoin community is very cool - they provide us the mumble server space! :)

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Mar 19, 2017 at 00:42 GMT_

----

https://steemit.com/beyondbitcoin/@officialfuzzy/guest-signups-beyond-bitcoin-hangout-199-3-24-17-rsvp-to-guest-speak-about-your-blockchain-project-last-week-s-payouts-signups#@cm-steem/re-officialfuzzy-guest-signups-beyond-bitcoin-hangout-199-3-24-17-rsvp-to-guest-speak-about-your-blockchain-project-last-week-s-payouts-signups-20170319t003536329z

I've RSVP'd to the 200th episode, please suggest topics for me to discuss.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Tuesday May 23, 2017 at 18:26 GMT_

----

https://steemit.com/beyondbitcoin/@officialfuzzy/guest-signups-beyond-bitcoin-hangout-208-5-26-17-debut-your-project-for-a-cut-of-hangout-earnings#@cm-steem/re-officialfuzzy-guest-signups-beyond-bitcoin-hangout-208-5-26-17-debut-your-project-for-a-cut-of-hangout-earnings-20170523t172520610z

RSVP'd to the 208th episode, looking for anything else to include!

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Saturday Jun 10, 2017 at 19:30 GMT_

----

I represented Gridcoin during the 209th & 210th hangouts:
* [#210](https://steemit.com/beyondbitcoin/@glitterfart/gridcoin-hangout-2017-06-09-beyond-bitcoin-radioshow-raw-recording-for-impatients)
* [#209](https://steemit.com/beyondbitcoin/@glitterfart/gridcoin-2017-06-02-beyond-bitcoin-radioshow-raw-recording-for-impatients)

**Comment by grctest** [comment]
Been like 3 weeks since I last did a BeyondBitcoin GRC appearance, I should get around to attending again.
