### ISSUE TITLE
200k GRC bounty -> for removing/improving "team requirement"

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Tasks#98]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Monday Mar 20, 2017 at 11:02 GMT_
_Originally opened as https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/94_

----

* needs to be defined for what code/task/feature exactly that bounty would be

further info on topic: https://github.com/gridcoin/Gridcoin-Research/issues/212

mentioned in [hangout 26](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2017_03_18.MD): making a bounty for removing/improving "team requirement"

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Monday Mar 20, 2017 at 12:26 GMT_

----

Related: https://github.com/gridcoin/Gridcoin-Research/issues/212

I pledge 50k GRC to anyone that can implement a DPOR/NN solution which is capable of supporting the entire BOINC network (250k to 4 million users) in a decentralized/distributed manner.

We could potentially bring foundation funds into the mix if this proves to be a significant amount of work?

Edit: Further clarification for bounty reward -> Solution must remove the team req, scale back the quantity of users responsible for the data gathering phase and scale up to between 250k-4mil users.

**Comment by skcin** [comment]
<a href="https://github.com/gustav1976"><img src="https://avatars3.githubusercontent.com/u/6749756?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gustav1976](https://github.com/gustav1976)**
_Monday Mar 20, 2017 at 13:28 GMT_

----

yes, this should be in the interest of us all, so let's incorporate foundation funds. I'd vote in favour of that.

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Monday Mar 20, 2017 at 17:17 GMT_

----

[lennstar](https://steemit.com/@lennstar) wrote [here](https://steemit.com/gridcoin/@erkan/get-bounties-for-helping-team-gridcoin-v2#@lennstar/re-erkan-get-bounties-for-helping-team-gridcoin-v2-20170320t170602794z):
"If supporting means in the normal client and without overloading a normal user or project, then I put in 20K too."

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Monday Mar 20, 2017 at 23:58 GMT_

----

Vortac adds another 30k GRC [here](https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1231#entry235612):
* "However, if we go the bounty way, then I pledge another 30k GRC."

and also says:
* "I think we should have a Foundation expense (and vote) for this. Would give more weight to it and become a final stance on the matter. After all, if this is implemented, it will affect the whole network (ultimately positively, I hope)."

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Tuesday Mar 21, 2017 at 07:29 GMT_

----

from [ALIEN](https://cryptocointalk.com/user/161-a-l-i-e-n/), [here](https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1231#entry235640):
"I pledge **100K** if you guys think the bounty approach will be fruitful.  I don't think it would be an issue for the foundation to cover any remaining amount after community donations for a total 1 mil GRC bounty.  It would be a large project and the reward should reflect the caliber of work we would be expecting.  There could maybe be an additional reward for providing 6 months of support or something to ensure it transitions smoothly."

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Apr 09, 2017 at 22:14 GMT_

----

If we can harden proof of CPID ownership, and reduce the amount of data that we would be downloading from project web servers (less than the full user.xml.gz file which has irrelevant data) we could potentially remove the mandatory team requirement with minimal changes to the neural network : https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/101

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Saturday Apr 29, 2017 at 12:56 GMT_

----

https://github.com/gridcoin/Gridcoin-Research/issues/289

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Thursday May 11, 2017 at 14:18 GMT_

----

Just to confirm, regardless of the trading rate of GRC my 50k GRC commitment to this issue stands, it's one of the highest priority issues IMO.

Like/Retweet: https://twitter.com/customminer/status/862633377689726976

**Comment by skcin** [comment]
<a href="https://github.com/Vortac2"><img src="https://avatars0.githubusercontent.com/u/24814168?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Vortac2](https://github.com/Vortac2)**
_Thursday May 11, 2017 at 15:21 GMT_

----

Absolutely, my commitment is firm as well. I would support a new Foundation expense too.

**Comment by skcin** [comment]
<a href="https://github.com/mistermarmot"><img src="https://avatars2.githubusercontent.com/u/22854638?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mistermarmot](https://github.com/mistermarmot)**
_Thursday May 18, 2017 at 20:50 GMT_

----

Team loyalty (tribalism oxytocin function) is a major impediment to getting people to leave the team they were with for years and join us even with profit motive.

As a first step of implementation, I was suggesting to Erkan in IRC, that we allow teams to join as pools.  
It maybe that no team will join, but of all the teams, it seems likely that many might want to earn some coin even if it means giving up individual contribution RAC as long as they can see their team possibly beat our pools or high ranking individuals.   Many teams would love to get the epeen of stomping us on our 'own field', but yet GRC still gets loyal adopters and spreads it's circulation to more people.

We will likely gain new Gridcoin users from their team mates that want their individual RAC back.

My coding abilities are 30 years out of date so, is this more easily accomplished than the individual, teamless, implementation?

**Comment by skcin** [comment]
<a href="https://github.com/Foggyx420"><img src="https://avatars3.githubusercontent.com/u/13292864?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Foggyx420](https://github.com/Foggyx420)**
_Thursday May 18, 2017 at 21:06 GMT_

----

Iam a little confused as to the direction you are speaking of @mistermarmot . Please expand on your comment.

My thoughts:
if we allow teams as pools it still would need the team requirement part removed.
also a Pool would still require a single CPID for a wallet and that wallet paying out everyone and that would be the team trusting that one person to do right. A pool is a group of users working for a single wallet.

Regardless team requirement removal would still allow all users going for gridcoin to remain in there own choice of teams or no team at all. I think this is the better option.

**Comment by skcin** [comment]
<a href="https://github.com/RobertoGaudio"><img src="https://avatars3.githubusercontent.com/u/1216738?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RobertoGaudio](https://github.com/RobertoGaudio)**
_Saturday Jun 10, 2017 at 04:32 GMT_

----

I've thought about it for a while and came up with this possible solution: how about not changing Gridcoin but BOINC? By letting the BOINC user join two teams instead of one people could easily stay in their beloved team and join Team Gridcoin beside it. This way they can continue to crunch for their teams and earn some GRC beside it. 
I think that this would lift up the team requirement barrier for a hell of a lot dedicated crunchers. What do you all think about it?

Regards
RobertoGaudio aka. Nuad

**Comment by skcin** [comment]
<a href="https://github.com/Slapbox"><img src="https://avatars2.githubusercontent.com/u/6835891?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Slapbox](https://github.com/Slapbox)**
_Sunday Jun 11, 2017 at 14:46 GMT_

----

@RobertoGaudio We have to focus on what's within our control. I don't think BOINC is going to change this. It's been this way for 20 years and working well for every purpose but mining GRC.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Jun 18, 2017 at 16:34 GMT_

----

@RobertoGaudio I think that adding a second team to a BOINC account would break a lot of existing 3rd party BOINC statistics websites, and would require all BOINC projects to inherit said change, as opposed to the Gridcoin network changing.

@gregagnew 
> (receiving address, email, md5, project, total credits done)

The email and md5 of the password are confidential and shouldn't be shared with the network. If I have your password's md5, I can login to grab your account key and have established a permanent BOINC account compromise.

**Comment by skcin** [comment]
<a href="https://github.com/RobertoGaudio"><img src="https://avatars3.githubusercontent.com/u/1216738?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RobertoGaudio](https://github.com/RobertoGaudio)**
_Sunday Jun 18, 2017 at 16:57 GMT_

----

@gregagnew : i'm happy that my idea seem to have deduced to a possible solution. :)

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Jun 18, 2017 at 17:07 GMT_

----

@gregagnew So you're proposing to make both the user's email address and password publicly available on the blockchain? This isn't a secure proposal. Email address use within the Gridcoin client is currently entirely private, email addresses are not publicly published. Making your email address publicly known [is massively insecure](https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/106).

We don't need to change the reward mechanism like you're proposing to remove the team requirement. Upgrades to the neural network mechanism, removing the team check and hardening the proof of CPID ownership are in scope of this bounty. (At least for my portion).

I do appreciate the effort though, thanks for the research/work the gridcoin client.

**Comment by skcin** [comment]
<a href="https://github.com/grctest"><img src="https://avatars1.githubusercontent.com/u/15861527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grctest](https://github.com/grctest)**
_Sunday Jun 18, 2017 at 17:19 GMT_

----

> Wait, this entire thread is about removing the team requirement.
>
> "200k GRC bounty -> for removing/improving "team requirement" "
>
> Its literally the name of the thread.

That may be the case, but you must take into account the contents of the thread which lay out the requirements for the bounty.

----

>Nothing is required to be on the blockchain, not email or password.
>> * UserA (Minter) adds POR transaction to block chain with (receiving address, email, md5, project, total credits done), to be confirmed by other 
>> * UserB (Verifier) receives POR block
>> * User verifies e-mail -> recieving address from gridcoin.us
>> * User gets XML from project using email/md5 and verifies work done
>> * User confirms block

You stated in your previous post that UserA signs the POR block with the email/md5, then the verifier verifies the email using the emal/md5. I'm getting mixed messages here.

**Comment by skcin** [comment]
<a href="https://github.com/Foggyx420"><img src="https://avatars3.githubusercontent.com/u/13292864?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Foggyx420](https://github.com/Foggyx420)**
_Sunday Jun 18, 2017 at 19:34 GMT_

----

the email is used for the CPID and many instances in code for using of it. it is not public. sure team founder can access that but with removal of team req a user doesn't have to be in a team for it to be shown.

**Comment by skcin** [comment]
<a href="https://github.com/Erkan-Yilmaz"><img src="https://avatars1.githubusercontent.com/u/642286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Erkan-Yilmaz](https://github.com/Erkan-Yilmaz)**
_Friday Jul 14, 2017 at 08:52 GMT_

----

* a related [Gridcoin poll: Impact to GRC price if team requirement is lifted? (vote until July 25)](https://steemit.com/gridcoin/@erkan/gridcoin-poll-impact-to-grc-price-if-team-requirement-is-lifted-vote-until-july-25)
* see also: "[irc chat about biased answers on this poll](https://github.com/gridcoin/Gridcoin-Research/issues/434)"

**Comment by jamescowens** [comment]
This is being worked on right now....

https://github.com/jamescowens/Gridcoin-Research/commits/integrated_scraper

Also see https://github.com/gridcoin-community/Gridcoin-Research/wiki/Scraper-Brainstorming

**Comment by grctest** [comment]
PR2965 has been fully integrated into the master BOINC branch, it'll be included in the next server release, however BOINC project web servers can implement it ahead of this release.

**Comment by jamescowens** [comment]
This will be closed upon the release of Fern, as all requirements have been met. I believe the bounty should be paid 2/3 to @cyrossignol and 1/3 to me based on the contributions of he and I from Denise through Fern.

**Comment by barton2526** [comment]
@jamescowens this needs to be closed

**Comment by jamescowens** [comment]
The bounty has not been paid.

**Comment by Pythonix** [comment]
Vortac has pledged 30k GRC for this bounty (see https://github.com/gridcoin-community/Gridcoin-Tasks/issues/98#issuecomment-331496093) and he just paid it out.

10k GRC for @jamescowens : http://main.gridcoinstats.eu/tx/a0d4483be74d3444512e6fb0d6a550016de44078b6ab2269c859d9ee88e532a3

20k GRC for @cycy : http://main.gridcoinstats.eu/tx/c6e332788ee423fb48634d1ad377216b6146c91e87d8604a7de8b3a6b8d7f4b5

**Comment by makeasnek** [comment]
This should be closed?

**Comment by wilkart** [comment]
@skcin and @jamescowens
Close please.
